'use client';

import { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type AppLanguage = 'vi' | 'en' | 'zh';

type CopyValue = string | Partial<Record<AppLanguage, string>>;
type CopyMap = Record<string, CopyValue>;

const STORAGE_KEY = 'moly.study.language';

export const LANGUAGES: Array<{ code: AppLanguage; label: string; shortLabel: string; nativeName: string }> = [
  { code: 'vi', label: 'Tiếng Việt', shortLabel: 'VI', nativeName: 'Tiếng Việt' },
  { code: 'en', label: 'English', shortLabel: 'EN', nativeName: 'English' },
  { code: 'zh', label: '中文', shortLabel: '中', nativeName: '中文' },
];

const COPY: CopyMap = {
  'common.language': { vi: 'Ngôn ngữ', en: 'Language', zh: '语言' },
  'common.search': { vi: 'Tìm kiếm', en: 'Search', zh: '搜索' },
  'common.back': { vi: 'Quay lại', en: 'Back', zh: '返回' },
  'common.close': { vi: 'Đóng', en: 'Close', zh: '关闭' },
  'common.save': { vi: 'Lưu thay đổi', en: 'Save changes', zh: '保存更改' },
  'common.cancel': { vi: 'Hủy', en: 'Cancel', zh: '取消' },
  'common.refresh': { vi: 'Làm mới', en: 'Refresh', zh: '刷新' },
  'common.loading': { vi: 'Đang tải...', en: 'Loading...', zh: '正在加载...' },
  'common.all': { vi: 'Tất cả', en: 'All', zh: '全部' },
  'common.view': { vi: 'Xem', en: 'View', zh: '查看' },
  'common.edit': { vi: 'Sửa', en: 'Edit', zh: '编辑' },
  'common.later': { vi: 'Để sau', en: 'Later', zh: '稍后' },
  'common.subject': { vi: 'Môn học', en: 'Subject', zh: '科目' },
  'common.points': { vi: 'điểm', en: 'points', zh: '分' },
  'common.days': { vi: 'ngày', en: 'days', zh: '天' },
  'common.minutes': { vi: 'phút', en: 'minutes', zh: '分钟' },

  'nav.home': { vi: 'Trang chủ', en: 'Home', zh: '首页' },
  'nav.courses': { vi: 'Khóa học', en: 'Courses', zh: '课程' },
  'nav.chooseSubject': { vi: 'Chọn môn học', en: 'Choose a subject', zh: '选择科目' },
  'nav.roadmap': { vi: 'Lộ trình', en: 'Roadmap', zh: '学习路径' },
  'nav.examRoom': { vi: 'Phòng thi', en: 'Exam room', zh: '考试中心' },
  'nav.games': { vi: 'Game học tập', en: 'Learning games', zh: '学习游戏' },
  'nav.docs': { vi: 'Tài liệu', en: 'Materials', zh: '资料' },
  'nav.forum': { vi: 'Diễn đàn', en: 'Forum', zh: '论坛' },
  'nav.qa': { vi: 'Hỏi đáp VIP', en: 'VIP Q&A', zh: 'VIP问答' },
  'nav.blog': { vi: 'Blog', en: 'Blog', zh: '博客' },
  'nav.ranking': { vi: 'Bảng xếp hạng', en: 'Leaderboard', zh: '排行榜' },
  'nav.more': { vi: 'Khác:', en: 'More:', zh: '更多：' },
  'nav.upgrade': { vi: 'Nâng cấp', en: 'Upgrade', zh: '升级' },
  'nav.upgradeVip': { vi: 'Nâng cấp VIP', en: 'Upgrade to VIP', zh: '升级VIP' },
  'nav.login': { vi: 'Đăng nhập', en: 'Log in', zh: '登录' },
  'nav.register': { vi: 'Đăng ký', en: 'Sign up', zh: '注册' },
  'nav.logout': { vi: 'Đăng xuất', en: 'Log out', zh: '退出登录' },
  'nav.profile': { vi: 'Hồ sơ cá nhân', en: 'Profile', zh: '个人资料' },
  'nav.admin': { vi: 'Trang quản trị', en: 'Admin panel', zh: '管理后台' },
  'nav.darkMode': { vi: 'Chế độ tối', en: 'Dark mode', zh: '深色模式' },
  'nav.mobileUpgradeTitle': { vi: 'Nâng cấp tài khoản VIP', en: 'Upgrade your VIP account', zh: '升级VIP账号' },
  'nav.mobileUpgradeDesc': { vi: 'Mở khóa đề VIP, video giải đề và hỏi giảng viên', en: 'Unlock VIP exams, solution videos and instructor Q&A', zh: '解锁VIP试卷、视频解析和教师问答' },
  'nav.viewNow': { vi: 'Xem ngay', en: 'View now', zh: '立即查看' },

  'subject.math': { vi: 'Toán', en: 'Math', zh: '数学' },
  'subject.physics': { vi: 'Vật Lý', en: 'Physics', zh: '物理' },
  'subject.chemistry': { vi: 'Hóa Học', en: 'Chemistry', zh: '化学' },
  'subject.chineseSoc': { vi: 'Tiếng Trung XH', en: 'Chinese Social', zh: '中文（文）' },
  'subject.chineseSci': { vi: 'Tiếng Trung TN', en: 'Chinese Science', zh: '中文（理）' },
  'subject.forum': { vi: 'Diễn đàn', en: 'Forum', zh: '论坛' },

  'home.hero.platform': { vi: 'Nền tảng CSCA', en: 'CSCA Platform', zh: 'CSCA 平台' },
  'home.hero.platformDesc': { vi: 'Luyện thi học bổng Trung Quốc', en: 'Scholarship exam prep for China', zh: '中国奖学金考试备考' },
  'home.hero.signup': { vi: 'Đăng ký miễn phí', en: 'Sign up free', zh: '免费注册' },
  'home.hero.subjectCount': { vi: '4 môn thi', en: '4 exam subjects', zh: '4个考试科目' },
  'home.hero.passRate': { vi: 'Tỷ lệ học viên đậu', en: 'Student pass rate', zh: '学员通过率' },
  'home.stats.students': { vi: 'Học viên', en: 'Students', zh: '学员' },
  'home.stats.exams': { vi: 'Đề thi', en: 'Exams', zh: '套试卷' },
  'home.stats.materials': { vi: 'Tài liệu', en: 'Materials', zh: '资料' },
  'home.stats.passRate': { vi: 'Tỷ lệ đậu', en: 'Pass rate', zh: '通过率' },
  'home.subjects.badge': { vi: '6 môn thi', en: '6 subjects', zh: '6个科目' },
  'home.subjects.title': { vi: 'Chọn môn học của bạn', en: 'Choose your subject', zh: '选择你的科目' },
  'home.subjects.desc': { vi: 'Nội dung chuẩn đề thi CSCA, cập nhật liên tục', en: 'CSCA-aligned content, updated continuously', zh: '贴近CSCA考试内容，持续更新' },
  'home.subjects.studyNow': { vi: 'Học ngay', en: 'Study now', zh: '开始学习' },
  'home.hot.badge': { vi: 'Nổi bật', en: 'Popular', zh: '热门' },
  'home.hot.title': { vi: 'Đề thi hot tuần này', en: 'Popular exams this week', zh: '本周热门试卷' },
  'home.hot.desc': { vi: 'Được nhiều học viên luyện tập nhất', en: 'Most practiced by students', zh: '最多学员练习' },
  'home.hot.all': { vi: 'Xem tất cả', en: 'View all', zh: '查看全部' },
  'home.hot.start': { vi: 'Làm ngay', en: 'Start now', zh: '立即练习' },
  'home.hot.attempts': { vi: 'lượt làm', en: 'attempts', zh: '次练习' },
  'home.countdown.label': { vi: 'CSCA 2026', en: 'CSCA 2026', zh: 'CSCA 2026' },
  'home.countdown.title': { vi: 'Thời gian còn lại đến ngày thi', en: 'Time left until the exam', zh: '距离考试剩余时间' },
  'home.countdown.desc': { vi: 'Đừng để thời gian trôi qua, bắt đầu ôn tập ngay hôm nay', en: 'Do not let time slip away. Start preparing today', zh: '不要让时间流逝，从今天开始备考' },
  'home.countdown.start': { vi: 'Làm ngay', en: 'Start now', zh: '立即做题' },
  'home.countdown.plan': { vi: 'Lên lịch ôn thi', en: 'Plan my study', zh: '制定复习计划' },
  'home.countdown.days': { vi: 'Ngày', en: 'Days', zh: '天' },
  'home.countdown.hours': { vi: 'Giờ', en: 'Hours', zh: '小时' },
  'home.countdown.minutes': { vi: 'Phút', en: 'Minutes', zh: '分钟' },
  'home.countdown.seconds': { vi: 'Giây', en: 'Seconds', zh: '秒' },
  'home.ai.badge': { vi: 'Powered by Gemini AI', en: 'Powered by Gemini AI', zh: '由 Gemini AI 支持' },
  'home.ai.title': { vi: 'Lộ trình học tập', en: 'Personalized', zh: '个性化' },
  'home.ai.titleAccent': { vi: 'cá nhân hóa', en: 'study roadmap', zh: '学习路径' },
  'home.ai.desc': { vi: 'AI phân tích hành vi làm bài của bạn và đưa ra kế hoạch ôn thi chính xác theo điểm yếu.', en: 'AI analyzes your exam history and builds a precise plan around your weak areas.', zh: 'AI分析你的做题记录，并根据薄弱点制定精准备考计划。' },
  'home.ai.try': { vi: 'Thử AI lộ trình', en: 'Try AI roadmap', zh: '试用AI学习路径' },
  'home.features.badge': { vi: 'Tại sao CSCA?', en: 'Why CSCA?', zh: '为什么选择CSCA？' },
  'home.features.title': { vi: 'Học thông minh, đậu chắc', en: 'Study smarter, pass stronger', zh: '智能学习，稳步通过' },
  'home.steps.badge': { vi: '3 bước đơn giản', en: '3 simple steps', zh: '简单三步' },
  'home.steps.title': { vi: 'Bắt đầu ngay hôm nay', en: 'Start today', zh: '今天开始' },
  'home.testimonials.badge': { vi: 'Học viên nói gì', en: 'Student stories', zh: '学员反馈' },
  'home.testimonials.title': { vi: 'Câu chuyện thành công', en: 'Success stories', zh: '成功故事' },
  'home.vip.badge': { vi: 'Premium Access', en: 'Premium Access', zh: '高级权限' },
  'home.vip.title': { vi: 'Nâng cấp CSCA PRO ngay hôm nay', en: 'Upgrade to CSCA PRO today', zh: '立即升级 CSCA PRO' },
  'home.vip.desc': { vi: 'Mở khóa toàn bộ đề thi, lời giải chi tiết và chữa bài tự luận bằng AI. Thành viên VIP và Pre dùng chung đề VIP, Pre có thêm video giải đề và hỏi giảng viên.', en: 'Unlock all exams, detailed solutions and AI essay grading. VIP and Pre share the same VIP exams; Pre also gets solution videos and instructor Q&A.', zh: '解锁全部试卷、详细解析和AI作文批改。VIP和Pre共用VIP试卷，Pre额外包含视频解析和教师问答。' },
  'home.vip.join': { vi: 'Trở thành viên PRO', en: 'Become PRO', zh: '成为PRO会员' },
  'home.final.title': { vi: 'Sẵn sàng chinh phục CSCA?', en: 'Ready to conquer CSCA?', zh: '准备好攻克CSCA了吗？' },
  'home.final.desc': { vi: 'Tham gia cùng hơn 10,000 học viên đang ôn thi mỗi ngày', en: 'Join 10,000+ students preparing every day', zh: '加入超过10,000名每日备考的学员' },
  'home.final.tryExam': { vi: 'Thử làm đề ngay', en: 'Try an exam now', zh: '立即试做' },
  'home.final.freeNote': { vi: 'Miễn phí hoàn toàn · Không cần thẻ tín dụng', en: 'Completely free · No credit card required', zh: '完全免费 · 无需信用卡' },

  'exam.languageHint': { vi: 'Ngôn ngữ đề', en: 'Exam language', zh: '试卷语言' },
  'exam.question': { vi: 'Câu hỏi', en: 'Question', zh: '题目' },
  'exam.sharedPassage': { vi: 'Đoạn văn đọc hiểu dùng chung', en: 'Shared reading passage', zh: '共用阅读材料' },
  'exam.sharedContent': { vi: 'Nội dung dùng chung', en: 'Shared content', zh: '共用内容' },
  'exam.submit': { vi: 'Nộp bài', en: 'Submit', zh: '交卷' },
  'exam.submitEnd': { vi: 'Nộp bài kết thúc', en: 'Submit and finish', zh: '交卷结束' },
  'exam.submitting': { vi: 'Đang nộp', en: 'Submitting', zh: '正在交卷' },
  'exam.completed': { vi: 'Hoàn thành', en: 'Completed', zh: '已完成' },
  'exam.previous': { vi: 'Câu trước đó', en: 'Previous', zh: '上一题' },
  'exam.next': { vi: 'Câu tiếp theo', en: 'Next', zh: '下一题' },
  'exam.progress': { vi: 'Tiến độ', en: 'Progress', zh: '进度' },
  'exam.questionMap': { vi: 'Biểu đồ câu hỏi', en: 'Question map', zh: '题目导航' },
  'exam.selected': { vi: 'Đã chọn', en: 'Selected', zh: '已选' },
  'exam.current': { vi: 'Hiện tại', en: 'Current', zh: '当前' },
  'exam.unanswered': { vi: 'Chưa làm', en: 'Unanswered', zh: '未答' },
  'exam.print': { vi: 'Tải / In đề thi', en: 'Download / Print exam', zh: '下载/打印试卷' },
  'exam.allUsed': { vi: 'Tất cả các lựa chọn đã được sử dụng.', en: 'All options have been used.', zh: '所有选项已使用。' },
  'exam.essayPlaceholder': { vi: 'Nhập câu trả lời tự luận vào đây...', en: 'Enter your essay answer here...', zh: '在此输入主观题答案...' },
  'exam.translationPlaceholder': { vi: 'Nhập câu dịch tiếng Trung vào đây...', en: 'Enter your Chinese translation here...', zh: '在此输入中文翻译...' },
  'exam.autoSave': { vi: 'Câu trả lời được lưu tự động khi bạn gõ', en: 'Your answer is saved automatically as you type', zh: '输入时答案会自动保存' },
  'exam.confirmTitle': { vi: 'Nộp bài thi?', en: 'Submit exam?', zh: '确认交卷？' },
  'exam.confirmDesc': { vi: 'Sau khi nộp bạn không thể sửa đáp án.', en: 'After submitting, you cannot change your answers.', zh: '交卷后无法修改答案。' },
  'exam.reviewAgain': { vi: 'Kiểm tra lại', en: 'Review again', zh: '再检查' },
  'exam.submitNow': { vi: 'Nộp ngay', en: 'Submit now', zh: '立即交卷' },
  'exam.remaining': { vi: 'Còn lại', en: 'Remaining', zh: '剩余' },

  'auth.loginTitle': { vi: 'Chào mừng trở lại!', en: 'Welcome back!', zh: '欢迎回来！' },
  'auth.loginSubtitle': { vi: 'Đăng nhập để tiếp tục học tập', en: 'Log in to keep studying', zh: '登录后继续学习' },
  'auth.registerTitle': { vi: 'Tạo tài khoản mới', en: 'Create a new account', zh: '创建新账号' },
  'auth.registerSubtitle': { vi: 'Bắt đầu hành trình học tập của bạn', en: 'Start your learning journey', zh: '开启你的学习之旅' },
  'auth.emailLogin': { vi: 'Hoặc đăng nhập bằng email', en: 'Or log in with email', zh: '或使用邮箱登录' },
  'auth.emailRegister': { vi: 'Hoặc đăng ký bằng email', en: 'Or sign up with email', zh: '或使用邮箱注册' },
  'auth.facebookLogin': { vi: 'Đăng nhập với Facebook', en: 'Log in with Facebook', zh: '使用 Facebook 登录' },
  'auth.facebookRegister': { vi: 'Đăng ký với Facebook', en: 'Sign up with Facebook', zh: '使用 Facebook 注册' },
  'auth.email': { vi: 'Email', en: 'Email', zh: '邮箱' },
  'auth.password': { vi: 'Mật khẩu', en: 'Password', zh: '密码' },
  'auth.confirmPassword': { vi: 'Xác nhận mật khẩu', en: 'Confirm password', zh: '确认密码' },
  'auth.username': { vi: 'Tên đăng nhập', en: 'Username', zh: '用户名' },
  'auth.fullName': { vi: 'Họ và tên', en: 'Full name', zh: '姓名' },
  'auth.optional': { vi: 'Tùy chọn', en: 'Optional', zh: '可选' },
  'auth.fullNamePlaceholder': { vi: 'Nguyễn Văn A', en: 'Your full name', zh: '张三' },
  'auth.remember': { vi: 'Ghi nhớ đăng nhập', en: 'Remember me', zh: '记住登录状态' },
  'auth.forgot': { vi: 'Quên mật khẩu?', en: 'Forgot password?', zh: '忘记密码？' },
  'auth.login': { vi: 'Đăng nhập', en: 'Log in', zh: '登录' },
  'auth.loggingIn': { vi: 'Đang đăng nhập...', en: 'Logging in...', zh: '正在登录...' },
  'auth.createAccount': { vi: 'Tạo tài khoản', en: 'Create account', zh: '创建账号' },
  'auth.registering': { vi: 'Đang đăng ký...', en: 'Signing up...', zh: '正在注册...' },
  'auth.noAccount': { vi: 'Chưa có tài khoản?', en: 'Do not have an account?', zh: '还没有账号？' },
  'auth.haveAccount': { vi: 'Đã có tài khoản?', en: 'Already have an account?', zh: '已有账号？' },
  'auth.registerNow': { vi: 'Đăng ký ngay', en: 'Sign up now', zh: '立即注册' },
  'auth.loginNow': { vi: 'Đăng nhập ngay', en: 'Log in now', zh: '立即登录' },
  'auth.loginConsentPrefix': { vi: 'Bằng việc đăng nhập, bạn đồng ý với', en: 'By logging in, you agree to our', zh: '登录即表示你同意我们的' },
  'auth.registerConsentPrefix': { vi: 'Khi đăng ký, bạn đồng ý với', en: 'By signing up, you agree to our', zh: '注册即表示你同意我们的' },
  'auth.and': { vi: 'và', en: 'and', zh: '和' },
  'auth.consentSuffix': { vi: ' của chúng tôi.', en: '.', zh: '。' },
  'auth.terms': { vi: 'Điều khoản sử dụng', en: 'Terms of Use', zh: '使用条款' },
  'auth.privacy': { vi: 'Chính sách bảo mật', en: 'Privacy Policy', zh: '隐私政策' },
  'auth.otpTitle': { vi: 'Nhập mã xác thực', en: 'Enter verification code', zh: '输入验证码' },
  'auth.otpSent': { vi: 'Mã OTP đã được gửi đến email của bạn.', en: 'The OTP code was sent to your email.', zh: '验证码已发送到你的邮箱。' },
  'auth.noOtp': { vi: 'Không nhận được mã?', en: 'Did not receive the code?', zh: '没有收到验证码？' },
  'auth.resendCode': { vi: 'Gửi lại mã', en: 'Resend code', zh: '重新发送验证码' },
  'auth.resending': { vi: 'Đang gửi...', en: 'Sending...', zh: '正在发送...' },
  'auth.resendIn': { vi: 'Gửi lại sau {seconds}s', en: 'Resend in {seconds}s', zh: '{seconds}秒后重发' },
  'auth.backToLogin': { vi: 'Quay lại đăng nhập', en: 'Back to log in', zh: '返回登录' },
  'auth.waitBeforeRetry': { vi: 'Vui lòng chờ {minutes} phút trước khi thử lại.', en: 'Please wait {minutes} minutes before trying again.', zh: '请等待{minutes}分钟后再试。' },
  'auth.tooManyAttempts': { vi: 'Quá nhiều lần thử. Vui lòng chờ {minutes} phút.', en: 'Too many attempts. Please wait {minutes} minutes.', zh: '尝试次数过多。请等待{minutes}分钟。' },
  'auth.failedWithRemaining': { vi: '{message} (Còn {remaining} lần thử)', en: '{message} ({remaining} attempts left)', zh: '{message}（还可尝试{remaining}次）' },
  'auth.requiredEmail': { vi: 'Email là bắt buộc', en: 'Email is required', zh: '请输入邮箱' },
  'auth.invalidEmail': { vi: 'Email không hợp lệ', en: 'Invalid email', zh: '邮箱格式不正确' },
  'auth.requiredPassword': { vi: 'Mật khẩu là bắt buộc', en: 'Password is required', zh: '请输入密码' },
  'auth.passwordMin6': { vi: 'Mật khẩu phải có ít nhất 6 ký tự', en: 'Password must be at least 6 characters', zh: '密码至少需要6个字符' },
  'auth.passwordMin8': { vi: 'Mật khẩu phải có ít nhất 8 ký tự', en: 'Password must be at least 8 characters', zh: '密码至少需要8个字符' },
  'auth.requiredUsername': { vi: 'Tên đăng nhập là bắt buộc', en: 'Username is required', zh: '请输入用户名' },
  'auth.usernameMin3': { vi: 'Tên đăng nhập phải có ít nhất 3 ký tự', en: 'Username must be at least 3 characters', zh: '用户名至少需要3个字符' },
  'auth.usernameInvalid': { vi: 'Tên đăng nhập chỉ chứa chữ cái, số và dấu gạch dưới', en: 'Username can only contain letters, numbers and underscores', zh: '用户名只能包含字母、数字和下划线' },
  'auth.confirmRequired': { vi: 'Vui lòng xác nhận mật khẩu', en: 'Please confirm your password', zh: '请确认密码' },
  'auth.passwordMismatch': { vi: 'Mật khẩu không khớp', en: 'Passwords do not match', zh: '两次输入的密码不一致' },
  'auth.loginFailed': { vi: 'Đăng nhập thất bại. Vui lòng thử lại.', en: 'Login failed. Please try again.', zh: '登录失败，请重试。' },
  'auth.googleLoginFailed': { vi: 'Đăng nhập Google thất bại. Vui lòng thử lại.', en: 'Google login failed. Please try again.', zh: 'Google 登录失败，请重试。' },
  'auth.facebookLoginNotConfigured': { vi: 'Đăng nhập Facebook chưa được cấu hình.', en: 'Facebook login is not configured.', zh: 'Facebook 登录尚未配置。' },
  'auth.otpInvalid': { vi: 'Mã OTP không đúng. Vui lòng thử lại.', en: 'Incorrect OTP code. Please try again.', zh: '验证码不正确，请重试。' },
  'auth.otpResendFailed': { vi: 'Không thể gửi lại mã. Vui lòng thử lại.', en: 'Could not resend the code. Please try again.', zh: '无法重新发送验证码，请重试。' },
  'auth.registerFailed': { vi: 'Đăng ký thất bại. Vui lòng thử lại.', en: 'Sign up failed. Please try again.', zh: '注册失败，请重试。' },
  'auth.googleRegisterFailed': { vi: 'Đăng ký Google thất bại. Vui lòng thử lại.', en: 'Google sign up failed. Please try again.', zh: 'Google 注册失败，请重试。' },
  'auth.facebookRegisterNotConfigured': { vi: 'Đăng ký Facebook chưa được cấu hình.', en: 'Facebook sign up is not configured.', zh: 'Facebook 注册尚未配置。' },
  'auth.passwordStrength.veryWeak': { vi: 'Rất yếu', en: 'Very weak', zh: '很弱' },
  'auth.passwordStrength.weak': { vi: 'Yếu', en: 'Weak', zh: '弱' },
  'auth.passwordStrength.fair': { vi: 'Trung bình', en: 'Fair', zh: '一般' },
  'auth.passwordStrength.strong': { vi: 'Mạnh', en: 'Strong', zh: '强' },
  'auth.passwordStrength.veryStrong': { vi: 'Rất mạnh', en: 'Very strong', zh: '很强' },
  'auth.passwordFeedback.enter': { vi: 'Nhập mật khẩu', en: 'Enter a password', zh: '请输入密码' },
  'auth.passwordFeedback.min8': { vi: 'Ít nhất 8 ký tự', en: 'At least 8 characters', zh: '至少8个字符' },
  'auth.passwordFeedback.case': { vi: 'Bao gồm chữ hoa và chữ thường', en: 'Include uppercase and lowercase letters', zh: '包含大小写字母' },
  'auth.passwordFeedback.number': { vi: 'Bao gồm số', en: 'Include a number', zh: '包含数字' },
  'auth.passwordFeedback.special': { vi: 'Bao gồm ký tự đặc biệt', en: 'Include a special character', zh: '包含特殊字符' },

  'vocab.reviewTitle': { vi: 'Lịch ôn thông minh', en: 'Smart review schedule', zh: '智能复习计划' },
  'vocab.reviewDesc': { vi: 'SM-2 tự động đẩy từ khó về gần hơn', en: 'SM-2 brings difficult words back sooner', zh: 'SM-2 会让难词更快回到复习队列' },
  'vocab.refreshStats': { vi: 'Tải lại thống kê', en: 'Refresh stats', zh: '刷新统计' },
  'vocab.dueToday': { vi: 'Cần ôn hôm nay', en: 'Due today', zh: '今日待复习' },
  'vocab.weakWords': { vi: 'Từ yếu', en: 'Weak words', zh: '薄弱词' },
  'vocab.mastered': { vi: 'Đã nhớ', en: 'Mastered', zh: '已掌握' },
  'vocab.started': { vi: 'Đã học', en: 'Started', zh: '已开始' },
  'vocab.topic': { vi: 'Chủ đề', en: 'Topic', zh: '主题' },
  'vocab.due': { vi: 'Cần ôn', en: 'Due', zh: '待复习' },
  'vocab.weak': { vi: 'Yếu', en: 'Weak', zh: '薄弱' },
  'vocab.flashcardTitle': { vi: 'Flashcard', en: 'Flashcards', zh: '闪卡' },
  'vocab.flashcardDesc': { vi: 'Lật thẻ Hán tự, pinyin, nghĩa', en: 'Flip Chinese characters, pinyin and meaning', zh: '翻看汉字、拼音和释义' },
  'vocab.autoSpeak': { vi: 'Tự phát âm', en: 'Auto speak', zh: '自动朗读' },
  'vocab.start': { vi: 'Bắt đầu', en: 'Start', zh: '开始' },
  'vocab.speak': { vi: 'Phát âm', en: 'Speak', zh: '朗读' },
  'vocab.flipHint': { vi: 'Nhấn để lật thẻ', en: 'Tap to flip', zh: '点击翻卡' },
  'vocab.newWord': { vi: 'Từ mới', en: 'New word', zh: '新词' },
  'vocab.dueReview': { vi: 'Đến lịch ôn', en: 'Due for review', zh: '到期复习' },
  'vocab.wrong': { vi: 'Sai', en: 'Wrong', zh: '错误' },
  'vocab.hard': { vi: 'Khó nhớ', en: 'Hard', zh: '较难' },
  'vocab.remembered': { vi: 'Đã nhớ', en: 'Remembered', zh: '已记住' },
  'vocab.noSession': { vi: 'Chưa có phiên flashcard', en: 'No flashcard session yet', zh: '暂无闪卡练习' },
  'vocab.startHint': { vi: 'Bấm Bắt đầu để lấy từ mới và từ đến lịch ôn.', en: 'Press Start to load new words and due reviews.', zh: '点击开始加载新词和到期复习。' },
  'vocab.previousCard': { vi: 'Thẻ trước', en: 'Previous card', zh: '上一张卡' },
  'vocab.nextCard': { vi: 'Thẻ tiếp theo', en: 'Next card', zh: '下一张卡' },
  'vocab.loginRequiredFlashcard': { vi: 'Đăng nhập để dùng flashcard.', en: 'Log in to use flashcards.', zh: '请登录后使用闪卡。' },
  'vocab.loadFlashcardError': { vi: 'Không tải được flashcard.', en: 'Could not load flashcards.', zh: '无法加载闪卡。' },
  'vocab.saveReviewError': { vi: 'Không lưu được kết quả ôn tập.', en: 'Could not save review result.', zh: '无法保存复习结果。' },
  'vocab.miniTestTitle': { vi: 'Mini test từ vựng', en: 'Vocabulary mini test', zh: '词汇小测' },
  'vocab.miniTestDesc': { vi: 'Chọn nghĩa đúng, kết quả sẽ cập nhật lịch ôn', en: 'Choose the correct meaning; results update the review schedule', zh: '选择正确释义，结果会更新复习计划' },
  'vocab.createTest': { vi: 'Tạo đề', en: 'Create test', zh: '生成测试' },
  'vocab.correctCount': { vi: '{score}/{total} câu đúng', en: '{score}/{total} correct', zh: '答对 {score}/{total} 题' },
  'vocab.answerLabel': { vi: 'đáp án:', en: 'answer:', zh: '答案：' },
  'vocab.submitTest': { vi: 'Nộp bài', en: 'Submit', zh: '提交' },
  'vocab.emptyTest': { vi: 'Bấm Tạo đề để làm bài test nhanh.', en: 'Press Create test to start a quick test.', zh: '点击生成测试开始快速练习。' },
  'vocab.loginRequiredTest': { vi: 'Đăng nhập để làm mini test.', en: 'Log in to take the mini test.', zh: '请登录后参加小测。' },
  'vocab.loadTestError': { vi: 'Không tải được mini test.', en: 'Could not load the mini test.', zh: '无法加载小测。' },
  'vocab.submitTestError': { vi: 'Không nộp được mini test.', en: 'Could not submit the mini test.', zh: '无法提交小测。' },

  'course.section.materials': { vi: 'Kho tài liệu', en: 'Materials', zh: '资料库' },
  'course.section.mockExam': { vi: 'Đề mô phỏng', en: 'Mock exams', zh: '模拟试卷' },
  'course.section.history': { vi: 'Lịch sử thi', en: 'Exam history', zh: '考试记录' },
  'course.section.structure': { vi: 'Cấu trúc đề', en: 'Exam structure', zh: '试卷结构' },
  'course.section.theory': { vi: 'Lý thuyết', en: 'Theory', zh: '理论资料' },
  'course.section.vocabulary': { vi: 'Từ vựng', en: 'Vocabulary', zh: '词汇' },
  'course.section.solutions': { vi: 'Giải đề chi tiết', en: 'Detailed solutions', zh: '详细解析' },
  'course.section.ai': { vi: 'AI phân tích', en: 'AI analysis', zh: 'AI 分析' },
  'course.section.progress': { vi: 'Theo dõi tiến bộ', en: 'Progress tracking', zh: '进度跟踪' },
  'course.section.settings': { vi: 'Cài đặt', en: 'Settings', zh: '设置' },
  'course.defaultSubtitle': { vi: 'Luyện tập theo đề, xem lịch sử điểm và để AI phân tích lộ trình cải thiện sau mỗi lần làm bài.', en: 'Practice by exam, review your score history and let AI analyze how to improve after each attempt.', zh: '按试卷练习，查看成绩记录，并让 AI 在每次答题后分析提升路径。' },
  'course.searchPlaceholder': { vi: 'Tìm nhanh đề thi... (nhấn / để focus)', en: 'Quick search exams... (press / to focus)', zh: '快速搜索试卷...（按 / 聚焦）' },
  'course.title.mockExam': { vi: 'Đề Mô Phỏng {subject}', en: '{subject} Mock Exams', zh: '{subject}模拟试卷' },
  'course.title.history': { vi: 'Lịch Sử Làm Bài', en: 'Exam History', zh: '做题记录' },
  'course.title.structure': { vi: 'Cấu Trúc Đề', en: 'Exam Structure', zh: '试卷结构' },
  'course.title.theory': { vi: 'Lý Thuyết', en: 'Theory', zh: '理论资料' },
  'course.title.vocabulary': { vi: 'Từ Vựng {subject}', en: '{subject} Vocabulary', zh: '{subject}词汇' },
  'course.title.solutions': { vi: 'Giải Đề Chi Tiết', en: 'Detailed Solutions', zh: '详细解析' },
  'course.title.roadmap': { vi: 'Lộ Trình Học Cá Nhân', en: 'Personal Study Roadmap', zh: '个人学习路径' },
  'course.aiCompanionTitle': { vi: 'AI đồng hành cùng bạn', en: 'AI studies with you', zh: 'AI 陪你学习' },
  'course.aiCompanionDesc': { vi: 'Phân tích điểm mạnh, điểm yếu và gợi ý cách cải thiện.', en: 'Analyze strengths, weaknesses and improvement suggestions.', zh: '分析优势、薄弱点并给出提升建议。' },
  'course.exploreNow': { vi: 'Khám phá ngay', en: 'Explore now', zh: '立即探索' },
  'course.feature.practiceTitle': { vi: 'Luyện tập thông minh', en: 'Smart practice', zh: '智能练习' },
  'course.feature.practiceText': { vi: 'Hệ thống đề mô phỏng sát với đề thi thật.', en: 'Mock exams closely follow the real exam.', zh: '模拟试卷贴近真实考试。' },
  'course.feature.progressTitle': { vi: 'Theo dõi tiến bộ', en: 'Track progress', zh: '跟踪进步' },
  'course.feature.progressText': { vi: 'Xem lịch sử làm bài và phân tích điểm mạnh, điểm yếu.', en: 'View attempt history and analyze strengths and weaknesses.', zh: '查看做题记录并分析强弱项。' },
  'course.feature.aiTitle': { vi: 'AI gợi ý lộ trình', en: 'AI roadmap suggestions', zh: 'AI 推荐学习路径' },
  'course.feature.aiText': { vi: 'Nhận gợi ý cá nhân hóa để cải thiện hiệu quả hơn.', en: 'Get personalized suggestions to improve more effectively.', zh: '获得个性化建议，更有效提升。' },
  'course.feature.realExamTitle': { vi: 'Thi thử như thật', en: 'Realistic mock testing', zh: '真实模拟考试' },
  'course.feature.realExamText': { vi: 'Giao diện và thời gian thi bám sát kỳ thi chính thức.', en: 'Interface and timing match the official exam closely.', zh: '界面和计时贴近正式考试。' },
  'course.examListTitle': { vi: 'Danh sách đề thi', en: 'Exam list', zh: '试卷列表' },
  'course.examListDesc': { vi: 'Chọn đề và làm lại nhiều lần để theo dõi tiến bộ.', en: 'Choose exams and retake them to track progress.', zh: '选择试卷并反复练习以跟踪进步。' },

  'examList.regularTitle': { vi: 'Đề thường', en: 'Regular exams', zh: '普通试卷' },
  'examList.regularDesc': { vi: 'Tất cả tài khoản đều có thể làm', en: 'Available for all accounts', zh: '所有账号均可练习' },
  'examList.vipTitle': { vi: 'Đề VIP', en: 'VIP exams', zh: 'VIP 试卷' },
  'examList.vipDesc': { vi: 'Tài khoản VIP và Pre dùng chung bộ đề này', en: 'VIP and Pre accounts share this exam set', zh: 'VIP 和 Pre 账号共用此试卷集' },
  'examList.noExamsTitle': { vi: 'Chưa có đề để luyện', en: 'No exams to practice yet', zh: '暂无可练习试卷' },
  'examList.noExamsText': { vi: 'Bộ đề cho môn này đang được cập nhật.', en: 'This subject exam set is being updated.', zh: '该科目试卷正在更新。' },
  'examList.viewLater': { vi: 'Xem sau', en: 'View later', zh: '稍后查看' },
  'examList.continueTitle': { vi: 'Tiếp tục bài đang làm', en: 'Continue current attempt', zh: '继续当前试卷' },
  'examList.continueAction': { vi: 'Tiếp tục', en: 'Continue', zh: '继续' },
  'examList.recommendTitle': { vi: 'Gợi ý hôm nay', en: 'Today suggestion', zh: '今日建议' },
  'examList.recommendText': { vi: 'Làm {title} để tăng tiến độ bộ đề.', en: 'Take {title} to improve exam-set progress.', zh: '练习 {title} 来提升进度。' },
  'examList.practiceNow': { vi: 'Luyện ngay', en: 'Practice now', zh: '立即练习' },
  'examList.retryWeakTitle': { vi: 'Ôn lại điểm yếu', en: 'Review weak areas', zh: '复习薄弱点' },
  'examList.retryWeakText': { vi: 'Làm lại {title} để cải thiện điểm thấp nhất.', en: 'Retake {title} to improve your lowest score.', zh: '重做 {title} 来提高最低分。' },
  'examList.retry': { vi: 'Làm lại', en: 'Retake', zh: '重做' },
  'examList.unlockTitle': { vi: 'Mở khóa đề nâng cao', en: 'Unlock advanced exams', zh: '解锁进阶试卷' },
  'examList.unlockText': { vi: 'Bạn đã hết đề miễn phí phù hợp. Mở khóa VIP để luyện tiếp.', en: 'You have no suitable free exams left. Unlock VIP to keep practicing.', zh: '你已没有合适的免费试卷。解锁 VIP 继续练习。' },
  'examList.viewVip': { vi: 'Xem gói VIP', en: 'View VIP plans', zh: '查看 VIP 套餐' },
  'examList.completedTitle': { vi: 'Đã hoàn thành', en: 'Completed', zh: '已完成' },
  'examList.completedText': { vi: 'Bạn đã hoàn thành các đề hiện có trong môn này.', en: 'You have completed all current exams in this subject.', zh: '你已完成该科目当前所有试卷。' },
  'examList.done': { vi: 'Đã làm', en: 'Done', zh: '已做' },
  'examList.notDone': { vi: 'Chưa làm', en: 'Not done', zh: '未做' },
  'examList.sort': { vi: 'Sắp xếp:', en: 'Sort:', zh: '排序：' },
  'examList.newest': { vi: 'Mới nhất', en: 'Newest', zh: '最新' },
  'examList.oldest': { vi: 'Cũ nhất', en: 'Oldest', zh: '最旧' },
  'examList.byName': { vi: 'Theo tên', en: 'By name', zh: '按名称' },
  'examList.hideDone': { vi: 'Ẩn đã làm', en: 'Hide done', zh: '隐藏已做' },
  'examList.hidingDone': { vi: 'Đang ẩn đã làm', en: 'Hiding done', zh: '正在隐藏已做' },
  'examList.foundCount': { vi: 'Tìm thấy {count} đề thi', en: 'Found {count} exams', zh: '找到 {count} 套试卷' },
  'examList.searchFor': { vi: 'cho \"{search}\"', en: 'for \"{search}\"', zh: '关于“{search}”' },
  'examList.regularCount': { vi: '{count} đề thường', en: '{count} regular', zh: '{count} 套普通' },
  'examList.vipCount': { vi: '{count} đề VIP', en: '{count} VIP', zh: '{count} 套 VIP' },
  'examList.viewing': { vi: 'Đang xem {type}', en: 'Viewing {type}', zh: '正在查看{type}' },
  'examList.doneHidden': { vi: '(đã ẩn đề đã làm)', en: '(done exams hidden)', zh: '（已隐藏已做试卷）' },
  'examList.progressOverview': { vi: 'Tổng quan luyện tập', en: 'Practice overview', zh: '练习概览' },
  'examList.setProgress': { vi: 'Tiến độ bộ đề', en: 'Set progress', zh: '试卷进度' },
  'examList.questionsPracticed': { vi: 'Câu đã luyện', en: 'Questions practiced', zh: '已练题目' },
  'examList.passRate': { vi: 'Tỉ lệ đạt', en: 'Pass rate', zh: '通过率' },
  'examList.searchPlaceholder': { vi: 'Tìm nhanh đề thi... (nhấn / để focus)', en: 'Quick search exams... (press / to focus)', zh: '快速搜索试卷...（按 / 聚焦）' },
  'examList.noGroup': { vi: 'Chưa có đề phù hợp trong nhóm này.', en: 'No matching exams in this group.', zh: '该分组暂无匹配试卷。' },
  'examList.noSearch': { vi: 'Không tìm thấy đề \"{search}\"', en: 'No exams found for \"{search}\"', zh: '未找到“{search}”相关试卷' },
  'examList.noMatch': { vi: 'Không có đề thi phù hợp', en: 'No matching exams', zh: '暂无匹配试卷' },
  'examList.tryAnother': { vi: 'Thử từ khóa khác', en: 'Try another keyword', zh: '试试其他关键词' },
  'examList.updating': { vi: 'Đội ngũ đang cập nhật thêm đề thi', en: 'More exams are being added.', zh: '正在更新更多试卷。' },
  'examList.clearSearch': { vi: 'Xóa tìm kiếm', en: 'Clear search', zh: '清除搜索' },
  'examList.subjectCode': { vi: 'Mã môn: {code}', en: 'Subject code: {code}', zh: '科目代码：{code}' },
  'examList.minutes': { vi: '{count} phút', en: '{count} minutes', zh: '{count} 分钟' },
  'examList.questions': { vi: '{count} câu', en: '{count} questions', zh: '{count} 题' },
  'examList.examCount': { vi: '{count} đề', en: '{count} exams', zh: '{count} 套' },
  'examList.attempts': { vi: '{count} lần', en: '{count} attempts', zh: '{count} 次' },
  'examList.scorePoint': { vi: '{score} đ', en: '{score} pts', zh: '{score} 分' },
  'examList.passed': { vi: '{rate}% đỗ', en: '{rate}% passed', zh: '{rate}% 通过' },
  'examList.shuffle': { vi: 'Xáo trộn', en: 'Shuffled', zh: '乱序' },
  'examList.locked': { vi: 'Khóa', en: 'Locked', zh: '已锁' },
  'examList.startExam': { vi: 'Làm bài', en: 'Start', zh: '开始' },
  'examList.vipOnlyTitle': { vi: 'Đề \"{title}\" chỉ dành cho VIP/Pre', en: '\"{title}\" is for VIP/Pre only', zh: '“{title}”仅限 VIP/Pre' },
  'examList.easy': { vi: 'Dễ', en: 'Easy', zh: '简单' },
  'examList.medium': { vi: 'TB', en: 'Medium', zh: '中等' },
  'examList.hard': { vi: 'Khó', en: 'Hard', zh: '困难' },

  'history.loginTitle': { vi: 'Đăng nhập để xem lịch sử', en: 'Log in to view history', zh: '登录后查看记录' },
  'history.loginDesc': { vi: 'Theo dõi tiến trình học tập và kết quả tất cả các bài thi đã làm.', en: 'Track learning progress and results from all completed exams.', zh: '跟踪学习进度和所有已完成试卷的结果。' },
  'history.loginNow': { vi: 'Đăng nhập ngay', en: 'Log in now', zh: '立即登录' },
  'history.title': { vi: 'Lịch Sử Làm Bài', en: 'Exam History', zh: '做题记录' },
  'history.subtitle': { vi: 'Tất cả {total} lần thi · {passed} lần đạt', en: '{total} attempts · {passed} passed', zh: '共 {total} 次考试 · {passed} 次通过' },
  'history.searchPlaceholder': { vi: 'Tìm trong lịch sử làm bài...', en: 'Search attempt history...', zh: '搜索做题记录...' },
  'history.detailStats': { vi: 'Thống kê chi tiết', en: 'Detailed stats', zh: '详细统计' },
  'history.totalAttempts': { vi: 'Tổng bài', en: 'Total attempts', zh: '总次数' },
  'history.avgScore': { vi: 'Điểm TB', en: 'Avg score', zh: '平均分' },
  'history.bestScore': { vi: 'Điểm cao nhất', en: 'Best score', zh: '最高分' },
  'history.passedAttempts': { vi: 'Lần đạt (≥50%)', en: 'Passed (>=50%)', zh: '通过次数（≥50%）' },
  'history.all': { vi: 'Tất cả', en: 'All', zh: '全部' },
  'history.loading': { vi: 'Đang tải lịch sử...', en: 'Loading history...', zh: '正在加载记录...' },
  'history.emptyTitle': { vi: 'Chưa có bài thi nào', en: 'No attempts yet', zh: '暂无考试记录' },
  'history.noResults': { vi: 'Không có kết quả', en: 'No results', zh: '没有结果' },
  'history.emptyDesc': { vi: 'Hãy làm thử đề mô phỏng để xem kết quả tại đây.', en: 'Try a mock exam to see results here.', zh: '先做一套模拟试卷，结果会显示在这里。' },
  'history.filterDesc': { vi: 'Thử chọn bộ lọc khác.', en: 'Try another filter.', zh: '请尝试其他筛选。' },
  'history.startExam': { vi: 'Làm đề ngay', en: 'Start an exam', zh: '立即做题' },
  'history.exam': { vi: 'Đề thi', en: 'Exam', zh: '试卷' },
  'history.score': { vi: 'Điểm', en: 'Score', zh: '分数' },
  'history.correct': { vi: 'Đúng', en: 'Correct', zh: '正确' },
  'history.time': { vi: 'Thời gian', en: 'Time', zh: '用时' },
  'history.result': { vi: 'Kết quả', en: 'Result', zh: '结果' },
  'history.pageCount': { vi: '{from}-{to} / {total} bài', en: '{from}-{to} / {total} attempts', zh: '{from}-{to} / {total} 次' },
  'history.noTime': { vi: 'Chưa có thời gian', en: 'No time yet', zh: '暂无时间' },
  'history.justNow': { vi: 'Vừa xong', en: 'Just now', zh: '刚刚' },
  'history.minutesAgo': { vi: '{count} phút trước', en: '{count} minutes ago', zh: '{count}分钟前' },
  'history.hoursAgo': { vi: '{count}h trước', en: '{count}h ago', zh: '{count}小时前' },
  'history.daysAgo': { vi: '{count} ngày trước', en: '{count} days ago', zh: '{count}天前' },
  'history.monthsAgo': { vi: '{count} tháng trước', en: '{count} months ago', zh: '{count}个月前' },
  'history.yearsAgo': { vi: '{count} năm trước', en: '{count} years ago', zh: '{count}年前' },
  'history.excellent': { vi: 'Xuất sắc', en: 'Excellent', zh: '优秀' },
  'history.good': { vi: 'Khá', en: 'Good', zh: '良好' },
  'history.average': { vi: 'Trung bình', en: 'Average', zh: '中等' },
  'history.weak': { vi: 'Yếu', en: 'Weak', zh: '较弱' },

  'roadmap.title': { vi: 'Lộ Trình Học Cá Nhân', en: 'Personal Study Roadmap', zh: '个人学习路径' },
  'roadmap.heroBadge': { vi: 'Bản Đồ Học Tập', en: 'Study Map', zh: '学习地图' },
  'roadmap.heroTitle': { vi: 'Lộ Trình Tinh Anh', en: 'Elite Roadmap', zh: '精英学习路径' },
  'roadmap.heroDesc': { vi: 'AI đang cá nhân hoá đường đi của bạn. Liên tục bứt phá các mốc điểm trong Đề Mô Phỏng để mở khoá Chặng tiếp theo.', en: 'AI is personalizing your path. Keep breaking score milestones in mock exams to unlock the next stage.', zh: 'AI 正在个性化你的学习路线。持续突破模拟试卷分数节点，解锁下一阶段。' },
  'roadmap.searchPlaceholder': { vi: 'Tìm mốc lộ trình...', en: 'Search roadmap milestones...', zh: '搜索学习路径节点...' },
  'roadmap.loginTitle': { vi: 'Đăng nhập để xem Lộ Trình', en: 'Log in to view roadmap', zh: '登录后查看学习路径' },
  'roadmap.loginDesc': { vi: 'AI sẽ phân tích kết quả theo môn và tạo lộ trình học tập cá nhân hóa.', en: 'AI will analyze subject results and build a personalized study roadmap.', zh: 'AI 会按科目分析结果并生成个性化学习路径。' },
  'roadmap.guestTitle': { vi: 'Ai đó chưa đăng nhập nhỉ?', en: 'Looks like you are not logged in yet', zh: '你还没有登录' },
  'roadmap.guestDesc': { vi: 'Trí tuệ nhân tạo Gemini cần biết tên bạn để xếp hạng và vẽ chính xác lộ trình cá nhân hoá riêng rẽ.', en: 'Gemini AI needs your account to rank your progress and draw an accurate personalized roadmap.', zh: 'Gemini AI 需要你的账号来评估进度并生成准确的个性化路线。' },
  'roadmap.loginStart': { vi: 'Đăng nhập & Bắt đầu', en: 'Log in & start', zh: '登录并开始' },
  'roadmap.survivalTitle': { vi: 'Sống sót chặng đường', en: 'Roadmap stages', zh: '学习阶段' },
  'roadmap.continueStudy': { vi: 'Tiếp tục học', en: 'Continue studying', zh: '继续学习' },
  'roadmap.allSubjects': { vi: 'tất cả môn', en: 'all subjects', zh: '所有科目' },
  'roadmap.milestones': { vi: 'Mốc tiến bộ', en: 'Progress milestones', zh: '进步节点' },
  'roadmap.milestonesDesc': { vi: 'Các chặng học tập được mở theo kết quả luyện đề.', en: 'Study stages unlock based on exam practice results.', zh: '学习阶段会根据练习结果解锁。' },
  'roadmap.stage': { vi: 'Chặng {count}', en: 'Stage {count}', zh: '第 {count} 阶段' },
  'roadmap.focusTitle': { vi: 'Lộ trình cải thiện hằng ngày', en: 'Daily improvement roadmap', zh: '每日提升路径' },
  'roadmap.focusDesc': { vi: 'Tổng hợp riêng cho {subject}: tiến độ, việc hôm nay, chủ đề yếu và đề nên làm tiếp.', en: 'Personalized for {subject}: progress, today tasks, weak topics and next exams.', zh: '为{subject}汇总：进度、今日任务、薄弱主题和下一套试卷。' },
  'roadmap.regenerate': { vi: 'Tạo lại kế hoạch', en: 'Regenerate plan', zh: '重新生成计划' },
  'roadmap.recent7Days': { vi: '7 ngày gần đây', en: 'Last 7 days', zh: '近 7 天' },
  'roadmap.todayTasks': { vi: 'Hôm nay cần làm', en: 'Today tasks', zh: '今日任务' },
  'roadmap.suggestedExam': { vi: 'Làm đề gợi ý', en: 'Take suggested exam', zh: '做推荐试卷' },
  'roadmap.needOneExam': { vi: 'Làm ít nhất 1 đề để hệ thống tạo việc học hôm nay.', en: 'Take at least 1 exam so the system can create today tasks.', zh: '至少完成 1 套试卷后系统会生成今日任务。' },
  'roadmap.plan7Days': { vi: 'Kế hoạch 7 ngày', en: '7-day plan', zh: '7 天计划' },
  'roadmap.noPlan': { vi: 'Chưa có kế hoạch 7 ngày.', en: 'No 7-day plan yet.', zh: '暂无 7 天计划。' },
  'roadmap.weakTopics': { vi: 'Chủ đề yếu cần ưu tiên', en: 'Weak topics to prioritize', zh: '需优先复习的薄弱主题' },
  'roadmap.errorRate': { vi: '{rate}% sai', en: '{rate}% wrong', zh: '{rate}% 错误' },
  'roadmap.defaultAdvice': { vi: 'Ôn lại lý thuyết và luyện thêm câu cùng chủ đề.', en: 'Review theory and practice more questions in this topic.', zh: '复习理论并多练同主题题目。' },
  'roadmap.noWeakTopics': { vi: 'Chưa đủ dữ liệu chủ đề yếu cho môn này.', en: 'Not enough weak-topic data for this subject yet.', zh: '该科目暂无足够薄弱主题数据。' },
  'roadmap.nextExams': { vi: 'Đề nên làm tiếp', en: 'Recommended next exams', zh: '建议下一步试卷' },
  'roadmap.noRecommendations': { vi: 'Chưa có đề gợi ý riêng cho môn này.', en: 'No personalized exam suggestions for this subject yet.', zh: '该科目暂无个性化推荐试卷。' },
  'roadmap.day': { vi: 'Ngày {count}', en: 'Day {count}', zh: '第 {count} 天' },
  'roadmap.today': { vi: 'Hôm nay', en: 'Today', zh: '今天' },
  'roadmap.minutes': { vi: '{count} phút', en: '{count} minutes', zh: '{count} 分钟' },

  'materials.structureDesc': { vi: 'Phân tích cấu trúc đề thi chính thức · {count} tài liệu', en: 'Official exam-structure analysis · {count} materials', zh: '官方试卷结构分析 · {count} 份资料' },
  'materials.theoryDesc': { vi: 'Tài liệu lý thuyết chuẩn CSCA · {count} tài liệu', en: 'CSCA-aligned theory materials · {count} materials', zh: 'CSCA 标准理论资料 · {count} 份资料' },
  'materials.search': { vi: 'Tìm tài liệu...', en: 'Search materials...', zh: '搜索资料...' },
  'materials.searchDocs': { vi: 'Tìm kiếm tài liệu...', en: 'Search documents...', zh: '搜索文件...' },
  'materials.loadError': { vi: 'Tải tài liệu chưa thành công. Bạn thử lại giúp mình nhé.', en: 'Could not load materials. Please try again.', zh: '资料加载失败，请重试。' },
  'materials.reload': { vi: 'Tải lại', en: 'Reload', zh: '重新加载' },
  'materials.noMatch': { vi: 'Không tìm thấy tài liệu phù hợp', en: 'No matching materials found', zh: '未找到匹配资料' },
  'materials.noneInSection': { vi: 'Chưa có tài liệu nào cho mục này', en: 'No materials in this section yet', zh: '该栏目暂无资料' },
  'materials.none': { vi: 'Chưa có tài liệu nào', en: 'No materials yet', zh: '暂无资料' },
  'materials.download': { vi: 'Tải về', en: 'Download', zh: '下载' },
  'materials.openFile': { vi: 'Mở file', en: 'Open file', zh: '打开文件' },
  'materials.openNewTab': { vi: 'Mở tab mới', en: 'Open new tab', zh: '新标签打开' },
  'materials.commonTopic': { vi: 'Tài liệu chung', en: 'General materials', zh: '通用资料' },
  'materials.loadingPdf': { vi: 'Đang tải PDF...', en: 'Loading PDF...', zh: '正在加载 PDF...' },
  'materials.loadingDoc': { vi: 'Đang tải tài liệu...', en: 'Loading document...', zh: '正在加载资料...' },

  'solutions.desc': { vi: 'Xem video hướng dẫn giải chi tiết từng đề thi. Hướng dẫn từng bước, phương pháp giải nhanh.', en: 'Watch detailed solution videos for each exam with step-by-step guidance and faster methods.', zh: '观看每套试卷的详细视频解析，包含分步讲解和快速方法。' },
  'solutions.askAdvisor': { vi: 'Nhắn tin Hỏi Đáp 1-1 với Cố Vấn', en: 'Message an advisor 1-on-1', zh: '一对一咨询导师' },
  'solutions.askAdvisorHint': { vi: 'Bạn chưa hiểu đoạn nào? Hãy hỏi cố vấn ngay nhé.', en: 'Need help with any part? Ask an advisor now.', zh: '哪里还没理解？现在就问导师。' },
  'solutions.askVipAdvisor': { vi: 'Hỏi Cố Vấn VIP', en: 'Ask VIP advisor', zh: '咨询 VIP 导师' },
  'solutions.needPreTitle': { vi: 'Cần tài khoản Pre', en: 'Pre account required', zh: '需要 Pre 账号' },
  'solutions.preVideoTitle': { vi: 'Video giải đề chỉ dành cho Pre', en: 'Solution video is Pre-only', zh: '解析视频仅限 Pre' },
  'solutions.preVideoExclusive': { vi: 'Video giải đề Pre độc quyền - chỉ dành cho tài khoản Pre.', en: 'Exclusive Pre solution videos are available only to Pre accounts.', zh: 'Pre 专属解析视频仅限 Pre 账号观看。' },
  'solutions.videoPreOnly': { vi: 'Video giải đề này dành cho thành viên Pre. VIP chỉ có AI phân tích.', en: 'This solution video is for Pre members. VIP includes AI analysis only.', zh: '此解析视频面向 Pre 会员，VIP 仅含 AI 分析。' },
  'solutions.featureAllVideos': { vi: 'Xem toàn bộ video giải đề Pre', en: 'Watch all Pre solution videos', zh: '观看全部 Pre 解析视频' },
  'solutions.featureAdvisor': { vi: 'Chat 1-1 với cố vấn chuyên gia', en: 'Chat 1-on-1 with an expert advisor', zh: '与专家导师一对一聊天' },
  'solutions.featureAiAnalysis': { vi: 'Phân tích AI chi tiết từng câu', en: 'Detailed AI analysis for each question', zh: '每题详细 AI 分析' },
  'solutions.featureUnlimited': { vi: 'Truy cập đề thi cao cấp không giới hạn', en: 'Unlimited access to premium exams', zh: '无限访问高级试卷' },
  'solutions.featureUpgradeForVideo': { vi: 'Nâng cấp Pre để xem video giải đề', en: 'Upgrade to Pre to watch solution videos', zh: '升级到 Pre 观看解析视频' },
  'solutions.upgradePreNow': { vi: '👑 Nâng cấp Pre ngay', en: '👑 Upgrade to Pre now', zh: '👑 立即升级 Pre' },
  'solutions.lockedVideos': { vi: 'Có {count} video giải đề cần nâng cấp để xem', en: '{count} solution videos require an upgrade', zh: '有 {count} 个解析视频需升级后观看' },
  'solutions.upgradePre': { vi: 'Nâng cấp gói Pre để mở khóa video hướng dẫn giải đề', en: 'Upgrade to Pre to unlock solution videos', zh: '升级到 Pre 解锁解析视频' },
  'solutions.upgrade': { vi: 'Nâng cấp', en: 'Upgrade', zh: '升级' },
  'solutions.upgradeVip': { vi: 'Nâng cấp VIP', en: 'Upgrade VIP', zh: '升级 VIP' },
  'solutions.searchExam': { vi: 'Tìm kiếm đề...', en: 'Search exams...', zh: '搜索试卷...' },
  'solutions.totalCount': { vi: 'Tổng cộng: {count} đề', en: 'Total: {count} exams', zh: '共 {count} 套试卷' },
  'solutions.videoCount': { vi: 'Có video: {count} đề', en: 'With video: {count}', zh: '有视频：{count} 套' },
  'solutions.lockedCount': { vi: 'Đã khóa: {count} video', en: 'Locked: {count} videos', zh: '已锁定：{count} 个视频' },
  'solutions.noMatch': { vi: 'Không tìm thấy đề thi phù hợp', en: 'No matching exams found', zh: '未找到匹配试卷' },
  'solutions.noExams': { vi: 'Chưa có đề thi nào', en: 'No exams yet', zh: '暂无试卷' },
  'solutions.watchVideo': { vi: 'Xem Video', en: 'Watch video', zh: '观看视频' },
  'solutions.noVideo': { vi: 'Chưa có video', en: 'No video yet', zh: '暂无视频' },
  'solutions.videoBadge': { vi: '{count} video', en: '{count} videos', zh: '{count} 个视频' },

  'vocab.courseTitle': { vi: 'Từ Vựng Chuyên Ngành', en: 'Specialized Vocabulary', zh: '专业词汇' },
  'vocab.back': { vi: 'Quay lại', en: 'Back', zh: '返回' },
  'vocab.searchWords': { vi: 'Tìm từ vựng...', en: 'Search vocabulary...', zh: '搜索词汇...' },
  'vocab.exportPdf': { vi: 'Xuất PDF', en: 'Export PDF', zh: '导出 PDF' },
  'vocab.exportPdfTitle': { vi: 'Xuất danh sách từ vựng ra PDF', en: 'Export vocabulary list to PDF', zh: '将词汇列表导出为 PDF' },
  'vocab.noWordsFound': { vi: 'Không tìm thấy từ vựng', en: 'No vocabulary found', zh: '未找到词汇' },
  'vocab.tryAnotherKeyword': { vi: 'Hãy thử tìm kiếm bằng một từ khóa khác.', en: 'Try searching with another keyword.', zh: '请尝试其他关键词。' },
  'vocab.wordList': { vi: 'Danh sách từ vựng', en: 'Vocabulary list', zh: '词汇列表' },
  'vocab.wordsCount': { vi: '{count} từ', en: '{count} words', zh: '{count} 个词' },
  'vocab.vipContent': { vi: 'Nội dung VIP', en: 'VIP content', zh: 'VIP 内容' },
  'vocab.allSubjects': { vi: 'Tất cả môn', en: 'All subjects', zh: '全部科目' },
  'vocab.noWords': { vi: 'Chưa có từ vựng nào', en: 'No vocabulary yet', zh: '暂无词汇' },
  'vocab.updatingWords': { vi: 'Hệ thống đang được cập nhật thêm từ vựng cho môn học này. Bạn quay lại sau nhé!', en: 'Vocabulary for this subject is being updated. Please check back later.', zh: '该科目词汇正在更新，请稍后再来。' },
  'vocab.topicsCount': { vi: '{count} chủ đề từ vựng', en: '{count} vocabulary topics', zh: '{count} 个词汇主题' },
  'vocab.startLearning': { vi: 'Bắt đầu học', en: 'Start learning', zh: '开始学习' },

  'profile.languageTitle': { vi: 'Ngôn ngữ hiển thị', en: 'Display language', zh: '显示语言' },
  'profile.languageDesc': { vi: 'Áp dụng cho trang user, navbar, trang chủ, hồ sơ và nội dung đề thi có đủ dữ liệu.', en: 'Applies to user pages, navbar, homepage, profile and exam content when data exists.', zh: '适用于用户页面、导航栏、首页、个人资料及已有多语言数据的试题内容。' },
  'profile.info': { vi: 'Thông tin', en: 'Info', zh: '信息' },
  'profile.stats': { vi: 'Thống kê', en: 'Stats', zh: '统计' },
  'profile.wallet': { vi: 'Ví xu', en: 'Coin wallet', zh: '金币钱包' },
  'profile.vip': { vi: 'VIP', en: 'VIP', zh: 'VIP' },
  'profile.devices': { vi: 'Thiết bị', en: 'Devices', zh: '设备' },
  'profile.settings': { vi: 'Cài đặt', en: 'Settings', zh: '设置' },
  'profile.edit': { vi: 'Chỉnh sửa', en: 'Edit', zh: '编辑' },
  'profile.joined': { vi: 'Tham gia', en: 'Joined', zh: '加入于' },
  'profile.target': { vi: 'Mục tiêu', en: 'Target', zh: '目标' },
  'profile.fullName': { vi: 'Họ và tên', en: 'Full name', zh: '姓名' },
  'profile.username': { vi: 'Tên đăng nhập', en: 'Username', zh: '用户名' },
  'profile.bio': { vi: 'Giới thiệu', en: 'Bio', zh: '简介' },
  'profile.noBio': { vi: 'Chưa có giới thiệu', en: 'No bio yet', zh: '暂无简介' },
  'profile.targetScore': { vi: 'Điểm mục tiêu', en: 'Target score', zh: '目标分数' },
  'profile.notSet': { vi: 'Chưa đặt', en: 'Not set', zh: '未设置' },
  'profile.vipExpiry': { vi: 'Hạn VIP', en: 'VIP expiry', zh: 'VIP到期日' },
  'profile.examsDone': { vi: 'Đề thi đã làm', en: 'Completed exams', zh: '已完成试卷' },
  'profile.avgScore': { vi: 'Điểm trung bình', en: 'Average score', zh: '平均分' },
  'profile.highestScore': { vi: 'Điểm cao nhất', en: 'Highest score', zh: '最高分' },
  'profile.posts': { vi: 'Bài viết', en: 'Posts', zh: '帖子' },
  'profile.detailStats': { vi: 'Xem thống kê chi tiết toàn bộ', en: 'View full detailed stats', zh: '查看完整详细统计' },
};

type LanguageContextValue = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  t: (key: string) => string;
  format: (key: string, values: Record<string, string | number>) => string;
  pick: (value: Partial<Record<AppLanguage, string | null | undefined>>) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function normalizeLanguage(value: string | null | undefined): AppLanguage {
  return value === 'en' || value === 'zh' || value === 'vi' ? value : 'vi';
}

export function pickLocalizedText(
  value: Partial<Record<AppLanguage, string | null | undefined>>,
  language: AppLanguage,
): string {
  const preferred = value[language]?.trim();
  if (preferred) return preferred;
  return value.vi?.trim() || value.en?.trim() || value.zh?.trim() || '';
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>('vi');

  useEffect(() => {
    setLanguageState(normalizeLanguage(window.localStorage.getItem(STORAGE_KEY)));
  }, []);

  useEffect(() => {
    document.documentElement.lang = language === 'zh' ? 'zh-CN' : language;
    window.localStorage.setItem(STORAGE_KEY, language);
  }, [language]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage: setLanguageState,
    t: (key: string) => {
      const copy = COPY[key];
      if (!copy) return key;
      if (typeof copy === 'string') return copy;
      return pickLocalizedText(copy, language);
    },
    format: (key, values) => {
      const copy = COPY[key];
      const text = typeof copy === 'string' ? copy : copy ? pickLocalizedText(copy, language) : key;
      return Object.entries(values).reduce(
        (message, [name, value]) => message.split(`{${name}}`).join(String(value)),
        text,
      );
    },
    pick: (text) => pickLocalizedText(text, language),
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used inside LanguageProvider');
  }
  return ctx;
}
