export type ChemistryFormulaGrade = '10' | '11' | '12' | 'Chung';

export interface ChemistryFormulaLine {
  label: string;
  value: string;
  note?: string;
}

export interface ChemistryCscaFormulaTopic {
  id: string;
  title: string;
  grade: ChemistryFormulaGrade;
  area: string;
  chinese?: string;
  summary: string;
  keywords: string[];
  formulas: ChemistryFormulaLine[];
  notes?: string[];
}

const m = String.raw;

export const CHEMISTRY_CSCA_FORMULA_TOPICS: ChemistryCscaFormulaTopic[] = [
  {
    id: 'atomic-structure-isotopes',
    title: 'Nguyên tử, đồng vị, số hạt',
    grade: '10',
    area: 'Đại cương',
    chinese: '原子结构、同位素',
    summary: 'Số proton, neutron, electron, số khối, điện tích ion và nguyên tử khối trung bình.',
    keywords: ['nguyen tu', 'dong vi', 'so hat', 'proton', 'neutron', 'electron', '同位素', '原子'],
    formulas: [
      { label: 'Số hiệu nguyên tử', value: m`\(Z=p=e\)`, note: 'Với nguyên tử trung hòa điện.' },
      { label: 'Số khối', value: m`\(A=Z+N=p+n\)` },
      { label: 'Tổng hạt nguyên tử', value: m`\(S=p+n+e=2Z+N\)` },
      { label: 'Ion dương', value: m`\(\mathrm{M}^{k+}:\ e=Z-k\)` },
      { label: 'Ion âm', value: m`\(\mathrm{X}^{k-}:\ e=Z+k\)` },
      { label: 'Kí hiệu hạt nhân', value: m`\({}^{A}_{Z}\mathrm{X}\)` },
      { label: 'Nguyên tử khối trung bình', value: m`\(\overline{A}=\frac{A_1x_1+A_2x_2+\cdots+A_nx_n}{x_1+x_2+\cdots+x_n}\)` },
      { label: 'Nếu dùng phần trăm', value: m`\(\overline{A}=\frac{A_1a_1+A_2a_2+\cdots+A_na_n}{100}\)` },
    ],
    notes: ['Bài số hạt thường dùng thêm điều kiện bền: với nguyên tố nhẹ, \(1\le N/Z\le1.5\).'],
  },
  {
    id: 'electron-configuration-periodic-table',
    title: 'Cấu hình electron và bảng tuần hoàn',
    grade: '10',
    area: 'Đại cương',
    chinese: '电子排布、元素周期表',
    summary: 'Quy tắc phân bố electron, lớp ngoài cùng, nhóm, chu kì và xu hướng tuần hoàn.',
    keywords: ['cau hinh electron', 'bang tuan hoan', 'chu ki', 'nhom', '电子排布', '周期表'],
    formulas: [
      { label: 'Sức chứa lớp n', value: m`\(N_{\max}=2n^2\)` },
      { label: 'Sức chứa phân lớp', value: m`\(\mathrm{s}:2,\quad \mathrm{p}:6,\quad \mathrm{d}:10,\quad \mathrm{f}:14\)` },
      { label: 'Thứ tự mức năng lượng', value: m`\(1s<2s<2p<3s<3p<4s<3d<4p<5s<4d<5p<6s<4f<5d<6p\)` },
      { label: 'Số electron hóa trị nhóm A', value: m`\(\text{số e hóa trị}=\text{số thứ tự nhóm A}\)` },
      { label: 'Chu kì', value: m`\(\text{chu kì}=\text{số lớp electron đang có}\)` },
      { label: 'Bán kính nguyên tử', value: 'Trong một chu kì giảm dần từ trái sang phải; trong một nhóm tăng dần từ trên xuống dưới.' },
      { label: 'Độ âm điện', value: 'Trong một chu kì tăng dần từ trái sang phải; trong một nhóm giảm dần từ trên xuống dưới.' },
      { label: 'Tính kim loại', value: 'Tăng từ trên xuống dưới và từ phải sang trái.' },
    ],
  },
  {
    id: 'chemical-bonding-crystal',
    title: 'Liên kết hóa học và hình học phân tử',
    grade: '10',
    area: 'Liên kết',
    chinese: '化学键、分子结构',
    summary: 'Ion, cộng hóa trị, độ âm điện, liên kết hydrogen, công thức Lewis và dạng hình học cơ bản.',
    keywords: ['lien ket hoa hoc', 'ion', 'cong hoa tri', 'lewis', 'hydrogen', '化学键'],
    formulas: [
      { label: 'Hiệu độ âm điện', value: m`\(\Delta\chi=|\chi_A-\chi_B|\)` },
      { label: 'Phân loại gần đúng', value: m`\(\Delta\chi<0.4:\text{ không cực};\quad 0.4\le\Delta\chi<1.7:\text{ có cực};\quad \Delta\chi\ge1.7:\text{ ion}\)` },
      { label: 'Quy tắc octet', value: 'Nguyên tử có xu hướng đạt 8 electron lớp ngoài cùng, riêng H, He đạt 2 electron.' },
      { label: 'Liên kết ion', value: m`\(\mathrm{M}\to \mathrm{M}^{n+}+ne,\quad \mathrm{X}+ne\to \mathrm{X}^{n-}\)` },
      { label: 'Liên kết cho nhận', value: m`\(\mathrm{A:}+\mathrm{B}\to \mathrm{A}\to\mathrm{B}\)` },
      { label: 'Moment lưỡng cực', value: m`\(\mu=q\cdot l\)` },
      { label: 'Tứ diện', value: m`\(\mathrm{AX_4}:\ 109.5^\circ\)` },
      { label: 'Tam giác phẳng', value: m`\(\mathrm{AX_3}:\ 120^\circ\)` },
      { label: 'Thẳng', value: m`\(\mathrm{AX_2}:\ 180^\circ\)` },
    ],
  },
  {
    id: 'oxidation-number-redox',
    title: 'Số oxi hóa và phản ứng oxi hóa khử',
    grade: '10',
    area: 'Oxi hóa khử',
    chinese: '氧化还原、氧化数',
    summary: 'Quy tắc số oxi hóa, electron trao đổi, cân bằng oxi hóa khử và chất oxi hóa/khử.',
    keywords: ['oxi hoa khu', 'so oxi hoa', 'electron', 'can bang', '氧化还原'],
    formulas: [
      { label: 'Đơn chất', value: m`\(\mathrm{SOX}=0\)` },
      { label: 'Ion đơn nguyên tử', value: m`\(\mathrm{SOX}=\text{điện tích ion}\)` },
      { label: 'Tổng số oxi hóa phân tử', value: m`\(\sum \mathrm{SOX}=0\)` },
      { label: 'Tổng số oxi hóa ion', value: m`\(\sum \mathrm{SOX}=q_{\mathrm{ion}}\)` },
      { label: 'Oxi thường gặp', value: m`\(\mathrm{O}:-2\)`, note: 'Peroxide: O = -1; trong OF2: O = +2.' },
      { label: 'Hydrogen thường gặp', value: m`\(\mathrm{H}:+1\)`, note: 'Hydride kim loại: H = -1.' },
      { label: 'Oxi hóa', value: m`\(\mathrm{M}\to \mathrm{M}^{n+}+ne\)` },
      { label: 'Khử', value: m`\(\mathrm{X}+ne\to \mathrm{X}^{n-}\)` },
      { label: 'Bảo toàn electron', value: m`\(\sum n_e\text{ nhường}=\sum n_e\text{ nhận}\)` },
      { label: 'Hệ số redox', value: m`\(a\cdot \Delta \mathrm{SOX}_{\text{khử}}=b\cdot \Delta \mathrm{SOX}_{\text{oxi hóa}}\)` },
    ],
    notes: ['Chất khử bị oxi hóa, số oxi hóa tăng. Chất oxi hóa bị khử, số oxi hóa giảm.'],
  },
  {
    id: 'mole-mass-volume',
    title: 'Mol, khối lượng, thể tích khí',
    grade: 'Chung',
    area: 'Tính toán cơ bản',
    chinese: '物质的量、质量、气体体积',
    summary: 'Các công thức gốc để đổi mol, khối lượng, thể tích khí, số hạt và tỉ khối.',
    keywords: ['mol', 'khoi luong', 'the tich khi', 'ti khoi', '物质的量'],
    formulas: [
      { label: 'Số mol từ khối lượng', value: m`\(n=\frac{m}{M}\)` },
      { label: 'Khối lượng', value: m`\(m=nM\)` },
      { label: 'Số hạt', value: m`\(N=nN_A,\quad N_A=6.022\times10^{23}\)` },
      { label: 'Khí ở điều kiện chuẩn', value: m`\(n=\frac{V}{22.4}\)`, note: 'Nếu đề dùng SATP hoặc điều kiện mới, theo dữ kiện đề.' },
      { label: 'Phương trình khí lý tưởng', value: m`\(PV=nRT\)` },
      { label: 'Tỉ khối so với khí B', value: m`\(d_{A/B}=\frac{M_A}{M_B}\)` },
      { label: 'Tỉ khối so với H2', value: m`\(d_{A/\mathrm{H}_2}=\frac{M_A}{2}\)` },
      { label: 'Tỉ khối so với không khí', value: m`\(d_{A/\mathrm{kk}}=\frac{M_A}{29}\)` },
      { label: 'Khối lượng mol hỗn hợp', value: m`\(\overline{M}=\frac{m_{\text{hh}}}{n_{\text{hh}}}\)` },
      { label: 'Phần trăm thể tích khí', value: m`\(\%V_i=\frac{V_i}{V_{\text{hh}}}\times100\%=\frac{n_i}{n_{\text{hh}}}\times100\%\)` },
    ],
  },
  {
    id: 'solutions-concentrations',
    title: 'Dung dịch và nồng độ',
    grade: 'Chung',
    area: 'Dung dịch',
    chinese: '溶液、浓度',
    summary: 'Nồng độ mol, nồng độ phần trăm, pha loãng, trộn dung dịch và ion trong dung dịch.',
    keywords: ['dung dich', 'nong do mol', 'nong do phan tram', 'pha loang', '浓度'],
    formulas: [
      { label: 'Nồng độ mol', value: m`\(C_M=\frac{n_{\text{ct}}}{V_{\text{dd}}}\)` },
      { label: 'Số mol chất tan', value: m`\(n_{\text{ct}}=C_MV_{\text{dd}}\)` },
      { label: 'Nồng độ phần trăm', value: m`\(C\%=\frac{m_{\text{ct}}}{m_{\text{dd}}}\times100\%\)` },
      { label: 'Khối lượng dung dịch', value: m`\(m_{\text{dd}}=m_{\text{ct}}+m_{\text{dm}}\)` },
      { label: 'Liên hệ D, V, m', value: m`\(m_{\text{dd}}=D\cdot V_{\text{dd}}\)` },
      { label: 'Pha loãng', value: m`\(C_1V_1=C_2V_2\)` },
      { label: 'Trộn cùng chất tan', value: m`\(C_{\text{sau}}=\frac{C_1V_1+C_2V_2}{V_1+V_2}\)` },
      { label: 'Mol ion từ muối', value: m`\(\mathrm{A}_x\mathrm{B}_y\to x\mathrm{A}^{y+}+y\mathrm{B}^{x-}\)` },
      { label: 'Nồng độ ion', value: m`\([\mathrm{ion}]=\nu_{\mathrm{ion}}C_{\mathrm{chất}}\)` },
      { label: 'Bảo toàn điện tích', value: m`\(\sum n_{\mathrm{cation}}\cdot q_+=\sum n_{\mathrm{anion}}\cdot |q_-|\)` },
    ],
  },
  {
    id: 'stoichiometry-yield-limiting',
    title: 'Tính theo phương trình và hiệu suất',
    grade: 'Chung',
    area: 'Tính toán cơ bản',
    chinese: '化学计量、产率',
    summary: 'Tỉ lệ mol theo hệ số phản ứng, chất giới hạn, hiệu suất và lượng dư.',
    keywords: ['tinh theo phuong trinh', 'hieu suat', 'chat du', 'chat het', 'stoichiometry', '化学计量'],
    formulas: [
      { label: 'Tỉ lệ phương trình', value: m`\(\frac{n_A}{a}=\frac{n_B}{b}=\frac{n_C}{c}\)` },
      { label: 'Chất giới hạn', value: m`\(\min\left(\frac{n_i}{\nu_i}\right)\Rightarrow\text{chất hết}\)` },
      { label: 'Hiệu suất theo sản phẩm', value: m`\(H=\frac{m_{\text{thực tế}}}{m_{\text{lý thuyết}}}\times100\%\)` },
      { label: 'Hiệu suất theo chất phản ứng', value: m`\(H=\frac{n_{\text{đã phản ứng}}}{n_{\text{ban đầu}}}\times100\%\)` },
      { label: 'Lượng sản phẩm thực tế', value: m`\(m_{\text{tt}}=m_{\text{lt}}\cdot\frac{H}{100}\)` },
      { label: 'Lượng chất cần dùng', value: m`\(m_{\text{cần}}=\frac{m_{\text{lý thuyết}}}{H/100}\)` },
      { label: 'Độ tinh khiết', value: m`\(\%P=\frac{m_{\text{chất tinh khiết}}}{m_{\text{mẫu}}}\times100\%\)` },
      { label: 'Bảo toàn khối lượng', value: m`\(\sum m_{\text{trước}}=\sum m_{\text{sau}}\)` },
      { label: 'Bảo toàn nguyên tố', value: m`\(n_{\text{nguyên tố trước}}=n_{\text{nguyên tố sau}}\)` },
    ],
  },
  {
    id: 'gas-laws-mixtures',
    title: 'Khí, hỗn hợp khí và áp suất riêng phần',
    grade: 'Chung',
    area: 'Khí',
    chinese: '气体、分压',
    summary: 'Phương trình trạng thái khí, hỗn hợp khí, áp suất riêng phần và hơi nước.',
    keywords: ['khi', 'hon hop khi', 'ap suat', 'dalton', '气体'],
    formulas: [
      { label: 'Khí lý tưởng', value: m`\(PV=nRT\)` },
      { label: 'Tỉ lệ trạng thái', value: m`\(\frac{P_1V_1}{T_1}=\frac{P_2V_2}{T_2}\)` },
      { label: 'Boyle', value: m`\(PV=\text{hằng số}\quad(T,n\text{ không đổi})\)` },
      { label: 'Charles', value: m`\(\frac{V}{T}=\text{hằng số}\quad(P,n\text{ không đổi})\)` },
      { label: 'Gay Lussac', value: m`\(\frac{P}{T}=\text{hằng số}\quad(V,n\text{ không đổi})\)` },
      { label: 'Áp suất riêng phần', value: m`\(P_i=x_iP_{\text{hh}}\)` },
      { label: 'Phần mol', value: m`\(x_i=\frac{n_i}{n_{\text{hh}}}\)` },
      { label: 'Dalton', value: m`\(P_{\text{hh}}=P_1+P_2+\cdots+P_k\)` },
      { label: 'Khí thu qua nước', value: m`\(P_{\text{khí khô}}=P_{\text{hh}}-P_{\mathrm{H_2O}}\)` },
    ],
  },
  {
    id: 'thermochemistry-enthalpy',
    title: 'Nhiệt hóa học và enthalpy',
    grade: '10',
    area: 'Nhiệt hóa',
    chinese: '热化学、焓变',
    summary: 'Phản ứng tỏa/thu nhiệt, enthalpy tạo thành, Hess và năng lượng liên kết.',
    keywords: ['nhiet hoa hoc', 'enthalpy', 'hess', 'nang luong lien ket', '热化学'],
    formulas: [
      { label: 'Độ biến thiên enthalpy', value: m`\(\Delta H=H_{\text{sản phẩm}}-H_{\text{chất phản ứng}}\)` },
      { label: 'Tỏa nhiệt', value: m`\(\Delta H<0\)` },
      { label: 'Thu nhiệt', value: m`\(\Delta H>0\)` },
      { label: 'Theo enthalpy tạo thành', value: m`\(\Delta H^\circ=\sum \nu \Delta H_f^\circ(\text{sản phẩm})-\sum \nu \Delta H_f^\circ(\text{chất phản ứng})\)` },
      { label: 'Theo năng lượng liên kết', value: m`\(\Delta H\approx\sum E_{\text{bẻ gãy}}-\sum E_{\text{hình thành}}\)` },
      { label: 'Nhiệt lượng', value: m`\(q=mc\Delta T\)` },
      { label: 'Nhiệt lượng mol', value: m`\(q=n\Delta H\)` },
      { label: 'Hess', value: m`\(\Delta H_{\text{tổng}}=\Delta H_1+\Delta H_2+\cdots\)` },
    ],
  },
  {
    id: 'chemical-rate',
    title: 'Tốc độ phản ứng',
    grade: '10',
    area: 'Động hóa học',
    chinese: '化学反应速率',
    summary: 'Tốc độ trung bình, biểu thức tốc độ, bậc phản ứng, nhiệt độ và xúc tác.',
    keywords: ['toc do phan ung', 'dong hoa hoc', 'bac phan ung', '速率'],
    formulas: [
      { label: 'Tốc độ trung bình', value: m`\(v_{\text{tb}}=\frac{|\Delta C|}{\Delta t}\)` },
      { label: 'Phản ứng tổng quát', value: m`\(aA+bB\to cC+dD\)` },
      { label: 'Theo hệ số', value: m`\(v=-\frac{1}{a}\frac{\Delta[A]}{\Delta t}=-\frac{1}{b}\frac{\Delta[B]}{\Delta t}=\frac{1}{c}\frac{\Delta[C]}{\Delta t}=\frac{1}{d}\frac{\Delta[D]}{\Delta t}\)` },
      { label: 'Định luật tốc độ', value: m`\(v=k[A]^m[B]^n\)` },
      { label: 'Bậc phản ứng', value: m`\(\alpha=m+n\)` },
      { label: 'Hệ số nhiệt độ Van Hoff', value: m`\(\frac{v_2}{v_1}=\gamma^{\frac{T_2-T_1}{10}}\)` },
      { label: 'Arrhenius', value: m`\(k=Ae^{-\frac{E_a}{RT}}\)` },
      { label: 'Thời gian bán hủy bậc 1', value: m`\(t_{1/2}=\frac{\ln2}{k}\)` },
    ],
  },
  {
    id: 'chemical-equilibrium',
    title: 'Cân bằng hóa học',
    grade: '11',
    area: 'Cân bằng',
    chinese: '化学平衡',
    summary: 'Hằng số cân bằng, chuyển dịch cân bằng, quan hệ Kc-Kp và thương phản ứng.',
    keywords: ['can bang hoa hoc', 'hang so can bang', 'le chatelier', '平衡'],
    formulas: [
      { label: 'Phản ứng tổng quát', value: m`\(aA+bB\rightleftharpoons cC+dD\)` },
      { label: 'Hằng số Kc', value: m`\(K_c=\frac{[C]^c[D]^d}{[A]^a[B]^b}\)` },
      { label: 'Hằng số Kp', value: m`\(K_p=\frac{P_C^cP_D^d}{P_A^aP_B^b}\)` },
      { label: 'Liên hệ Kp-Kc', value: m`\(K_p=K_c(RT)^{\Delta n}\)` },
      { label: 'Delta n khí', value: m`\(\Delta n=(c+d)-(a+b)\)` },
      { label: 'Thương phản ứng', value: m`\(Q_c=\frac{[C]^c[D]^d}{[A]^a[B]^b}\)` },
      { label: 'Chiều thuận', value: m`\(Q<K\Rightarrow\text{dịch theo chiều tạo sản phẩm}\)` },
      { label: 'Chiều nghịch', value: m`\(Q>K\Rightarrow\text{dịch theo chiều tạo chất phản ứng}\)` },
      { label: 'Tại cân bằng', value: m`\(Q=K\)` },
      { label: 'Chất rắn/lỏng tinh khiết', value: 'Không đưa vào biểu thức hằng số cân bằng.' },
    ],
  },
  {
    id: 'acid-base-ph',
    title: 'Acid, base, pH',
    grade: '11',
    area: 'Acid-base',
    chinese: '酸碱、pH',
    summary: 'pH, pOH, Ka, Kb, Kw, trung hòa và xấp xỉ acid/base yếu.',
    keywords: ['acid', 'base', 'ph', 'poh', 'ka', 'kb', '酸碱'],
    formulas: [
      { label: 'pH', value: m`\(\mathrm{pH}=-\log[\mathrm{H}^+]\)` },
      { label: 'pOH', value: m`\(\mathrm{pOH}=-\log[\mathrm{OH}^-]\)` },
      { label: 'Nước', value: m`\(K_w=[\mathrm{H}^+][\mathrm{OH}^-]=10^{-14}\quad(25^\circ\mathrm{C})\)` },
      { label: 'Liên hệ', value: m`\(\mathrm{pH}+\mathrm{pOH}=14\)` },
      { label: 'Acid mạnh', value: m`\([\mathrm{H}^+]\approx aC_{\mathrm{acid}}\)` },
      { label: 'Base mạnh', value: m`\([\mathrm{OH}^-]\approx bC_{\mathrm{base}}\)` },
      { label: 'Ka', value: m`\(K_a=\frac{[\mathrm{H}^+][\mathrm{A}^-]}{[\mathrm{HA}]}\)` },
      { label: 'Kb', value: m`\(K_b=\frac{[\mathrm{BH}^+][\mathrm{OH}^-]}{[\mathrm{B}]}\)` },
      { label: 'Cặp liên hợp', value: m`\(K_aK_b=K_w\)` },
      { label: 'Acid yếu gần đúng', value: m`\([\mathrm{H}^+]\approx\sqrt{K_aC}\)` },
      { label: 'Base yếu gần đúng', value: m`\([\mathrm{OH}^-]\approx\sqrt{K_bC}\)` },
      { label: 'Trung hòa', value: m`\(n_{\mathrm{H}^+}=n_{\mathrm{OH}^-}\)` },
    ],
  },
  {
    id: 'solubility-precipitation',
    title: 'Độ tan và kết tủa',
    grade: '11',
    area: 'Dung dịch',
    chinese: '溶解度、沉淀',
    summary: 'Độ tan, tích số tan, điều kiện tạo kết tủa và hòa tan kết tủa.',
    keywords: ['do tan', 'ket tua', 'tich so tan', 'ksp', '沉淀'],
    formulas: [
      { label: 'Độ tan theo gam', value: m`\(S=\frac{m_{\text{chất tan}}}{m_{\text{nước}}}\times100\)` },
      { label: 'Tích số tan AB', value: m`\(\mathrm{AB}(s)\rightleftharpoons \mathrm{A}^++\mathrm{B}^-,\quad K_{sp}=[\mathrm{A}^+][\mathrm{B}^-]\)` },
      { label: 'Tích số tan A2B', value: m`\(\mathrm{A_2B}\rightleftharpoons2\mathrm{A}^++\mathrm{B}^{2-},\quad K_{sp}=[\mathrm{A}^+]^2[\mathrm{B}^{2-}]\)` },
      { label: 'Ion product', value: m`\(Q_{sp}=\prod[\mathrm{ion}]^{\nu}\)` },
      { label: 'Có kết tủa', value: m`\(Q_{sp}>K_{sp}\)` },
      { label: 'Bão hòa', value: m`\(Q_{sp}=K_{sp}\)` },
      { label: 'Chưa kết tủa', value: m`\(Q_{sp}<K_{sp}\)` },
      { label: 'Muối AB độ tan s', value: m`\(K_{sp}=s^2\)` },
      { label: 'Muối A2B độ tan s', value: m`\(K_{sp}=4s^3\)` },
      { label: 'Muối AB2 độ tan s', value: m`\(K_{sp}=4s^3\)` },
    ],
  },
  {
    id: 'electrochemistry',
    title: 'Điện hóa học',
    grade: '12',
    area: 'Điện hóa',
    chinese: '电化学',
    summary: 'Pin điện hóa, điện phân, Faraday, dãy điện hóa và suất điện động.',
    keywords: ['dien hoa', 'dien phan', 'faraday', 'pin dien hoa', '电化学'],
    formulas: [
      { label: 'Suất điện động chuẩn', value: m`\(E^\circ_{\text{pin}}=E^\circ_{\text{catot}}-E^\circ_{\text{anot}}\)` },
      { label: 'Gibbs', value: m`\(\Delta G^\circ=-nFE^\circ_{\text{pin}}\)` },
      { label: 'Liên hệ K', value: m`\(\Delta G^\circ=-RT\ln K\)` },
      { label: 'Nernst', value: m`\(E=E^\circ-\frac{0.0592}{n}\log Q\quad(25^\circ\mathrm{C})\)` },
      { label: 'Faraday', value: m`\(m=\frac{AIt}{nF}\)` },
      { label: 'Số mol electron', value: m`\(n_e=\frac{It}{F}\)` },
      { label: 'Điện lượng', value: m`\(Q=It\)` },
      { label: 'Hằng số Faraday', value: m`\(F=96500\ \mathrm{C/mol}\)` },
      { label: 'Catot', value: 'Xảy ra quá trình khử, nhận electron.' },
      { label: 'Anot', value: 'Xảy ra quá trình oxi hóa, nhường electron.' },
      { label: 'Điện phân dung dịch', value: 'So sánh khả năng phóng điện của ion với nước.' },
    ],
  },
  {
    id: 'halogens',
    title: 'Halogen',
    grade: '10',
    area: 'Vô cơ',
    chinese: '卤素',
    summary: 'Flo, clo, brom, iod; tính oxi hóa, hydrogen halide, muối halide và phản ứng đặc trưng.',
    keywords: ['halogen', 'clo', 'brom', 'iod', 'flo', '卤素'],
    formulas: [
      { label: 'Dạng đơn chất', value: m`\(\mathrm{X_2}:\ \mathrm{F_2,Cl_2,Br_2,I_2}\)` },
      { label: 'Số oxi hóa thường gặp', value: m`\(\mathrm{F}:-1;\quad \mathrm{Cl,Br,I}:-1,+1,+3,+5,+7\)` },
      { label: 'Tính oxi hóa', value: m`\(\mathrm{F_2}>\mathrm{Cl_2}>\mathrm{Br_2}>\mathrm{I_2}\)` },
      { label: 'Phản ứng với kim loại', value: m`\(\mathrm{2M}+n\mathrm{X_2}\to2\mathrm{MX}_n\)` },
      { label: 'Halogen mạnh đẩy yếu', value: m`\(\mathrm{Cl_2}+2\mathrm{Br}^-\to2\mathrm{Cl}^-+\mathrm{Br_2}\)` },
      { label: 'Clo tác dụng NaOH lạnh', value: m`\(\mathrm{Cl_2}+2\mathrm{NaOH}\to\mathrm{NaCl}+\mathrm{NaClO}+\mathrm{H_2O}\)` },
      { label: 'Clo tác dụng NaOH nóng', value: m`\(\mathrm{3Cl_2}+6\mathrm{NaOH}\to5\mathrm{NaCl}+\mathrm{NaClO_3}+3\mathrm{H_2O}\)` },
      { label: 'Nhận biết Cl-', value: m`\(\mathrm{Ag}^++\mathrm{Cl}^-\to\mathrm{AgCl}\downarrow\)` },
      { label: 'Nhận biết Br-', value: m`\(\mathrm{Ag}^++\mathrm{Br}^-\to\mathrm{AgBr}\downarrow\)` },
      { label: 'Nhận biết I-', value: m`\(\mathrm{Ag}^++\mathrm{I}^-\to\mathrm{AgI}\downarrow\)` },
    ],
  },
  {
    id: 'oxygen-sulfur',
    title: 'Oxi, lưu huỳnh và hợp chất',
    grade: '10',
    area: 'Vô cơ',
    chinese: '氧、硫及其化合物',
    summary: 'Oxi, ozon, lưu huỳnh, SO2, H2S, H2SO4 và phản ứng đặc trưng.',
    keywords: ['oxi', 'ozon', 'luu huynh', 'h2so4', 'so2', '氧', '硫'],
    formulas: [
      { label: 'Oxi hóa kim loại', value: m`\(\mathrm{2M}+x\mathrm{O_2}\to \mathrm{M}_2\mathrm{O}_{2x}\)` },
      { label: 'Ozon phân hủy', value: m`\(\mathrm{2O_3}\to3\mathrm{O_2}\)` },
      { label: 'SO2 vừa oxi hóa vừa khử', value: m`\(\mathrm{S}^{+4}\to \mathrm{S}^{+6}\ \text{hoặc}\ \mathrm{S}^{0}\)` },
      { label: 'SO2 với kiềm', value: m`\(\mathrm{SO_2}+\mathrm{OH}^-\to\mathrm{HSO_3^-};\quad \mathrm{SO_2}+2\mathrm{OH}^-\to\mathrm{SO_3^{2-}}+\mathrm{H_2O}\)` },
      { label: 'H2S tính khử', value: m`\(\mathrm{H_2S}\to\mathrm{S}\to\mathrm{SO_2}\to\mathrm{SO_4^{2-}}\)` },
      { label: 'H2SO4 loãng', value: m`\(\mathrm{M}+\mathrm{H_2SO_4}\to\mathrm{MSO_4}+\mathrm{H_2}\uparrow\)` },
      { label: 'H2SO4 đặc nóng với Cu', value: m`\(\mathrm{Cu}+2\mathrm{H_2SO_4}\to\mathrm{CuSO_4}+\mathrm{SO_2}+2\mathrm{H_2O}\)` },
      { label: 'Nhận biết sulfate', value: m`\(\mathrm{Ba}^{2+}+\mathrm{SO_4}^{2-}\to\mathrm{BaSO_4}\downarrow\)` },
      { label: 'Oleum', value: m`\(\mathrm{H_2SO_4}\cdot n\mathrm{SO_3}\)` },
    ],
  },
  {
    id: 'nitrogen-phosphorus',
    title: 'Nitơ, phospho và hợp chất',
    grade: '11',
    area: 'Vô cơ',
    chinese: '氮、磷及其化合物',
    summary: 'NH3, muối ammonium, HNO3, nitrate, phosphoric acid và phân bón.',
    keywords: ['nito', 'amoniac', 'hno3', 'photpho', 'phan bon', '氮', '磷'],
    formulas: [
      { label: 'Amoniac base yếu', value: m`\(\mathrm{NH_3}+\mathrm{H_2O}\rightleftharpoons\mathrm{NH_4^+}+\mathrm{OH^-}\)` },
      { label: 'NH3 với acid', value: m`\(\mathrm{NH_3}+\mathrm{H^+}\to\mathrm{NH_4^+}\)` },
      { label: 'Muối ammonium với kiềm', value: m`\(\mathrm{NH_4^+}+\mathrm{OH^-}\to\mathrm{NH_3}\uparrow+\mathrm{H_2O}\)` },
      { label: 'Nhiệt phân NH4NO3', value: m`\(\mathrm{NH_4NO_3}\to\mathrm{N_2O}+2\mathrm{H_2O}\)` },
      { label: 'HNO3 oxi hóa mạnh', value: m`\(\mathrm{N}^{+5}\to\mathrm{NO_2}\ \text{hoặc}\ \mathrm{NO}\)` },
      { label: 'Cu với HNO3 đặc', value: m`\(\mathrm{Cu}+4\mathrm{HNO_3}\to\mathrm{Cu(NO_3)_2}+2\mathrm{NO_2}+2\mathrm{H_2O}\)` },
      { label: 'Cu với HNO3 loãng', value: m`\(\mathrm{3Cu}+8\mathrm{HNO_3}\to3\mathrm{Cu(NO_3)_2}+2\mathrm{NO}+4\mathrm{H_2O}\)` },
      { label: 'H3PO4 ba nấc', value: m`\(\mathrm{H_3PO_4}\rightleftharpoons\mathrm{H^+}+\mathrm{H_2PO_4^-}\rightleftharpoons2\mathrm{H^+}+\mathrm{HPO_4^{2-}}\rightleftharpoons3\mathrm{H^+}+\mathrm{PO_4^{3-}}\)` },
      { label: 'Supephotphat đơn', value: m`\(\mathrm{Ca(H_2PO_4)_2}+\mathrm{CaSO_4}\)` },
      { label: 'Supephotphat kép', value: m`\(\mathrm{Ca(H_2PO_4)_2}\)` },
    ],
  },
  {
    id: 'carbon-silicon',
    title: 'Carbon, silicon và hợp chất',
    grade: '11',
    area: 'Vô cơ',
    chinese: '碳、硅及其化合物',
    summary: 'CO, CO2, muối carbonate, silicate, thủy tinh và phản ứng với acid/kiềm.',
    keywords: ['carbon', 'cacbon', 'co2', 'carbonate', 'silic', '碳', '硅'],
    formulas: [
      { label: 'CO khử oxit kim loại', value: m`\(\mathrm{MO}+\mathrm{CO}\to\mathrm{M}+\mathrm{CO_2}\)` },
      { label: 'CO2 với kiềm', value: m`\(\mathrm{CO_2}+\mathrm{OH^-}\to\mathrm{HCO_3^-};\quad \mathrm{CO_2}+2\mathrm{OH^-}\to\mathrm{CO_3^{2-}}+\mathrm{H_2O}\)` },
      { label: 'Carbonate với acid', value: m`\(\mathrm{CO_3^{2-}}+2\mathrm{H^+}\to\mathrm{CO_2}\uparrow+\mathrm{H_2O}\)` },
      { label: 'Hydrogencarbonate với acid', value: m`\(\mathrm{HCO_3^-}+\mathrm{H^+}\to\mathrm{CO_2}\uparrow+\mathrm{H_2O}\)` },
      { label: 'Hydrogencarbonate với kiềm', value: m`\(\mathrm{HCO_3^-}+\mathrm{OH^-}\to\mathrm{CO_3^{2-}}+\mathrm{H_2O}\)` },
      { label: 'Nhiệt phân CaCO3', value: m`\(\mathrm{CaCO_3}\to\mathrm{CaO}+\mathrm{CO_2}\)` },
      { label: 'SiO2 với kiềm', value: m`\(\mathrm{SiO_2}+2\mathrm{NaOH}\to\mathrm{Na_2SiO_3}+\mathrm{H_2O}\)` },
      { label: 'SiO2 với HF', value: m`\(\mathrm{SiO_2}+4\mathrm{HF}\to\mathrm{SiF_4}+2\mathrm{H_2O}\)` },
      { label: 'Thủy tinh thường', value: m`\(\mathrm{Na_2O\cdot CaO\cdot6SiO_2}\)` },
    ],
  },
  {
    id: 'metals-general',
    title: 'Kim loại đại cương',
    grade: '12',
    area: 'Kim loại',
    chinese: '金属通论',
    summary: 'Tính chất kim loại, dãy điện hóa, ăn mòn, điều chế và bài toán kim loại.',
    keywords: ['kim loai', 'day dien hoa', 'an mon', 'dieu che', '金属'],
    formulas: [
      { label: 'Kim loại nhường electron', value: m`\(\mathrm{M}\to\mathrm{M}^{n+}+ne\)` },
      { label: 'Tính khử kim loại', value: 'Kim loại đứng trước trong dãy điện hóa có tính khử mạnh hơn.' },
      { label: 'Ion kim loại nhận electron', value: m`\(\mathrm{M}^{n+}+ne\to\mathrm{M}\)` },
      { label: 'Ăn mòn điện hóa', value: 'Cần đủ: hai điện cực khác bản chất, tiếp xúc trực tiếp/gián tiếp, cùng trong dung dịch điện li.' },
      { label: 'Kim loại với acid HCl/H2SO4 loãng', value: m`\(\mathrm{M}+n\mathrm{H^+}\to\mathrm{M}^{n+}+\frac{n}{2}\mathrm{H_2}\)` },
      { label: 'Kim loại đẩy kim loại yếu', value: m`\(\mathrm{M}+\mathrm{N}^{k+}\to\mathrm{M}^{n+}+\mathrm{N}\)` },
      { label: 'Điều chế kim loại mạnh', value: 'Điện phân nóng chảy muối/oxide/hydroxide.' },
      { label: 'Điều chế kim loại trung bình yếu', value: 'Khử oxide bằng CO, H2, Al hoặc điện phân dung dịch.' },
      { label: 'Bảo toàn electron kim loại', value: m`\(\sum n_{\mathrm{M}}\cdot k=\sum n_e\text{ nhận}\)` },
    ],
  },
  {
    id: 'alkali-alkaline-aluminum',
    title: 'Kim loại kiềm, kiềm thổ, nhôm',
    grade: '12',
    area: 'Kim loại',
    chinese: '碱金属、碱土金属、铝',
    summary: 'Na, K, Ca, Ba, Al; nước cứng, lưỡng tính và phản ứng đặc trưng.',
    keywords: ['kim loai kiem', 'kiem tho', 'nhom', 'nuoc cung', '铝'],
    formulas: [
      { label: 'Kiềm với nước', value: m`\(\mathrm{2M}+2\mathrm{H_2O}\to2\mathrm{MOH}+\mathrm{H_2}\)` },
      { label: 'Ca/Ba với nước', value: m`\(\mathrm{M}+2\mathrm{H_2O}\to\mathrm{M(OH)_2}+\mathrm{H_2}\)` },
      { label: 'CO2 vào kiềm', value: m`\(\frac{n_{\mathrm{OH^-}}}{n_{\mathrm{CO_2}}}=T\)` },
      { label: 'Tạo HCO3-', value: m`\(T\le1\Rightarrow \mathrm{HCO_3^-}\)` },
      { label: 'Tạo CO3(2-)', value: m`\(T\ge2\Rightarrow \mathrm{CO_3^{2-}}\)` },
      { label: 'Nước cứng tạm thời', value: m`\(\mathrm{Ca(HCO_3)_2},\ \mathrm{Mg(HCO_3)_2}\)` },
      { label: 'Làm mềm bằng đun nóng', value: m`\(\mathrm{Ca(HCO_3)_2}\to\mathrm{CaCO_3}\downarrow+\mathrm{CO_2}+\mathrm{H_2O}\)` },
      { label: 'Al với acid', value: m`\(\mathrm{2Al}+6\mathrm{H^+}\to2\mathrm{Al^{3+}}+3\mathrm{H_2}\)` },
      { label: 'Al với kiềm', value: m`\(\mathrm{2Al}+2\mathrm{OH^-}+6\mathrm{H_2O}\to2[\mathrm{Al(OH)_4}]^-+3\mathrm{H_2}\)` },
      { label: 'Al(OH)3 lưỡng tính', value: m`\(\mathrm{Al(OH)_3}+3\mathrm{H^+}\to\mathrm{Al^{3+}}+3\mathrm{H_2O}\)` },
      { label: 'Al(OH)3 tan trong kiềm', value: m`\(\mathrm{Al(OH)_3}+\mathrm{OH^-}\to[\mathrm{Al(OH)_4}]^-\)` },
    ],
  },
  {
    id: 'iron-chromium-copper',
    title: 'Sắt, crom, đồng và hợp chất',
    grade: '12',
    area: 'Kim loại',
    chinese: '铁、铬、铜',
    summary: 'Trạng thái oxi hóa, phản ứng Fe2+/Fe3+, Cr(III)/Cr(VI), Cu và nhận biết ion.',
    keywords: ['sat', 'crom', 'dong', 'fe2', 'fe3', 'cr', 'cu', '铁', '铬', '铜'],
    formulas: [
      { label: 'Fe thường gặp', value: m`\(\mathrm{Fe}:0,+2,+3\)` },
      { label: 'Fe với HCl', value: m`\(\mathrm{Fe}+2\mathrm{HCl}\to\mathrm{FeCl_2}+\mathrm{H_2}\)` },
      { label: 'Fe với Cl2', value: m`\(\mathrm{2Fe}+3\mathrm{Cl_2}\to2\mathrm{FeCl_3}\)` },
      { label: 'Fe2+ bị oxi hóa', value: m`\(\mathrm{Fe^{2+}}\to\mathrm{Fe^{3+}}+e\)` },
      { label: 'Fe3+ bị khử', value: m`\(\mathrm{Fe^{3+}}+e\to\mathrm{Fe^{2+}}\)` },
      { label: 'Nhận biết Fe2+', value: m`\(\mathrm{Fe^{2+}}+2\mathrm{OH^-}\to\mathrm{Fe(OH)_2}\downarrow\)` },
      { label: 'Nhận biết Fe3+', value: m`\(\mathrm{Fe^{3+}}+3\mathrm{OH^-}\to\mathrm{Fe(OH)_3}\downarrow\)` },
      { label: 'Cu với HNO3 đặc', value: m`\(\mathrm{Cu}+4\mathrm{HNO_3}\to\mathrm{Cu(NO_3)_2}+2\mathrm{NO_2}+2\mathrm{H_2O}\)` },
      { label: 'Cr(OH)3 lưỡng tính', value: m`\(\mathrm{Cr(OH)_3}+\mathrm{OH^-}\to[\mathrm{Cr(OH)_4}]^-\)` },
      { label: 'Cr2O7 và CrO4', value: m`\(\mathrm{Cr_2O_7^{2-}}+\mathrm{H_2O}\rightleftharpoons2\mathrm{CrO_4^{2-}}+2\mathrm{H^+}\)` },
    ],
  },
  {
    id: 'organic-general',
    title: 'Đại cương hóa hữu cơ',
    grade: '11',
    area: 'Hữu cơ',
    chinese: '有机化学基础',
    summary: 'Công thức phân tử, độ bất bão hòa, đồng đẳng, đồng phân và đốt cháy hữu cơ.',
    keywords: ['hoa huu co', 'do bat bao hoa', 'dong phan', 'dot chay', '有机'],
    formulas: [
      { label: 'Độ bất bão hòa', value: m`\(\Delta=\frac{2C+2+N-H-X}{2}\)` },
      { label: 'Hydrocarbon no mạch hở', value: m`\(\mathrm{C}_n\mathrm{H}_{2n+2}\)` },
      { label: 'Một liên kết pi/vòng', value: m`\(\mathrm{C}_n\mathrm{H}_{2n}\)` },
      { label: 'Hai liên kết pi/vòng', value: m`\(\mathrm{C}_n\mathrm{H}_{2n-2}\)` },
      { label: 'Đốt cháy CxHyOz', value: m`\(\mathrm{C}_x\mathrm{H}_y\mathrm{O}_z+\left(x+\frac{y}{4}-\frac{z}{2}\right)\mathrm{O}_2\to x\mathrm{CO}_2+\frac{y}{2}\mathrm{H}_2\mathrm{O}\)` },
      { label: 'Bảo toàn C', value: m`\(n_C=n_{\mathrm{CO_2}}\)` },
      { label: 'Bảo toàn H', value: m`\(n_H=2n_{\mathrm{H_2O}}\)` },
      { label: 'Bảo toàn O', value: m`\(n_O=2n_{\mathrm{CO_2}}+n_{\mathrm{H_2O}}-2n_{\mathrm{O_2}}\)` },
      { label: 'Khối lượng hữu cơ', value: m`\(m_C+m_H+m_O+\cdots=m_{\text{chất}}\)` },
    ],
  },
  {
    id: 'hydrocarbons',
    title: 'Hydrocarbon',
    grade: '11',
    area: 'Hữu cơ',
    chinese: '烃',
    summary: 'Alkane, alkene, alkyne, arene; phản ứng cháy, cộng, thế và nhận biết.',
    keywords: ['hydrocarbon', 'ankan', 'anken', 'ankin', 'benzen', '烃'],
    formulas: [
      { label: 'Alkane', value: m`\(\mathrm{C}_n\mathrm{H}_{2n+2}\quad(n\ge1)\)` },
      { label: 'Cycloalkane/alkene', value: m`\(\mathrm{C}_n\mathrm{H}_{2n}\quad(n\ge2)\)` },
      { label: 'Alkyne/alkadiene', value: m`\(\mathrm{C}_n\mathrm{H}_{2n-2}\quad(n\ge2)\)` },
      { label: 'Arene đơn vòng', value: m`\(\mathrm{C}_n\mathrm{H}_{2n-6}\quad(n\ge6)\)` },
      { label: 'Đốt alkane', value: m`\(\mathrm{C}_n\mathrm{H}_{2n+2}+\frac{3n+1}{2}\mathrm{O}_2\to n\mathrm{CO}_2+(n+1)\mathrm{H}_2\mathrm{O}\)` },
      { label: 'Đốt alkene', value: m`\(\mathrm{C}_n\mathrm{H}_{2n}+\frac{3n}{2}\mathrm{O}_2\to n\mathrm{CO}_2+n\mathrm{H}_2\mathrm{O}\)` },
      { label: 'Đốt alkyne', value: m`\(\mathrm{C}_n\mathrm{H}_{2n-2}+\frac{3n-1}{2}\mathrm{O}_2\to n\mathrm{CO}_2+(n-1)\mathrm{H}_2\mathrm{O}\)` },
      { label: 'Alkene cộng brom', value: m`\(\mathrm{C=C}+\mathrm{Br_2}\to\mathrm{Br-C-C-Br}\)` },
      { label: 'Alkyne đầu mạch với AgNO3/NH3', value: m`\(\mathrm{R-C{\equiv}CH}+\mathrm{AgNO_3}+\mathrm{NH_3}\to\mathrm{R-C{\equiv}CAg}\downarrow+\mathrm{NH_4NO_3}\)` },
      { label: 'Benzen thế brom', value: m`\(\mathrm{C_6H_6}+\mathrm{Br_2}\to\mathrm{C_6H_5Br}+\mathrm{HBr}\)` },
      { label: 'Tỉ lệ đốt alkene', value: m`\(n_{\mathrm{CO_2}}=n_{\mathrm{H_2O}}\)` },
      { label: 'Tỉ lệ đốt alkane', value: m`\(n_{\mathrm{H_2O}}-n_{\mathrm{CO_2}}=n_{\text{ankan}}\)` },
    ],
  },
  {
    id: 'alcohol-phenol-ether',
    title: 'Alcohol, phenol, ether',
    grade: '11',
    area: 'Hữu cơ',
    chinese: '醇、酚、醚',
    summary: 'Công thức, phản ứng với Na, tách nước, oxi hóa alcohol và phenol.',
    keywords: ['ancol', 'alcohol', 'phenol', 'ether', '醇', '酚'],
    formulas: [
      { label: 'Alcohol no đơn chức', value: m`\(\mathrm{C}_n\mathrm{H}_{2n+1}\mathrm{OH}\)` },
      { label: 'Alcohol no đơn chức mạch hở', value: m`\(\mathrm{C}_n\mathrm{H}_{2n+2}\mathrm{O}\)` },
      { label: 'Phản ứng với Na', value: m`\(\mathrm{2ROH}+2\mathrm{Na}\to2\mathrm{RONa}+\mathrm{H_2}\)` },
      { label: 'Mol H2 từ alcohol', value: m`\(n_{\mathrm{H_2}}=\frac{1}{2}n_{\mathrm{OH}}\)` },
      { label: 'Tách nước tạo alkene', value: m`\(\mathrm{C}_n\mathrm{H}_{2n+1}\mathrm{OH}\to\mathrm{C}_n\mathrm{H}_{2n}+\mathrm{H_2O}\)` },
      { label: 'Oxi hóa alcohol bậc 1', value: m`\(\mathrm{RCH_2OH}\to\mathrm{RCHO}\to\mathrm{RCOOH}\)` },
      { label: 'Oxi hóa alcohol bậc 2', value: m`\(\mathrm{R_1CHOHR_2}\to\mathrm{R_1COR_2}\)` },
      { label: 'Phenol với NaOH', value: m`\(\mathrm{C_6H_5OH}+\mathrm{NaOH}\to\mathrm{C_6H_5ONa}+\mathrm{H_2O}\)` },
      { label: 'Phenol với brom', value: m`\(\mathrm{C_6H_5OH}+3\mathrm{Br_2}\to\mathrm{C_6H_2Br_3OH}\downarrow+3\mathrm{HBr}\)` },
    ],
  },
  {
    id: 'aldehyde-ketone-carboxylic-ester',
    title: 'Aldehyde, ketone, acid carboxylic, ester',
    grade: '12',
    area: 'Hữu cơ',
    chinese: '醛、酮、羧酸、酯',
    summary: 'Nhóm carbonyl, tráng bạc, acid, ester hóa, xà phòng hóa và chỉ số ester.',
    keywords: ['andehit', 'xeton', 'acid carboxylic', 'este', 'trang bac', '醛', '酯'],
    formulas: [
      { label: 'Aldehyde no đơn chức', value: m`\(\mathrm{C}_n\mathrm{H}_{2n}\mathrm{O}\)` },
      { label: 'Acid no đơn chức', value: m`\(\mathrm{C}_n\mathrm{H}_{2n}\mathrm{O}_2\)` },
      { label: 'Ester no đơn chức', value: m`\(\mathrm{C}_n\mathrm{H}_{2n}\mathrm{O}_2\)` },
      { label: 'Tráng bạc aldehyde', value: m`\(\mathrm{RCHO}\to2\mathrm{Ag}\)` },
      { label: 'Formaldehyde tráng bạc', value: m`\(\mathrm{HCHO}\to4\mathrm{Ag}\)` },
      { label: 'Khử aldehyde', value: m`\(\mathrm{RCHO}+\mathrm{H_2}\to\mathrm{RCH_2OH}\)` },
      { label: 'Acid với base', value: m`\(\mathrm{RCOOH}+\mathrm{NaOH}\to\mathrm{RCOONa}+\mathrm{H_2O}\)` },
      { label: 'Ester hóa', value: m`\(\mathrm{RCOOH}+\mathrm{R'OH}\rightleftharpoons\mathrm{RCOOR'}+\mathrm{H_2O}\)` },
      { label: 'Thủy phân ester acid', value: m`\(\mathrm{RCOOR'}+\mathrm{H_2O}\rightleftharpoons\mathrm{RCOOH}+\mathrm{R'OH}\)` },
      { label: 'Xà phòng hóa', value: m`\(\mathrm{RCOOR'}+\mathrm{NaOH}\to\mathrm{RCOONa}+\mathrm{R'OH}\)` },
      { label: 'Chất béo xà phòng hóa', value: m`\((\mathrm{RCOO})_3\mathrm{C_3H_5}+3\mathrm{NaOH}\to3\mathrm{RCOONa}+\mathrm{C_3H_5(OH)_3}\)` },
      { label: 'Số mol NaOH ester đơn chức', value: m`\(n_{\mathrm{NaOH}}=n_{\mathrm{ester}}\)` },
    ],
  },
  {
    id: 'amine-amino-acid-protein',
    title: 'Amine, amino acid, peptide, protein',
    grade: '12',
    area: 'Hữu cơ',
    chinese: '胺、氨基酸、蛋白质',
    summary: 'Tính base của amine, amino acid lưỡng tính, peptide và thủy phân.',
    keywords: ['amin', 'amino acid', 'peptide', 'protein', '胺', '氨基酸'],
    formulas: [
      { label: 'Amine no đơn chức', value: m`\(\mathrm{C}_n\mathrm{H}_{2n+3}\mathrm{N}\)` },
      { label: 'Amine với acid', value: m`\(\mathrm{RNH_2}+\mathrm{HCl}\to\mathrm{RNH_3Cl}\)` },
      { label: 'Aniline với HCl', value: m`\(\mathrm{C_6H_5NH_2}+\mathrm{HCl}\to\mathrm{C_6H_5NH_3Cl}\)` },
      { label: 'Amino acid dạng chung', value: m`\(\mathrm{H_2N-R-COOH}\)` },
      { label: 'Amino acid với HCl', value: m`\(\mathrm{H_2N-R-COOH}+\mathrm{HCl}\to\mathrm{ClH_3N-R-COOH}\)` },
      { label: 'Amino acid với NaOH', value: m`\(\mathrm{H_2N-R-COOH}+\mathrm{NaOH}\to\mathrm{H_2N-R-COONa}+\mathrm{H_2O}\)` },
      { label: 'Peptide bond', value: m`\(\mathrm{-CO-NH-}\)` },
      { label: 'Số liên kết peptide mạch hở', value: m`\(k_{\text{peptide}}=n_{\text{gốc amino acid}}-1\)` },
      { label: 'Thủy phân peptide', value: m`\(\mathrm{peptide}+(n-1)\mathrm{H_2O}\to n\ \mathrm{amino\ acid}\)` },
      { label: 'Phản ứng biuret', value: 'Peptide có từ 2 liên kết peptide trở lên tạo màu tím với Cu(OH)2 trong môi trường kiềm.' },
    ],
  },
  {
    id: 'carbohydrates',
    title: 'Carbohydrate',
    grade: '12',
    area: 'Hữu cơ',
    chinese: '糖类',
    summary: 'Glucose, fructose, saccharose, tinh bột, cellulose và phản ứng nhận biết.',
    keywords: ['glucose', 'fructose', 'saccarozơ', 'tinh bot', 'cellulose', '糖'],
    formulas: [
      { label: 'Glucose', value: m`\(\mathrm{C_6H_{12}O_6}\)` },
      { label: 'Fructose', value: m`\(\mathrm{C_6H_{12}O_6}\)` },
      { label: 'Saccharose', value: m`\(\mathrm{C_{12}H_{22}O_{11}}\)` },
      { label: 'Tinh bột/cellulose', value: m`\((\mathrm{C_6H_{10}O_5})_n\)` },
      { label: 'Glucose tráng bạc', value: m`\(\mathrm{C_6H_{12}O_6}\to2\mathrm{Ag}\)` },
      { label: 'Glucose lên men rượu', value: m`\(\mathrm{C_6H_{12}O_6}\to2\mathrm{C_2H_5OH}+2\mathrm{CO_2}\)` },
      { label: 'Thủy phân saccharose', value: m`\(\mathrm{C_{12}H_{22}O_{11}}+\mathrm{H_2O}\to\mathrm{C_6H_{12}O_6}+\mathrm{C_6H_{12}O_6}\)` },
      { label: 'Thủy phân tinh bột', value: m`\((\mathrm{C_6H_{10}O_5})_n+n\mathrm{H_2O}\to n\mathrm{C_6H_{12}O_6}\)` },
      { label: 'Iod nhận biết tinh bột', value: 'Tinh bột tạo màu xanh tím với I2.' },
      { label: 'Cellulose trinitrate', value: m`\(\mathrm{C_6H_7O_2(OH)_3}+3\mathrm{HNO_3}\to\mathrm{C_6H_7O_2(ONO_2)_3}+3\mathrm{H_2O}\)` },
    ],
  },
  {
    id: 'polymers-materials',
    title: 'Polime và vật liệu',
    grade: '12',
    area: 'Hữu cơ',
    chinese: '聚合物、材料',
    summary: 'Trùng hợp, trùng ngưng, hệ số polime hóa và các polime hay gặp.',
    keywords: ['polime', 'trung hop', 'trung ngung', 'polymer', '聚合物'],
    formulas: [
      { label: 'Hệ số polime hóa', value: m`\(n=\frac{M_{\text{polime}}}{M_{\text{mắt xích}}}\)` },
      { label: 'Trùng hợp ethylene', value: m`\(n\mathrm{CH_2{=}CH_2}\to[-\mathrm{CH_2-CH_2}-]_n\)` },
      { label: 'PVC', value: m`\(n\mathrm{CH_2{=}CHCl}\to[-\mathrm{CH_2-CHCl}-]_n\)` },
      { label: 'Polystyrene', value: m`\(n\mathrm{C_6H_5CH{=}CH_2}\to[-\mathrm{CH_2-CH(C_6H_5)}-]_n\)` },
      { label: 'Cao su buna', value: m`\(n\mathrm{CH_2{=}CH-CH{=}CH_2}\to[-\mathrm{CH_2-CH{=}CH-CH_2}-]_n\)` },
      { label: 'Teflon', value: m`\(n\mathrm{CF_2{=}CF_2}\to[-\mathrm{CF_2-CF_2}-]_n\)` },
      { label: 'Nylon-6,6', value: 'Trùng ngưng hexamethylenediamine và adipic acid, tách nước.' },
      { label: 'Tơ capron', value: 'Trùng ngưng hoặc trùng hợp mở vòng caprolactam.' },
      { label: 'Trùng ngưng', value: 'Monomer có ít nhất hai nhóm chức, thường tách phân tử nhỏ như H2O, HCl.' },
    ],
  },
  {
    id: 'common-recognition-reactions',
    title: 'Nhận biết nhanh và kết tủa thường gặp',
    grade: 'Chung',
    area: 'Nhận biết',
    chinese: '常见鉴别反应',
    summary: 'Màu kết tủa, khí thoát ra, thuốc thử hay gặp trong đề trắc nghiệm.',
    keywords: ['nhan biet', 'ket tua', 'mau sac', 'thuoc thu', '鉴别'],
    formulas: [
      { label: 'AgCl', value: m`\(\mathrm{Ag^+}+\mathrm{Cl^-}\to\mathrm{AgCl}\downarrow\)`, note: 'Trắng.' },
      { label: 'AgBr', value: m`\(\mathrm{Ag^+}+\mathrm{Br^-}\to\mathrm{AgBr}\downarrow\)`, note: 'Vàng nhạt.' },
      { label: 'AgI', value: m`\(\mathrm{Ag^+}+\mathrm{I^-}\to\mathrm{AgI}\downarrow\)`, note: 'Vàng đậm.' },
      { label: 'BaSO4', value: m`\(\mathrm{Ba^{2+}}+\mathrm{SO_4^{2-}}\to\mathrm{BaSO_4}\downarrow\)`, note: 'Trắng, không tan trong acid mạnh.' },
      { label: 'CaCO3', value: m`\(\mathrm{Ca^{2+}}+\mathrm{CO_3^{2-}}\to\mathrm{CaCO_3}\downarrow\)`, note: 'Trắng, tan trong acid giải phóng CO2.' },
      { label: 'Fe(OH)2', value: m`\(\mathrm{Fe^{2+}}+2\mathrm{OH^-}\to\mathrm{Fe(OH)_2}\downarrow\)`, note: 'Trắng xanh, hóa nâu ngoài không khí.' },
      { label: 'Fe(OH)3', value: m`\(\mathrm{Fe^{3+}}+3\mathrm{OH^-}\to\mathrm{Fe(OH)_3}\downarrow\)`, note: 'Nâu đỏ.' },
      { label: 'Cu(OH)2', value: m`\(\mathrm{Cu^{2+}}+2\mathrm{OH^-}\to\mathrm{Cu(OH)_2}\downarrow\)`, note: 'Xanh lam.' },
      { label: 'Al(OH)3', value: m`\(\mathrm{Al^{3+}}+3\mathrm{OH^-}\to\mathrm{Al(OH)_3}\downarrow\)`, note: 'Keo trắng, tan trong kiềm dư.' },
      { label: 'NH4+', value: m`\(\mathrm{NH_4^+}+\mathrm{OH^-}\to\mathrm{NH_3}\uparrow+\mathrm{H_2O}\)` },
      { label: 'CO3(2-)', value: m`\(\mathrm{CO_3^{2-}}+2\mathrm{H^+}\to\mathrm{CO_2}\uparrow+\mathrm{H_2O}\)` },
      { label: 'Sulfide', value: m`\(\mathrm{S^{2-}}+2\mathrm{H^+}\to\mathrm{H_2S}\uparrow\)` },
    ],
  },
  {
    id: 'chemistry-csca-patterns',
    title: 'Mẫu nhận diện nhanh trong đề Hóa CSCA',
    grade: 'Chung',
    area: 'Chiến thuật',
    chinese: '化学考试常见表达',
    summary: 'Từ khóa tiếng Trung thường kéo theo công thức hoặc hướng xử lý tương ứng.',
    keywords: ['csca', 'tu khoa trung', 'doc de hoa', '关键词', '化学'],
    formulas: [
      { label: '物质的量', value: m`Mol: \(n=\frac{m}{M}\), \(n=C_MV\), \(PV=nRT\).` },
      { label: '浓度', value: m`Nồng độ: \(C_M=\frac{n}{V}\), \(C\%=\frac{m_{\text{ct}}}{m_{\text{dd}}}\times100\%\).` },
      { label: '过量 / 不足', value: m`Dư/thiếu: so sánh \(\frac{n_i}{\nu_i}\), giá trị nhỏ là chất giới hạn.` },
      { label: '产率', value: m`Hiệu suất: \(H=\frac{\text{thực tế}}{\text{lý thuyết}}\times100\%\).` },
      { label: '氧化还原', value: m`Oxi hóa khử: dùng bảo toàn electron \(\sum e_{\text{nhường}}=\sum e_{\text{nhận}}\).` },
      { label: '酸碱中和', value: m`Trung hòa: \(n_{\mathrm{H^+}}=n_{\mathrm{OH^-}}\).` },
      { label: '平衡常数', value: m`Cân bằng: \(K_c=\frac{[C]^c[D]^d}{[A]^a[B]^b}\).` },
      { label: '沉淀', value: m`Kết tủa: so sánh \(Q_{sp}\) với \(K_{sp}\).` },
      { label: '电解', value: m`Điện phân: \(m=\frac{AIt}{nF}\).` },
      { label: '燃烧', value: m`Đốt cháy hữu cơ: bảo toàn C, H, O qua \(\mathrm{CO_2}\), \(\mathrm{H_2O}\), \(\mathrm{O_2}\).` },
    ],
  },
];

export const CHEMISTRY_FORMULA_GRADE_OPTIONS: ChemistryFormulaGrade[] = ['Chung', '10', '11', '12'];

export const CHEMISTRY_FORMULA_AREAS = Array.from(
  new Set(CHEMISTRY_CSCA_FORMULA_TOPICS.map(topic => topic.area)),
);
