export type ChineseSocialFormulaGrade = 'Chung';

export interface ChineseSocialFormulaLine {
  label: string;
  value: string;
  note?: string;
}

export interface ChineseSocialCscaFormulaTopic {
  id: string;
  title: string;
  grade: ChineseSocialFormulaGrade;
  area: string;
  chinese?: string;
  summary: string;
  keywords: string[];
  formulas: ChineseSocialFormulaLine[];
  notes?: string[];
}

export const CHINESE_SOCIAL_CSCA_FORMULA_TOPICS: ChineseSocialCscaFormulaTopic[] = [
  {
    id: 'social-reading-signals',
    title: 'Tín hiệu đọc hiểu xã hội - nhân văn',
    grade: 'Chung',
    area: 'Đọc hiểu XH',
    chinese: '人文社科阅读',
    summary: 'Mẫu câu mở ý, nêu hiện tượng, giải thích bối cảnh và kết luận trong bài xã hội.',
    keywords: ['doc hieu', 'xa hoi', 'nhan van', '人文', '社会', '现象'],
    formulas: [
      { label: 'Hiện tượng xã hội', value: '近年来，A 现象越来越普遍。' },
      { label: 'Bối cảnh', value: '在 A 背景下，B 受到广泛关注。' },
      { label: 'Vấn đề cốt lõi', value: '问题的关键在于 A。' },
      { label: 'Quan điểm chung', value: '人们普遍认为，A。' },
      { label: 'Tranh luận', value: '关于 A，人们有不同看法。' },
      { label: 'Ý nghĩa', value: 'A 对 B 具有重要意义。' },
      { label: 'Tác động', value: 'A 对 B 产生了深远影响。' },
      { label: 'Xu hướng', value: 'A 已成为一种重要趋势。' },
      { label: 'Kết luận', value: '由此可见，A 不仅 B，而且 C。' },
      { label: 'Tóm lại', value: '总的来说，A 反映了 B。' },
    ],
    notes: ['Bài XH hay bẫy ở thái độ tác giả: 普遍认为 không nhất thiết là tác giả đồng ý hoàn toàn.'],
  },
  {
    id: 'opinion-argument',
    title: 'Nêu quan điểm, lập luận và phản biện',
    grade: 'Chung',
    area: 'Lập luận',
    chinese: '观点与论证',
    summary: 'Cấu trúc nhận diện luận điểm, luận cứ, phản biện và kết luận trong bài nghị luận.',
    keywords: ['quan diem', 'lap luan', 'phan bien', '观点', '论证', '反驳'],
    formulas: [
      { label: 'Theo tôi', value: '我认为 / 在我看来，A。' },
      { label: 'Có người cho rằng', value: '有人认为 A，也有人认为 B。' },
      { label: 'Luận điểm chính', value: '作者的主要观点是 A。' },
      { label: 'Lý do thứ nhất', value: '首先，A；其次，B；最后，C。' },
      { label: 'Dẫn chứng', value: '以 A 为例，可以说明 B。' },
      { label: 'Mặt tích cực', value: 'A 的积极作用在于 B。' },
      { label: 'Mặt hạn chế', value: 'A 也存在一定局限。' },
      { label: 'Phản biện nhẹ', value: '这种看法有一定道理，但忽视了 A。' },
      { label: 'Cân bằng quan điểm', value: '我们既要看到 A，也要注意 B。' },
      { label: 'Đưa giải pháp', value: '解决 A 问题，需要从 B 入手。' },
    ],
  },
  {
    id: 'culture-tradition',
    title: 'Văn hóa, truyền thống và bản sắc',
    grade: 'Chung',
    area: 'Văn hóa',
    chinese: '文化与传统',
    summary: 'Mẫu diễn đạt về phong tục, lễ hội, di sản, giao lưu văn hóa và bản sắc dân tộc.',
    keywords: ['van hoa', 'truyen thong', 'le hoi', '文化', '传统', '习俗'],
    formulas: [
      { label: 'Truyền thống lâu đời', value: 'A 有着悠久的历史和丰富的文化内涵。' },
      { label: 'Phong tục', value: 'A 是当地重要的传统习俗。' },
      { label: 'Lễ hội', value: '在 A 节日，人们通常会 B。' },
      { label: 'Di sản', value: 'A 被视为重要的文化遗产。' },
      { label: 'Bản sắc', value: 'A 体现了 B 的文化特色。' },
      { label: 'Kế thừa', value: '传承 A，有助于增强文化认同。' },
      { label: 'Đổi mới', value: '传统文化需要在创新中发展。' },
      { label: 'Giao lưu', value: '文化交流促进了不同文明之间的理解。' },
      { label: 'Xung đột văn hóa', value: '不同文化之间可能存在差异和误解。' },
      { label: 'Tôn trọng đa dạng', value: '尊重文化多样性，是交流的前提。' },
    ],
  },
  {
    id: 'history-civilization',
    title: 'Lịch sử, nhân vật và văn minh',
    grade: 'Chung',
    area: 'Lịch sử',
    chinese: '历史与文明',
    summary: 'Mẫu câu đọc hiểu văn bản lịch sử: nguyên nhân, diễn biến, kết quả, ảnh hưởng và đánh giá nhân vật.',
    keywords: ['lich su', 'van minh', 'nhan vat', '历史', '文明', '人物'],
    formulas: [
      { label: 'Thời kỳ', value: '在 A 时期，B 得到了发展。' },
      { label: 'Bối cảnh lịch sử', value: 'A 的出现与当时的社会背景有关。' },
      { label: 'Nguyên nhân lịch sử', value: '导致 A 的原因主要有 B 和 C。' },
      { label: 'Diễn biến', value: 'A 经历了 B、C、D 几个阶段。' },
      { label: 'Kết quả', value: 'A 最终导致了 B。' },
      { label: 'Ảnh hưởng lâu dài', value: 'A 对后来的 B 产生了深远影响。' },
      { label: 'Đóng góp', value: 'A 在 B 方面作出了重要贡献。' },
      { label: 'Đánh giá nhân vật', value: '评价 A，不能脱离其所处的时代。' },
      { label: 'Bài học', value: '这段历史给我们的启示是 A。' },
      { label: 'Văn minh', value: 'A 是人类文明发展的重要成果。' },
    ],
  },
  {
    id: 'education-learning',
    title: 'Giáo dục, học tập và phát triển cá nhân',
    grade: 'Chung',
    area: 'Giáo dục',
    chinese: '教育与成长',
    summary: 'Mẫu câu về trường học, phương pháp học, áp lực, kỹ năng, cơ hội và trưởng thành.',
    keywords: ['giao duc', 'hoc tap', 'phat trien', '教育', '学习', '成长'],
    formulas: [
      { label: 'Vai trò giáo dục', value: '教育在个人成长中起着重要作用。' },
      { label: 'Phương pháp học', value: '有效的学习方法可以提高学习效率。' },
      { label: 'Tự học', value: '自主学习能力越来越重要。' },
      { label: 'Áp lực học tập', value: '过大的学习压力可能影响身心健康。' },
      { label: 'Cân bằng', value: '学生需要在学习和生活之间保持平衡。' },
      { label: 'Kỹ năng', value: '除了知识，A 能力也不可忽视。' },
      { label: 'Cơ hội', value: 'A 为学生提供了更多发展机会。' },
      { label: 'Công bằng giáo dục', value: '教育公平关系到社会的长远发展。' },
      { label: 'Du học', value: '留学经历有助于开阔视野。' },
      { label: 'Trưởng thành', value: '成长意味着学会承担责任。' },
    ],
  },
  {
    id: 'economy-development',
    title: 'Kinh tế, tiêu dùng và phát triển',
    grade: 'Chung',
    area: 'Kinh tế',
    chinese: '经济与发展',
    summary: 'Mẫu diễn đạt về phát triển kinh tế, tiêu dùng, việc làm, đô thị hóa, bất bình đẳng và bền vững.',
    keywords: ['kinh te', 'tieu dung', 'viec lam', '经济', '消费', '发展'],
    formulas: [
      { label: 'Phát triển kinh tế', value: '经济发展提高了人们的生活水平。' },
      { label: 'Tăng trưởng', value: 'A 的增长带动了 B 的发展。' },
      { label: 'Tiêu dùng', value: '消费观念的变化反映了社会发展。' },
      { label: 'Nhu cầu', value: '随着收入提高，人们对 A 的需求增加。' },
      { label: 'Việc làm', value: 'A 创造了更多就业机会。' },
      { label: 'Đô thị hóa', value: '城市化进程改变了人们的生活方式。' },
      { label: 'Bất bình đẳng', value: 'A 可能加剧社会差距。' },
      { label: 'Bền vững', value: '发展不能以牺牲环境为代价。' },
      { label: 'Cân bằng lợi ích', value: '需要在效率和公平之间取得平衡。' },
      { label: 'Tác động thị trường', value: '市场变化会直接影响 A。' },
    ],
  },
  {
    id: 'media-technology-society',
    title: 'Truyền thông, internet và xã hội số',
    grade: 'Chung',
    area: 'Truyền thông',
    chinese: '媒体与数字社会',
    summary: 'Mẫu câu về mạng xã hội, thông tin, quyền riêng tư, tin giả, trí tuệ nhân tạo và đời sống số.',
    keywords: ['truyen thong', 'internet', 'mang xa hoi', '媒体', '网络', '人工智能'],
    formulas: [
      { label: 'Thông tin lan truyền', value: '网络使信息传播更加迅速。' },
      { label: 'Mạng xã hội', value: '社交媒体改变了人们的交流方式。' },
      { label: 'Tin giả', value: '虚假信息容易误导公众。' },
      { label: 'Quyền riêng tư', value: '个人隐私保护成为重要问题。' },
      { label: 'Thuật toán', value: '算法推荐会影响人们获取信息的方式。' },
      { label: 'AI', value: '人工智能提高了效率，也带来了新的挑战。' },
      { label: 'Lệ thuộc công nghệ', value: '过度依赖技术可能削弱人的判断力。' },
      { label: 'Khoảng cách số', value: '数字鸿沟会影响教育和就业机会。' },
      { label: 'Truyền thông trách nhiệm', value: '媒体应承担社会责任。' },
      { label: 'Suy nghĩ độc lập', value: '面对信息，公众需要保持独立思考。' },
    ],
  },
  {
    id: 'law-policy-public',
    title: 'Pháp luật, chính sách và trách nhiệm công dân',
    grade: 'Chung',
    area: 'Công dân',
    chinese: '法律、政策与公民责任',
    summary: 'Mẫu câu về quy định, chính sách công, quyền lợi, nghĩa vụ, trật tự và trách nhiệm xã hội.',
    keywords: ['phap luat', 'chinh sach', 'cong dan', '法律', '政策', '责任'],
    formulas: [
      { label: 'Chính sách', value: '政策的出台是为了解决 A 问题。' },
      { label: 'Quy định', value: '相关规定有助于规范 A 行为。' },
      { label: 'Tuân thủ pháp luật', value: '公民应自觉遵守法律法规。' },
      { label: 'Quyền và nghĩa vụ', value: '权利和义务是相互统一的。' },
      { label: 'Lợi ích công cộng', value: '公共利益需要每个人共同维护。' },
      { label: 'Trách nhiệm cá nhân', value: '每个人都应承担相应的社会责任。' },
      { label: 'Quản lý xã hội', value: '有效管理可以提高社会运行效率。' },
      { label: 'Công bằng', value: '制度公平是社会稳定的重要基础。' },
      { label: 'Thực thi', value: '政策效果取决于执行力度。' },
      { label: 'Ý thức công dân', value: '公民意识的提高有助于社会进步。' },
    ],
  },
  {
    id: 'interpersonal-ethics',
    title: 'Quan hệ xã hội, đạo đức và giá trị',
    grade: 'Chung',
    area: 'Đạo đức',
    chinese: '人际关系与价值观',
    summary: 'Mẫu câu về gia đình, cộng đồng, lòng tin, trách nhiệm, lựa chọn giá trị và xung đột thế hệ.',
    keywords: ['dao duc', 'gia dinh', 'gia tri', '人际关系', '价值观', '责任'],
    formulas: [
      { label: 'Quan hệ gia đình', value: '家庭关系对个人成长有重要影响。' },
      { label: 'Xung đột thế hệ', value: '代际差异可能导致沟通困难。' },
      { label: 'Tôn trọng', value: '相互尊重是良好关系的基础。' },
      { label: 'Lòng tin', value: '信任需要通过长期行动建立。' },
      { label: 'Trách nhiệm', value: '责任感体现了一个人的成熟。' },
      { label: 'Hợp tác', value: '合作可以实现个人与集体的共同发展。' },
      { label: 'Cạnh tranh', value: '合理竞争能够激发人的潜力。' },
      { label: 'Lựa chọn giá trị', value: '面对选择，人们往往会权衡利弊。' },
      { label: 'Đồng cảm', value: '理解他人有助于减少矛盾。' },
      { label: 'Lợi ích cá nhân - tập thể', value: '个人利益应与集体利益相协调。' },
    ],
  },
  {
    id: 'environment-society',
    title: 'Môi trường dưới góc nhìn xã hội',
    grade: 'Chung',
    area: 'Môi trường',
    chinese: '环境与社会',
    summary: 'Mẫu câu về bảo vệ môi trường, phát triển bền vững, trách nhiệm xã hội và hành vi tiêu dùng xanh.',
    keywords: ['moi truong', 'xa hoi', 'ben vung', '环境', '可持续', '责任'],
    formulas: [
      { label: 'Vấn đề môi trường', value: '环境问题已经成为全球关注的焦点。' },
      { label: 'Nguyên nhân xã hội', value: 'A 问题与人们的生活方式密切相关。' },
      { label: 'Ý thức bảo vệ', value: '提高环保意识是解决问题的第一步。' },
      { label: 'Hành động cá nhân', value: '个人可以从小事做起，减少资源浪费。' },
      { label: 'Trách nhiệm doanh nghiệp', value: '企业应承担环境保护责任。' },
      { label: 'Chính phủ', value: '政府需要制定有效政策，引导绿色发展。' },
      { label: 'Tiêu dùng xanh', value: '绿色消费正在成为新的生活方式。' },
      { label: 'Phát triển bền vững', value: '可持续发展强调经济、社会与环境的平衡。' },
      { label: 'Hậu quả', value: '如果不及时治理，A 将带来严重后果。' },
      { label: 'Giải pháp tổng hợp', value: '解决环境问题需要社会各方面共同努力。' },
    ],
  },
  {
    id: 'exam-question-social',
    title: 'Cụm hỏi trong đề XH',
    grade: 'Chung',
    area: 'Làm đề',
    chinese: '社科题干关键词',
    summary: 'Cụm câu hỏi thường gặp khi đề hỏi ý chính, thái độ, lập luận, suy luận và chi tiết xã hội.',
    keywords: ['cau hoi', 'de thi', 'xa hoi', '题干', '态度', '推断'],
    formulas: [
      { label: 'Ý chính', value: '这篇文章主要讨论的是 A。' },
      { label: 'Mục đích tác giả', value: '作者写这篇文章的目的是 A。' },
      { label: 'Thái độ', value: '作者对 A 的态度是支持 / 反对 / 客观。' },
      { label: 'Hàm ý', value: '这句话暗示了 A。' },
      { label: 'Suy luận', value: '根据文章，可以推断出 A。' },
      { label: 'Không phù hợp', value: '下列说法不符合原文的是 A。' },
      { label: 'Luận cứ', value: '作者用 A 来证明 B。' },
      { label: 'Từ thay thế', value: '文中的 “其 / 这 / 这种现象” 指的是 A。' },
      { label: 'Tiêu đề phù hợp', value: '最适合本文的标题是 A。' },
      { label: 'Điền câu', value: '填入横线处最恰当的一项是 A。' },
    ],
    notes: ['Gặp 客观 nghĩa là tác giả trình bày trung lập, không nhất thiết khen hay chê.'],
  },
  {
    id: 'social-translation-templates',
    title: 'Mẫu dịch Việt - Trung xã hội tự nhiên',
    grade: 'Chung',
    area: 'Dịch câu',
    chinese: '社科自然表达',
    summary: 'Khung dịch giúp viết câu xã hội tự nhiên hơn khi gặp đề dịch, điền câu hoặc viết ngắn.',
    keywords: ['dich', 'viet trung', 'xa hoi', '翻译', '自然表达'],
    formulas: [
      { label: 'Được quan tâm rộng rãi', value: 'A 受到广泛关注。' },
      { label: 'Đóng vai trò không thể thay thế', value: 'A 发挥着不可替代的作用。' },
      { label: 'Có lợi cho', value: 'A 有利于 B。' },
      { label: 'Không có lợi cho', value: 'A 不利于 B。' },
      { label: 'Trên thực tế', value: '事实上，A。' },
      { label: 'Ở mức độ nào đó', value: '在一定程度上，A。' },
      { label: 'Xét từ góc độ...', value: '从 A 的角度来看，B。' },
      { label: 'Không thể phủ nhận', value: '不可否认，A。' },
      { label: 'Điều đáng chú ý là', value: '值得注意的是，A。' },
      { label: 'Vẫn cần', value: 'A 仍然需要进一步完善。' },
    ],
  },
  {
    id: 'logic-connectors-social',
    title: 'Từ nối xã hội - nghị luận',
    grade: 'Chung',
    area: 'Liên kết',
    chinese: '社科连接词',
    summary: 'Liên từ tự nhiên trong bài xã hội: bổ sung, đối lập, nhân quả, nhượng bộ, chuyển ý và kết luận.',
    keywords: ['lien tu', 'nghi luan', 'logic', '连接词', '转折', '递进'],
    formulas: [
      { label: 'Bổ sung', value: '此外 / 另外 / 同时，A。' },
      { label: 'Tăng tiến', value: '更重要的是，A。' },
      { label: 'Đối lập', value: '然而 / 但是 / 不过，A。' },
      { label: 'Nhượng bộ', value: '尽管 A，B 仍然 C。' },
      { label: 'Nguyên nhân', value: '之所以 A，是因为 B。' },
      { label: 'Kết quả', value: '因此 / 因而 / 由此，A。' },
      { label: 'Chuyển góc nhìn', value: '从另一个角度看，A。' },
      { label: 'Liệt kê hai mặt', value: '一方面 A，另一方面 B。' },
      { label: 'Ví dụ', value: '例如 / 以 A 为例，B。' },
      { label: 'Kết lại', value: '综上所述，A。' },
    ],
  },
];

export const CHINESE_SOCIAL_FORMULA_GRADE_OPTIONS: ChineseSocialFormulaGrade[] = ['Chung'];

export const CHINESE_SOCIAL_FORMULA_AREAS = Array.from(
  new Set(CHINESE_SOCIAL_CSCA_FORMULA_TOPICS.map(topic => topic.area)),
);
