export type ChineseNaturalFormulaGrade = 'Chung';

export interface ChineseNaturalFormulaLine {
  label: string;
  value: string;
  note?: string;
}

export interface ChineseNaturalCscaFormulaTopic {
  id: string;
  title: string;
  grade: ChineseNaturalFormulaGrade;
  area: string;
  chinese?: string;
  summary: string;
  keywords: string[];
  formulas: ChineseNaturalFormulaLine[];
  notes?: string[];
}

export const CHINESE_NATURAL_CSCA_FORMULA_TOPICS: ChineseNaturalCscaFormulaTopic[] = [
  {
    id: 'science-reading-signals',
    title: 'Tín hiệu đọc hiểu bài khoa học tự nhiên',
    grade: 'Chung',
    area: 'Đọc hiểu TN',
    chinese: '自然科学说明文',
    summary: 'Các cụm mở bài, định nghĩa, phân loại, chức năng và kết luận hay gặp trong bài đọc tự nhiên.',
    keywords: ['doc hieu', 'khoa hoc tu nhien', '说明文', '定义', '分类', '功能'],
    formulas: [
      { label: 'Định nghĩa', value: '所谓 A，是指 B。', note: 'Dịch nhanh: Cái gọi là A tức là B.' },
      { label: 'Nói cách khác', value: '换句话说，A 就是 B。', note: 'Dùng khi đề diễn giải lại khái niệm.' },
      { label: 'Bản chất', value: 'A 的本质是 B。', note: 'Hay dùng trong câu hỏi “本质/根本原因”.' },
      { label: 'Đặc điểm', value: 'A 具有 B、C 等特点。', note: 'Nắm các từ sau 具有 để chọn ý đúng.' },
      { label: 'Chức năng', value: 'A 的作用是 B。 / A 起到 B 的作用。' },
      { label: 'Cấu tạo', value: 'A 由 B 和 C 组成。 / A 包括 B、C、D。' },
      { label: 'Phân loại', value: '根据 A 的不同，可以把 B 分为 C 和 D。' },
      { label: 'Ví dụ', value: '例如 / 比如 / 以 A 为例，B。', note: 'Ví dụ thường minh họa ý ngay trước nó.' },
      { label: 'Kết luận', value: '由此可见，A 与 B 密切相关。' },
      { label: 'Tóm lại', value: '总之 / 综上所述，A。' },
    ],
    notes: ['Khi đọc bài dài, khoanh các từ 所谓、作用、组成、根据、由此可见 trước.'],
  },
  {
    id: 'cause-effect-condition',
    title: 'Nguyên nhân, kết quả, điều kiện và mục đích',
    grade: 'Chung',
    area: 'Logic câu',
    chinese: '因果、条件、目的',
    summary: 'Mẫu câu giúp nhận ra vì sao xảy ra hiện tượng, điều kiện áp dụng và mục đích thí nghiệm.',
    keywords: ['nguyen nhan', 'ket qua', 'dieu kien', 'muc dich', '因为', '由于', '条件'],
    formulas: [
      { label: 'Vì... nên...', value: '因为 A，所以 B。', note: '口语, dễ gặp trong lời giải thích ngắn.' },
      { label: 'Do... nên...', value: '由于 A，B。', note: '书面语, tự nhiên hơn trong bài đọc khoa học.' },
      { label: 'Nguyên nhân chính', value: 'A 是导致 B 的主要原因。' },
      { label: 'Dẫn đến', value: 'A 会导致 / 引起 / 造成 B。', note: '导致 thường trung tính, 造成 hay nghiêng về hậu quả xấu.' },
      { label: 'Vì vậy', value: '因此 / 因而 / 所以，B。' },
      { label: 'Nếu... thì...', value: '如果 A，就 B。 / 若 A，则 B。', note: '若...则... trang trọng, hay gặp trong đề.' },
      { label: 'Chỉ cần... là...', value: '只要 A，就 B。', note: 'Điều kiện đủ.' },
      { label: 'Chỉ khi... mới...', value: '只有 A，才 B。', note: 'Điều kiện cần, rất hay bẫy đáp án.' },
      { label: 'Trừ khi...', value: '除非 A，否则 B。' },
      { label: 'Mục đích', value: '为了 A，需要 / 可以 B。' },
    ],
  },
  {
    id: 'comparison-quantity-change',
    title: 'So sánh, số liệu, tỉ lệ và thay đổi',
    grade: 'Chung',
    area: 'Số liệu',
    chinese: '比较、数量、变化',
    summary: 'Các mẫu so sánh và biến thiên hay xuất hiện trong đoạn có biểu đồ, thí nghiệm, dân số, môi trường.',
    keywords: ['so sanh', 'so lieu', 'ti le', 'phan tram', '比较', '倍数', '增加'],
    formulas: [
      { label: 'So sánh hơn', value: 'A 比 B 更 / 还 / 要 C。', note: 'Tính chất C đứng cuối câu.' },
      { label: 'Kém hơn', value: 'A 不如 B C。 / A 没有 B C。' },
      { label: 'Bằng nhau', value: 'A 和 B 一样 C。' },
      { label: 'Khác nhau', value: 'A 与 B 不同，主要体现在 C。' },
      { label: 'Tăng', value: 'A 增加 / 上升 / 提高 到 B。' },
      { label: 'Giảm', value: 'A 减少 / 下降 / 降低 到 B。' },
      { label: 'Tăng thêm bao nhiêu', value: 'A 增加了 B。', note: '了 + số lượng = mức tăng.' },
      { label: 'Tăng đến mức nào', value: 'A 增加到 B。', note: '到 + số lượng = kết quả cuối.' },
      { label: 'Gấp mấy lần', value: 'A 是 B 的 N 倍。 / A 比 B 多 N 倍。' },
      { label: 'Chiếm tỉ lệ', value: 'A 占 B 的 N%。' },
      { label: 'Tỉ lệ thuận', value: 'A 与 B 成正比。' },
      { label: 'Tỉ lệ nghịch', value: 'A 与 B 成反比。' },
    ],
    notes: ['Phân biệt 增加了 và 增加到: một bên là mức tăng, một bên là giá trị sau cùng.'],
  },
  {
    id: 'experiment-process',
    title: 'Thí nghiệm, thao tác và quy trình',
    grade: 'Chung',
    area: 'Thí nghiệm',
    chinese: '实验过程',
    summary: 'Mẫu câu mô tả mục đích, biến số, thao tác, quan sát và kết luận thí nghiệm.',
    keywords: ['thi nghiem', 'quy trinh', 'bien so', 'quan sat', '实验', '观察', '变量'],
    formulas: [
      { label: 'Mục đích thí nghiệm', value: '本实验的目的是研究 A 对 B 的影响。' },
      { label: 'Đối tượng nghiên cứu', value: '以 A 为研究对象，观察 B 的变化。' },
      { label: 'Biến độc lập', value: '改变 A，保持 B 不变。' },
      { label: 'Biến phụ thuộc', value: '测量 / 记录 B 的变化。' },
      { label: 'Nhóm đối chứng', value: '设置对照组，以排除其他因素的影响。' },
      { label: 'Thao tác', value: '先 A，然后 B，最后 C。' },
      { label: 'Hiện tượng quan sát', value: '可以观察到 A 出现 / 消失 / 变为 B。' },
      { label: 'Kết quả cho thấy', value: '实验结果表明，A 会影响 B。' },
      { label: 'Sai số', value: '误差可能来自 A、B 或 C。' },
      { label: 'Kiểm chứng', value: '为了验证 A，需要重复实验。' },
    ],
  },
  {
    id: 'nature-phenomena',
    title: 'Mô tả hiện tượng tự nhiên',
    grade: 'Chung',
    area: 'Hiện tượng',
    chinese: '自然现象',
    summary: 'Mẫu câu mô tả sự hình thành, biến đổi, chu kỳ và ảnh hưởng của hiện tượng tự nhiên.',
    keywords: ['hien tuong tu nhien', 'hinh thanh', 'anh huong', '自然现象', '形成', '影响'],
    formulas: [
      { label: 'Hình thành', value: 'A 是在 B 条件下形成的。' },
      { label: 'Quá trình', value: 'A 的形成过程包括 B、C 和 D。' },
      { label: 'Biến đổi', value: '随着 A 的变化，B 也会发生变化。' },
      { label: 'Chu kỳ', value: 'A 呈现周期性变化。' },
      { label: 'Phân bố', value: 'A 主要分布在 B 地区 / 环境中。' },
      { label: 'Nguồn gốc', value: 'A 来源于 B。 / A 由 B 演化而来。' },
      { label: 'Ảnh hưởng tích cực', value: 'A 有利于 B。 / A 对 B 有促进作用。' },
      { label: 'Ảnh hưởng tiêu cực', value: 'A 不利于 B。 / A 对 B 产生不良影响。' },
      { label: 'Mối quan hệ', value: 'A 与 B 相互作用 / 相互影响。' },
      { label: 'Điểm mấu chốt', value: '关键在于 A 是否满足 B 条件。' },
    ],
  },
  {
    id: 'biology-ecology',
    title: 'Sinh học, môi trường và sinh thái',
    grade: 'Chung',
    area: 'Sinh thái',
    chinese: '生物与生态',
    summary: 'Cụm tự nhiên để đọc bài về cơ thể sống, quần thể, môi trường, chuỗi thức ăn và bảo vệ sinh thái.',
    keywords: ['sinh hoc', 'moi truong', 'sinh thai', '生物', '生态', '环境'],
    formulas: [
      { label: 'Thích nghi', value: 'A 适应 B 环境。 / A 具有适应 B 的能力。' },
      { label: 'Sinh trưởng', value: 'A 的生长受 B、C 等因素影响。' },
      { label: 'Sinh sản', value: 'A 通过 B 方式繁殖。' },
      { label: 'Trao đổi chất', value: 'A 通过 B 获得能量 / 物质。' },
      { label: 'Chuỗi thức ăn', value: 'A 以 B 为食，C 又以 A 为食。' },
      { label: 'Cân bằng sinh thái', value: 'A 有助于维持生态平衡。' },
      { label: 'Ô nhiễm', value: 'A 污染会破坏 B，进而影响 C。' },
      { label: 'Bảo vệ môi trường', value: '应采取 A 措施，减少 B 对环境的影响。' },
      { label: 'Đa dạng sinh học', value: '保护 A 有利于保持生物多样性。' },
      { label: 'Quan hệ cạnh tranh', value: 'A 和 B 之间存在竞争关系。' },
    ],
  },
  {
    id: 'physics-chemistry-reading',
    title: 'Từ vựng diễn đạt Lý - Hóa trong bài tiếng Trung',
    grade: 'Chung',
    area: 'Khoa học',
    chinese: '物理化学表达',
    summary: 'Mẫu câu hay dùng để mô tả lực, năng lượng, phản ứng, dung dịch, nhiệt độ, áp suất trong bài đọc TN.',
    keywords: ['vat ly', 'hoa hoc', 'khoa hoc', '物理', '化学', '反应'],
    formulas: [
      { label: 'Tác dụng lực', value: 'A 对 B 施加力，使 B 发生变化。' },
      { label: 'Năng lượng chuyển hóa', value: 'A 能量转化为 B 能量。' },
      { label: 'Nhiệt độ ảnh hưởng', value: '温度升高会使 A 加快 / 增强。' },
      { label: 'Áp suất ảnh hưởng', value: '压力增大时，A 会发生明显变化。' },
      { label: 'Phản ứng hóa học', value: 'A 与 B 发生反应，生成 C。' },
      { label: 'Điều kiện phản ứng', value: '在 A 条件下，B 可以转化为 C。' },
      { label: 'Dung dịch', value: 'A 溶于 B，形成 C 溶液。' },
      { label: 'Nồng độ', value: 'A 的浓度越高，B 越明显。' },
      { label: 'Chất xúc tác', value: 'A 能加快反应速率，但本身不被消耗。' },
      { label: 'Bảo toàn', value: '反应前后，A 的总量保持不变。' },
    ],
  },
  {
    id: 'data-chart-reading',
    title: 'Đọc biểu đồ, bảng số liệu và mô tả xu hướng',
    grade: 'Chung',
    area: 'Số liệu',
    chinese: '图表与数据',
    summary: 'Mẫu câu dùng khi đề cho bảng, biểu đồ, hình vẽ hoặc đoạn thống kê.',
    keywords: ['bieu do', 'bang so lieu', 'xu huong', '图表', '数据', '趋势'],
    formulas: [
      { label: 'Theo biểu đồ', value: '从图表可以看出，A 呈现 B 趋势。' },
      { label: 'Nhìn chung', value: '总体来看，A 逐渐增加 / 减少。' },
      { label: 'Đạt cao nhất', value: 'A 在 B 时达到最高值。' },
      { label: 'Đạt thấp nhất', value: 'A 在 B 时降至最低值。' },
      { label: 'Ổn định', value: 'A 基本保持稳定。' },
      { label: 'Dao động', value: 'A 在 B 和 C 之间波动。' },
      { label: 'Tăng nhanh', value: 'A 快速上升，随后趋于平稳。' },
      { label: 'Giảm dần', value: 'A 逐渐下降，说明 B。' },
      { label: 'So với năm trước', value: '与上一阶段相比，A 有明显变化。' },
      { label: 'Suy luận từ dữ liệu', value: '这些数据说明，A 与 B 之间存在一定关系。' },
    ],
  },
  {
    id: 'grammar-core-patterns',
    title: 'Ngữ pháp trọng tâm hay gặp trong đề TN',
    grade: 'Chung',
    area: 'Ngữ pháp',
    chinese: '核心语法',
    summary: 'Các cấu trúc xử lý tân ngữ, bị động, nhấn mạnh, trạng thái và kinh nghiệm.',
    keywords: ['ngu phap', 'ba', 'bei', 'le', 'zhe', 'guo', '把', '被'],
    formulas: [
      { label: '把字句', value: '主语 + 把 + 宾语 + 动词 + 结果。', note: 'Nhấn mạnh xử lý đối tượng và kết quả.' },
      { label: '被字句', value: '宾语 + 被 + 施事 + 动词 + 结果。', note: 'Bị động, hay gặp khi mô tả vật bị tác động.' },
      { label: '使/让/令', value: 'A 使 / 让 / 令 B 发生变化。' },
      { label: '是...的', value: 'A 是在 B 条件下发生的。', note: 'Nhấn mạnh thời gian, nơi chốn, cách thức, điều kiện.' },
      { label: '正在', value: 'A 正在进行 / 发生。' },
      { label: '着', value: 'A 保持着 B 状态。' },
      { label: '了', value: 'A 发生了明显变化。' },
      { label: '过', value: 'A 曾经出现过 B 现象。' },
      { label: '越...越...', value: 'A 越高，B 越明显。' },
      { label: '既...又...', value: 'A 既能 B，又能 C。' },
    ],
  },
  {
    id: 'logic-connectors',
    title: 'Liên từ và mạch lập luận tự nhiên',
    grade: 'Chung',
    area: 'Liên kết',
    chinese: '连接词',
    summary: 'Từ nối giúp nhận ra quan hệ giữa các câu: thêm ý, đối lập, chuyển hướng, ví dụ, tổng kết.',
    keywords: ['lien tu', 'mach van', 'doc hieu', '连接词', '转折', '递进'],
    formulas: [
      { label: 'Liệt kê', value: '首先 A，其次 B，最后 C。' },
      { label: 'Đồng thời', value: '与此同时，A 也 B。' },
      { label: 'Hơn nữa', value: '此外 / 另外 / 而且，A。' },
      { label: 'Không những... mà còn...', value: 'A 不但 B，而且 C。' },
      { label: 'Tuy... nhưng...', value: '虽然 A，但是 B。' },
      { label: 'Tuy nhiên', value: '然而 / 但是 / 不过，B。' },
      { label: 'Ngược lại', value: '相反，A 并不 B。' },
      { label: 'Thay vì', value: '与其 A，不如 B。' },
      { label: 'Một mặt... mặt khác...', value: '一方面 A，另一方面 B。' },
      { label: 'Tổng kết', value: '总的来说，A。' },
    ],
  },
  {
    id: 'exam-question-phrases',
    title: 'Cụm hỏi trong đề và cách nhận đáp án',
    grade: 'Chung',
    area: 'Làm đề',
    chinese: '题干关键词',
    summary: 'Các cụm trong câu hỏi CSCA/đề đọc hiểu, giúp biết đề hỏi ý chính, chi tiết, suy luận hay thái độ.',
    keywords: ['lam de', 'cau hoi', 'dap an', '题干', '正确', '推断'],
    formulas: [
      { label: 'Ý chính', value: '本文主要讲的是 A。 / 文章的中心意思是 A。' },
      { label: 'Chi tiết đúng', value: '根据文章，下列说法正确的是 A。' },
      { label: 'Chi tiết sai', value: '下列说法不符合原文的是 A。' },
      { label: 'Nguyên nhân', value: '造成 A 的原因是 B。' },
      { label: 'Mục đích', value: '作者提到 A，是为了说明 B。' },
      { label: 'Suy luận', value: '由此可以推断，A。' },
      { label: 'Thái độ', value: '作者对 A 的态度是 B。' },
      { label: 'Từ thay thế', value: '文中 “这/其/该” 指的是 A。' },
      { label: 'Sắp xếp trình tự', value: 'A、B、C 的正确顺序是 D。' },
      { label: 'Điền từ', value: '填入空白处最恰当的是 A。' },
    ],
    notes: ['Gặp 不符合、不是、错误 nhớ gạch chân trước khi chọn đáp án.'],
  },
  {
    id: 'natural-translation-templates',
    title: 'Mẫu dịch Việt - Trung tự nhiên cho bài TN',
    grade: 'Chung',
    area: 'Dịch câu',
    chinese: '自然表达',
    summary: 'Các khung dịch giúp câu Trung nghe tự nhiên, không bị dịch word-by-word từ tiếng Việt.',
    keywords: ['dich cau', 'tu nhien', 'viet trung', '翻译', '自然表达'],
    formulas: [
      { label: 'Có thể thấy rằng', value: '可以看出，A。', note: 'Không dịch máy thành 可以看到那个.' },
      { label: 'Cho thấy', value: 'A 表明 / 说明 B。' },
      { label: 'Có liên quan đến', value: 'A 与 B 有关。 / A 和 B 密切相关。' },
      { label: 'Phụ thuộc vào', value: 'A 取决于 B。' },
      { label: 'Bị ảnh hưởng bởi', value: 'A 受到 B 的影响。' },
      { label: 'Đóng vai trò quan trọng', value: 'A 在 B 中起重要作用。' },
      { label: 'Không thể bỏ qua', value: 'A 不容忽视。' },
      { label: 'Ngày càng', value: 'A 越来越 B。' },
      { label: 'Ở một mức độ nào đó', value: '在一定程度上，A。' },
      { label: 'Cần chú ý rằng', value: '需要注意的是，A。' },
    ],
  },
];

export const CHINESE_NATURAL_FORMULA_GRADE_OPTIONS: ChineseNaturalFormulaGrade[] = ['Chung'];

export const CHINESE_NATURAL_FORMULA_AREAS = Array.from(
  new Set(CHINESE_NATURAL_CSCA_FORMULA_TOPICS.map(topic => topic.area)),
);
