export type MathFormulaGrade = '10' | '11' | '12' | 'Chung';
export type MathFormulaIllustration = 'polyhedra' | 'round-solids' | 'spatial-relations' | 'oxyz';

export interface MathFormulaLine {
  label: string;
  value: string;
  note?: string;
}

export interface MathCscaFormulaTopic {
  id: string;
  title: string;
  grade: MathFormulaGrade;
  area: string;
  chinese?: string;
  summary: string;
  keywords: string[];
  formulas: MathFormulaLine[];
  notes?: string[];
  illustration?: MathFormulaIllustration;
}

const m = String.raw;

export const MATH_CSCA_FORMULA_TOPICS: MathCscaFormulaTopic[] = [
  {
    id: 'sets-logic-intervals',
    title: 'Tập hợp, mệnh đề, khoảng số',
    grade: '10',
    area: 'Nền tảng',
    chinese: '集合、命题、区间',
    summary: 'Ký hiệu tập hợp, phủ định mệnh đề, giao hợp hiệu, khoảng nghiệm trên trục số.',
    keywords: ['tap hop', 'menh de', 'khoang', 'giao hop', '集合', '命题', '区间'],
    formulas: [
      { label: 'Hợp', value: m`\(x\in A\cup B\Leftrightarrow x\in A\ \text{hoặc}\ x\in B\)` },
      { label: 'Giao', value: m`\(x\in A\cap B\Leftrightarrow x\in A\ \text{và}\ x\in B\)` },
      { label: 'Hiệu', value: m`\(x\in A\setminus B\Leftrightarrow x\in A,\ x\notin B\)` },
      { label: 'Phần bù', value: m`\(C_EA=E\setminus A\)` },
      { label: 'De Morgan', value: m`\(\overline{A\cup B}=\overline A\cap\overline B,\quad \overline{A\cap B}=\overline A\cup\overline B\)` },
      { label: 'Phủ định kéo theo', value: m`\(\overline{P\Rightarrow Q}=P\land \overline Q\)` },
      { label: 'Khoảng mở', value: m`\(x\in(a,b)\Leftrightarrow a<x<b\)` },
      { label: 'Nửa khoảng', value: m`\(x\in[a,b)\Leftrightarrow a\le x<b\)` },
    ],
    notes: ['Khi giải bất phương trình có nhiều điều kiện, kết quả cuối lấy giao tất cả khoảng nghiệm.'],
  },
  {
    id: 'algebra-identities-factorization',
    title: 'Hằng đẳng thức và phân tích nhân tử',
    grade: '10',
    area: 'Đại số',
    chinese: '代数恒等式、因式分解',
    summary: 'Bộ biến đổi đa thức, phân thức, căn thức, dùng nhiều trong rút gọn và giải phương trình.',
    keywords: ['hang dang thuc', 'phan tich nhan tu', 'factor', 'dai so', '恒等式', '因式分解'],
    formulas: [
      { label: 'Bình phương tổng', value: m`\((a+b)^2=a^2+2ab+b^2\)` },
      { label: 'Bình phương hiệu', value: m`\((a-b)^2=a^2-2ab+b^2\)` },
      { label: 'Hiệu hai bình phương', value: m`\(a^2-b^2=(a-b)(a+b)\)` },
      { label: 'Lập phương tổng', value: m`\((a+b)^3=a^3+3a^2b+3ab^2+b^3\)` },
      { label: 'Lập phương hiệu', value: m`\((a-b)^3=a^3-3a^2b+3ab^2-b^3\)` },
      { label: 'Tổng hai lập phương', value: m`\(a^3+b^3=(a+b)(a^2-ab+b^2)\)` },
      { label: 'Hiệu hai lập phương', value: m`\(a^3-b^3=(a-b)(a^2+ab+b^2)\)` },
      { label: 'Tổng bình phương', value: m`\(a^2+b^2=(a+b)^2-2ab=(a-b)^2+2ab\)` },
      { label: 'Tách nhóm', value: m`\(ax+ay+bx+by=(a+b)(x+y)\)` },
    ],
    notes: ['Đưa về nhân tử trước khi rút gọn phân thức hoặc chia đa thức.'],
  },
  {
    id: 'powers-roots-log-laws',
    title: 'Lũy thừa, căn thức, logarit',
    grade: 'Chung',
    area: 'Đại số',
    chinese: '幂、根式、对数',
    summary: 'Luật mũ, căn, log. Nền cho hàm số, phương trình, bất phương trình mũ log.',
    keywords: ['luy thua', 'can thuc', 'logarit', 'log', 'mu', '幂', '根式', '对数'],
    formulas: [
      { label: 'Nhân cùng cơ số', value: m`\(a^m a^n=a^{m+n}\)` },
      { label: 'Chia cùng cơ số', value: m`\(\frac{a^m}{a^n}=a^{m-n}\quad(a\ne0)\)` },
      { label: 'Lũy thừa của lũy thừa', value: m`\((a^m)^n=a^{mn}\)` },
      { label: 'Lũy thừa tích', value: m`\((ab)^n=a^n b^n\)` },
      { label: 'Mũ âm', value: m`\(a^{-n}=\frac{1}{a^n}\quad(a\ne0)\)` },
      { label: 'Mũ hữu tỉ', value: m`\(a^{\frac{m}{n}}=\sqrt[n]{a^m}\quad(a>0)\)` },
      { label: 'Log tích', value: m`\(\log_a(xy)=\log_a x+\log_a y\)` },
      { label: 'Log thương', value: m`\(\log_a\frac{x}{y}=\log_a x-\log_a y\)` },
      { label: 'Log lũy thừa', value: m`\(\log_a x^m=m\log_a x\)` },
      { label: 'Đổi cơ số', value: m`\(\log_a b=\frac{\log_c b}{\log_c a}\)` },
      { label: 'Mũ và log ngược nhau', value: m`\(a^{\log_a x}=x,\quad \log_a a^x=x\)` },
    ],
    notes: [m`Điều kiện logarit: \(a>0,\ a\ne1,\ x>0\).`],
  },
  {
    id: 'equations-systems-basics',
    title: 'Phương trình, hệ phương trình cơ bản',
    grade: '10',
    area: 'Phương trình',
    chinese: '方程、方程组',
    summary: 'Bậc nhất, bậc hai, trùng phương, căn thức, hệ tuyến tính 2 ẩn.',
    keywords: ['phuong trinh', 'he phuong trinh', 'bac hai', 'can thuc', '方程组', '二次方程'],
    formulas: [
      { label: 'Bậc nhất', value: m`\(ax+b=0\Rightarrow x=-\frac{b}{a}\quad(a\ne0)\)` },
      { label: 'Delta', value: m`\(\Delta=b^2-4ac\)` },
      { label: 'Nghiệm bậc hai', value: m`\(x_{1,2}=\frac{-b\pm\sqrt{\Delta}}{2a}\quad(a\ne0)\)` },
      { label: 'Delta phẩy', value: m`\(\Delta'=b'^2-ac,\quad x_{1,2}=\frac{-b'\pm\sqrt{\Delta'}}{a}\)` },
      { label: 'Viète', value: m`\(x_1+x_2=-\frac{b}{a},\quad x_1x_2=\frac{c}{a}\)` },
      { label: 'Trùng phương', value: m`\(ax^4+bx^2+c=0,\ \ t=x^2\ge0\)` },
      { label: 'Căn thức', value: m`\(\sqrt{A}=B\Leftrightarrow B\ge0,\ A=B^2\)` },
      { label: 'Hệ 2 ẩn', value: m`\(\begin{cases}a_1x+b_1y=c_1\\a_2x+b_2y=c_2\end{cases}\)` },
      { label: 'Cramer 2 ẩn', value: m`\(D=a_1b_2-a_2b_1,\quad x=\frac{c_1b_2-c_2b_1}{D},\quad y=\frac{a_1c_2-a_2c_1}{D}\)` },
    ],
    notes: ['Với phương trình căn hoặc bình phương hai vế, luôn thử lại nghiệm.'],
  },
  {
    id: 'inequalities-absolute-value',
    title: 'Bất đẳng thức, bất phương trình, trị tuyệt đối',
    grade: '10',
    area: 'Bất đẳng thức',
    chinese: '不等式、绝对值',
    summary: 'Dạng đánh giá, khoảng nghiệm, min max, điều kiện khi biến đổi bất phương trình.',
    keywords: ['bat dang thuc', 'bat phuong trinh', 'tri tuyet doi', 'min max', '绝对值', '不等式'],
    formulas: [
      { label: 'Trị tuyệt đối', value: m`\( |x|=\begin{cases}x,&x\ge0\\-x,&x<0\end{cases}\)` },
      { label: 'Khoảng trị tuyệt đối', value: m`\( |x-a|<r\Leftrightarrow a-r<x<a+r\quad(r>0)\)` },
      { label: 'Ngoài khoảng', value: m`\( |x-a|>r\Leftrightarrow x<a-r\ \text{hoặc}\ x>a+r\)` },
      { label: 'Tam giác', value: m`\( |a+b|\le |a|+|b|,\quad ||a|-|b||\le |a-b|\)` },
      { label: 'Bình phương không âm', value: m`\((a-b)^2\ge0\Rightarrow a^2+b^2\ge2ab\)` },
      { label: 'AM-GM', value: m`\(\frac{x_1+\cdots+x_n}{n}\ge\sqrt[n]{x_1x_2\cdots x_n}\quad(x_i\ge0)\)` },
      { label: 'Cauchy Schwarz', value: m`\((a_1^2+\cdots+a_n^2)(b_1^2+\cdots+b_n^2)\ge(a_1b_1+\cdots+a_nb_n)^2\)` },
      { label: 'Cauchy Engel', value: m`\(\frac{x_1^2}{a_1}+\cdots+\frac{x_n^2}{a_n}\ge\frac{(x_1+\cdots+x_n)^2}{a_1+\cdots+a_n}\quad(a_i>0)\)` },
      { label: 'Nhân chia bất phương trình', value: m`\(a>b,\ c>0\Rightarrow ac>bc;\quad c<0\Rightarrow ac<bc\)` },
    ],
    notes: ['Khi nhân với biểu thức chứa biến, phải xét dấu biểu thức đó.'],
  },
  {
    id: 'functions-domain-graphs',
    title: 'Hàm số, tập xác định, đồ thị',
    grade: '10',
    area: 'Hàm số',
    chinese: '函数、定义域、图像',
    summary: 'Điều kiện xác định, tính chẵn lẻ, tịnh tiến đồ thị, giao điểm.',
    keywords: ['ham so', 'tap xac dinh', 'do thi', 'chan le', '定义域', '函数图像'],
    formulas: [
      { label: 'Mẫu số', value: m`\(\frac{A(x)}{B(x)}\ \text{xác định khi}\ B(x)\ne0\)` },
      { label: 'Căn bậc chẵn', value: m`\(\sqrt{A(x)}\ \text{xác định khi}\ A(x)\ge0\)` },
      { label: 'Logarit', value: m`\(\log_a A(x)\ \text{xác định khi}\ A(x)>0,\ a>0,\ a\ne1\)` },
      { label: 'Hàm chẵn', value: m`\(f(-x)=f(x)\)` },
      { label: 'Hàm lẻ', value: m`\(f(-x)=-f(x)\)` },
      { label: 'Dịch ngang', value: m`\(y=f(x-a)\ \text{dịch đồ thị sang phải}\ a\)` },
      { label: 'Dịch dọc', value: m`\(y=f(x)+b\ \text{dịch đồ thị lên}\ b\)` },
      { label: 'Giao điểm', value: m`\(\text{Giao của }y=f(x),y=g(x)\text{ là nghiệm }f(x)=g(x)\)` },
    ],
    notes: ['Nhiều điều kiện xác định thì lấy giao tất cả điều kiện.'],
  },
  {
    id: 'linear-quadratic-functions',
    title: 'Hàm bậc nhất, bậc hai',
    grade: '10',
    area: 'Hàm số',
    chinese: '一次函数、二次函数',
    summary: 'Đường thẳng, parabol, đỉnh, trục đối xứng, dấu tam thức.',
    keywords: ['ham bac nhat', 'ham bac hai', 'parabol', 'tam thuc', '一次函数', '二次函数'],
    formulas: [
      { label: 'Bậc nhất', value: m`\(y=ax+b\quad(a\ne0)\)` },
      { label: 'Hệ số góc', value: m`\(a=\tan\alpha\)`, note: m`\(\alpha\) là góc tạo với chiều dương trục Ox.` },
      { label: 'Song song', value: m`\(y=a_1x+b_1\parallel y=a_2x+b_2\Leftrightarrow a_1=a_2,\ b_1\ne b_2\)` },
      { label: 'Vuông góc', value: m`\(d_1\perp d_2\Leftrightarrow a_1a_2=-1\)` },
      { label: 'Parabol', value: m`\(y=ax^2+bx+c\quad(a\ne0)\)` },
      { label: 'Đỉnh', value: m`\(I\left(-\frac{b}{2a},-\frac{\Delta}{4a}\right)\)` },
      { label: 'Trục đối xứng', value: m`\(x=-\frac{b}{2a}\)` },
      { label: 'Dấu tam thức', value: m`\(ax^2+bx+c\) cùng dấu \(a\) ngoài hai nghiệm, trái dấu \(a\) trong khoảng hai nghiệm.` },
      { label: 'Min max parabol', value: m`\(a>0\Rightarrow y_{\min}=-\frac{\Delta}{4a};\quad a<0\Rightarrow y_{\max}=-\frac{\Delta}{4a}\)` },
    ],
  },
  {
    id: 'trigonometry-identities',
    title: 'Lượng giác cơ bản',
    grade: '10',
    area: 'Lượng giác',
    chinese: '三角函数恒等式',
    summary: 'Đẳng thức lượng giác, công thức cộng, nhân đôi, hạ bậc, biến đổi tổng tích.',
    keywords: ['luong giac', 'sin cos tan cot', 'cong thuc cong', '三角函数'],
    formulas: [
      { label: 'Hệ thức cơ bản', value: m`\(\sin^2x+\cos^2x=1\)` },
      { label: 'Tan cot', value: m`\(\tan x=\frac{\sin x}{\cos x},\quad \cot x=\frac{\cos x}{\sin x},\quad \tan x\cot x=1\)` },
      { label: 'Sin tổng', value: m`\(\sin(a+b)=\sin a\cos b+\cos a\sin b\)` },
      { label: 'Sin hiệu', value: m`\(\sin(a-b)=\sin a\cos b-\cos a\sin b\)` },
      { label: 'Cos tổng', value: m`\(\cos(a+b)=\cos a\cos b-\sin a\sin b\)` },
      { label: 'Cos hiệu', value: m`\(\cos(a-b)=\cos a\cos b+\sin a\sin b\)` },
      { label: 'Tan tổng', value: m`\(\tan(a+b)=\frac{\tan a+\tan b}{1-\tan a\tan b}\)` },
      { label: 'Tan hiệu', value: m`\(\tan(a-b)=\frac{\tan a-\tan b}{1+\tan a\tan b}\)` },
      { label: 'Nhân đôi sin', value: m`\(\sin2x=2\sin x\cos x\)` },
      { label: 'Nhân đôi cos', value: m`\(\cos2x=\cos^2x-\sin^2x=2\cos^2x-1=1-2\sin^2x\)` },
      { label: 'Nhân đôi tan', value: m`\(\tan2x=\frac{2\tan x}{1-\tan^2x}\)` },
      { label: 'Hạ bậc', value: m`\(\sin^2x=\frac{1-\cos2x}{2},\quad \cos^2x=\frac{1+\cos2x}{2}\)` },
      { label: 'Tích thành tổng', value: m`\(\sin a\sin b=\frac{\cos(a-b)-\cos(a+b)}2\)` },
      { label: 'Tổng thành tích', value: m`\(\sin a+\sin b=2\sin\frac{a+b}{2}\cos\frac{a-b}{2}\)` },
    ],
    notes: [m`Đổi đơn vị: \(180^\circ=\pi\) rad.`],
  },
  {
    id: 'trigonometric-equations',
    title: 'Phương trình lượng giác',
    grade: '11',
    area: 'Lượng giác',
    chinese: '三角方程',
    summary: 'Nghiệm tổng quát, chu kỳ, điều kiện tan cot.',
    keywords: ['phuong trinh luong giac', 'nghiem tong quat', 'chu ky', '三角方程'],
    formulas: [
      { label: 'Sin', value: m`\(\sin x=\sin\alpha\Leftrightarrow x=\alpha+2k\pi\ \text{hoặc}\ x=\pi-\alpha+2k\pi\)` },
      { label: 'Cos', value: m`\(\cos x=\cos\alpha\Leftrightarrow x=\pm\alpha+2k\pi\)` },
      { label: 'Tan', value: m`\(\tan x=\tan\alpha\Leftrightarrow x=\alpha+k\pi\)` },
      { label: 'Cot', value: m`\(\cot x=\cot\alpha\Leftrightarrow x=\alpha+k\pi\)` },
      { label: 'Chu kỳ', value: m`\(T_{\sin}=T_{\cos}=2\pi,\quad T_{\tan}=T_{\cot}=\pi\)` },
      { label: 'Dạng bậc nhất sin cos', value: m`\(a\sin x+b\cos x=c,\quad R=\sqrt{a^2+b^2}\)` },
      { label: 'Điều kiện có nghiệm', value: m`\(a\sin x+b\cos x=c\ \text{có nghiệm khi}\ |c|\le\sqrt{a^2+b^2}\)` },
    ],
    notes: [m`Luôn kiểm tra điều kiện \(\cos x\ne0\) với \(\tan x\), \(\sin x\ne0\) với \(\cot x\).`],
  },
  {
    id: 'triangle-plane-geometry',
    title: 'Tam giác, đường tròn, hình học phẳng',
    grade: 'Chung',
    area: 'Hình học phẳng',
    chinese: '平面几何、三角形、圆',
    summary: 'Diện tích, định lý sin cos, bán kính nội ngoại tiếp, cung quạt tròn.',
    keywords: ['hinh hoc phang', 'tam giac', 'duong tron', 'dien tich', '平面几何', '圆'],
    formulas: [
      { label: 'Diện tích tam giác', value: m`\(S=\frac{1}{2}ah_a=\frac{1}{2}ab\sin C\)` },
      { label: 'Heron', value: m`\(S=\sqrt{p(p-a)(p-b)(p-c)},\quad p=\frac{a+b+c}{2}\)` },
      { label: 'Ngoại tiếp', value: m`\(S=\frac{abc}{4R}\)` },
      { label: 'Nội tiếp', value: m`\(S=pr\)` },
      { label: 'Định lý cos', value: m`\(a^2=b^2+c^2-2bc\cos A\)` },
      { label: 'Định lý sin', value: m`\(\frac{a}{\sin A}=\frac{b}{\sin B}=\frac{c}{\sin C}=2R\)` },
      { label: 'Trung tuyến', value: m`\(m_a^2=\frac{2b^2+2c^2-a^2}{4}\)` },
      { label: 'Đường tròn', value: m`\(C=2\pi R,\quad S=\pi R^2\)` },
      { label: 'Cung tròn', value: m`\(l=R\alpha\)`, note: m`\(\alpha\) tính bằng radian.` },
      { label: 'Quạt tròn', value: m`\(S=\frac{1}{2}R^2\alpha=\frac{1}{2}Rl\)` },
    ],
  },
  {
    id: 'vectors-plane',
    title: 'Vectơ trong mặt phẳng',
    grade: '10',
    area: 'Vectơ',
    chinese: '平面向量',
    summary: 'Tọa độ vectơ, tích vô hướng, cùng phương, vuông góc, phân tích vectơ.',
    keywords: ['vector', 'vecto', 'tich vo huong', 'toa do', '向量'],
    formulas: [
      { label: 'Cộng tọa độ', value: m`\(\vec a=(x_1,y_1),\vec b=(x_2,y_2)\Rightarrow \vec a+\vec b=(x_1+x_2,y_1+y_2)\)` },
      { label: 'Nhân với số', value: m`\(k\vec a=(kx_1,ky_1)\)` },
      { label: 'Độ dài', value: m`\(|\vec a|=\sqrt{x_1^2+y_1^2}\)` },
      { label: 'Tích vô hướng', value: m`\(\vec a\cdot\vec b=x_1x_2+y_1y_2=|\vec a||\vec b|\cos\theta\)` },
      { label: 'Vuông góc', value: m`\(\vec a\perp\vec b\Leftrightarrow \vec a\cdot\vec b=0\)` },
      { label: 'Cùng phương', value: m`\(\vec a\parallel\vec b\Leftrightarrow x_1y_2-x_2y_1=0\)` },
      { label: 'Hình chiếu', value: m`\(\operatorname{proj}_{\vec b}\vec a=\frac{\vec a\cdot\vec b}{|\vec b|^2}\vec b\)` },
      { label: 'Trung điểm', value: m`\(\vec{OM}=\frac{\vec{OA}+\vec{OB}}2\)` },
      { label: 'Trọng tâm', value: m`\(\vec{OG}=\frac{\vec{OA}+\vec{OB}+\vec{OC}}3\)` },
    ],
  },
  {
    id: 'coordinate-plane-line-circle',
    title: 'Tọa độ Oxy, đường thẳng, đường tròn',
    grade: '10',
    area: 'Hình tọa độ',
    chinese: '平面解析几何',
    summary: 'Khoảng cách, trung điểm, trọng tâm, đường thẳng, đường tròn, tiếp tuyến.',
    keywords: ['oxy', 'duong thang', 'duong tron', 'khoang cach', '解析几何'],
    formulas: [
      { label: 'Khoảng cách hai điểm', value: m`\(AB=\sqrt{(x_B-x_A)^2+(y_B-y_A)^2}\)` },
      { label: 'Trung điểm', value: m`\(M\left(\frac{x_A+x_B}{2},\frac{y_A+y_B}{2}\right)\)` },
      { label: 'Trọng tâm', value: m`\(G\left(\frac{x_A+x_B+x_C}{3},\frac{y_A+y_B+y_C}{3}\right)\)` },
      { label: 'Đường thẳng tổng quát', value: m`\(Ax+By+C=0\)` },
      { label: 'Đường thẳng qua điểm có VTPT', value: m`\(A(x-x_0)+B(y-y_0)=0\)` },
      { label: 'Đường thẳng tham số', value: m`\(\begin{cases}x=x_0+at\\y=y_0+bt\end{cases}\)` },
      { label: 'Khoảng cách điểm đường', value: m`\(d(M,\Delta)=\frac{|Ax_M+By_M+C|}{\sqrt{A^2+B^2}}\)` },
      { label: 'Góc hai đường', value: m`\(\cos\varphi=\frac{|A_1A_2+B_1B_2|}{\sqrt{A_1^2+B_1^2}\sqrt{A_2^2+B_2^2}}\)` },
      { label: 'Đường tròn', value: m`\((x-a)^2+(y-b)^2=R^2\)` },
      { label: 'Tiếp tuyến đường tròn', value: m`\((x_0-a)(x-a)+(y_0-b)(y-b)=R^2\)` },
    ],
  },
  {
    id: 'conic-sections',
    title: 'Ba đường conic',
    grade: '10',
    area: 'Hình tọa độ',
    chinese: '圆锥曲线',
    summary: 'Elip, hypebol, parabol ở dạng chính tắc; thường gặp trong đề Trung.',
    keywords: ['conic', 'elip', 'hypebol', 'parabol', '圆锥曲线', '椭圆', '双曲线', '抛物线'],
    formulas: [
      { label: 'Elip chính tắc', value: m`\(\frac{x^2}{a^2}+\frac{y^2}{b^2}=1\quad(a>b>0)\)` },
      { label: 'Elip tiêu cự', value: m`\(c^2=a^2-b^2,\quad F_1(-c,0),F_2(c,0)\)` },
      { label: 'Elip tổng khoảng cách', value: m`\(MF_1+MF_2=2a\)` },
      { label: 'Hypebol chính tắc', value: m`\(\frac{x^2}{a^2}-\frac{y^2}{b^2}=1\)` },
      { label: 'Hypebol tiêu cự', value: m`\(c^2=a^2+b^2\)` },
      { label: 'Tiệm cận hypebol', value: m`\(y=\pm\frac{b}{a}x\)` },
      { label: 'Parabol', value: m`\(y^2=2px\quad(p>0)\)` },
      { label: 'Parabol tiêu điểm', value: m`\(F\left(\frac{p}{2},0\right),\quad \Delta:x=-\frac{p}{2}\)` },
      { label: 'Tâm sai', value: m`\(e=\frac{c}{a}\)`, note: 'Elip có e < 1, hypebol có e > 1.' },
    ],
  },
  {
    id: 'sequences-series',
    title: 'Dãy số, cấp số cộng, cấp số nhân',
    grade: '11',
    area: 'Dãy số',
    chinese: '数列、等差数列、等比数列',
    summary: 'Số hạng tổng quát, tổng n số hạng, tổng vô hạn, truy hồi đơn giản.',
    keywords: ['day so', 'cap so cong', 'cap so nhan', 'tong n', '数列', '等差', '等比'],
    formulas: [
      { label: 'Cấp số cộng', value: m`\(u_n=u_1+(n-1)d\)` },
      { label: 'Tổng cấp số cộng', value: m`\(S_n=\frac{n(u_1+u_n)}2=\frac{n[2u_1+(n-1)d]}2\)` },
      { label: 'Trung bình cộng', value: m`\(u_k=\frac{u_{k-1}+u_{k+1}}2\)` },
      { label: 'Cấp số nhân', value: m`\(u_n=u_1q^{n-1}\)` },
      { label: 'Tổng cấp số nhân', value: m`\(S_n=u_1\frac{1-q^n}{1-q}\quad(q\ne1)\)` },
      { label: 'Nếu q = 1', value: m`\(S_n=nu_1\)` },
      { label: 'Tổng vô hạn', value: m`\(S=\frac{u_1}{1-q}\quad(|q|<1)\)` },
      { label: 'Trung bình nhân', value: m`\(u_k^2=u_{k-1}u_{k+1}\)` },
      { label: 'Sai phân', value: m`\(u_{n+1}-u_n=d\Rightarrow\text{cấp số cộng}\)` },
      { label: 'Tỉ số', value: m`\(\frac{u_{n+1}}{u_n}=q\Rightarrow\text{cấp số nhân}\)` },
    ],
  },
  {
    id: 'limits-continuity',
    title: 'Giới hạn và liên tục',
    grade: '11',
    area: 'Giới hạn',
    chinese: '极限、连续',
    summary: 'Giới hạn dãy, hàm số, vô cực, lượng giác, liên tục.',
    keywords: ['gioi han', 'lien tuc', 'limit', '极限', '连续'],
    formulas: [
      { label: 'Dãy hình học', value: m`\(\lim_{n\to\infty}q^n=0\quad(|q|<1)\)` },
      { label: 'Bậc cao nhất', value: m`\(\lim_{x\to\infty}\frac{a_mx^m+\cdots}{b_nx^n+\cdots}\)`, note: m`So sánh bậc \(m,n\).` },
      { label: 'Sin x / x', value: m`\(\lim_{x\to0}\frac{\sin x}{x}=1\)` },
      { label: 'Tan x / x', value: m`\(\lim_{x\to0}\frac{\tan x}{x}=1\)` },
      { label: '1 - cos x', value: m`\(\lim_{x\to0}\frac{1-\cos x}{x^2}=\frac{1}{2}\)` },
      { label: 'Mũ e', value: m`\(\lim_{x\to0}\frac{e^x-1}{x}=1,\quad \lim_{n\to\infty}\left(1+\frac{1}{n}\right)^n=e\)` },
      { label: 'Liên tục tại điểm', value: m`\(f\) liên tục tại \(x_0\) khi \(\lim_{x\to x_0}f(x)=f(x_0)\)` },
      { label: 'Liên tục trên khoảng', value: m`\(f\) liên tục trên \((a,b)\) nếu liên tục tại mọi \(x\in(a,b)\)` },
    ],
  },
  {
    id: 'derivative-table-rules',
    title: 'Đạo hàm và quy tắc tính',
    grade: '11',
    area: 'Đạo hàm',
    chinese: '导数',
    summary: 'Bảng đạo hàm, quy tắc tổng tích thương, hàm hợp, tiếp tuyến.',
    keywords: ['dao ham', 'tiep tuyen', 'ham hop', '导数', '切线'],
    formulas: [
      { label: 'Định nghĩa', value: m`\(f'(x_0)=\lim_{x\to x_0}\frac{f(x)-f(x_0)}{x-x_0}\)` },
      { label: 'Lũy thừa', value: m`\((x^\alpha)'=\alpha x^{\alpha-1}\)` },
      { label: 'Tổng', value: m`\((u+v)'=u'+v'\)` },
      { label: 'Tích', value: m`\((uv)'=u'v+uv'\)` },
      { label: 'Thương', value: m`\(\left(\frac{u}{v}\right)'=\frac{u'v-uv'}{v^2}\)` },
      { label: 'Hàm hợp', value: m`\((f(u))'=f'(u)u'\)` },
      { label: 'Lượng giác', value: m`\((\sin x)'=\cos x,\quad(\cos x)'=-\sin x,\quad(\tan x)'=\frac{1}{\cos^2x}\)` },
      { label: 'Mũ log', value: m`\((e^x)'=e^x,\quad(a^x)'=a^x\ln a,\quad(\ln x)'=\frac{1}{x}\)` },
      { label: 'Tiếp tuyến', value: m`\(y=f'(x_0)(x-x_0)+f(x_0)\)` },
      { label: 'Pháp tuyến', value: m`\(y=-\frac{1}{f'(x_0)}(x-x_0)+f(x_0)\quad(f'(x_0)\ne0)\)` },
    ],
  },
  {
    id: 'function-survey-optimization',
    title: 'Khảo sát hàm số, cực trị, min max',
    grade: '12',
    area: 'Khảo sát hàm',
    chinese: '函数性质、单调性、极值',
    summary: 'Đơn điệu, cực trị, tiệm cận, tương giao, giá trị lớn nhất nhỏ nhất.',
    keywords: ['khao sat ham', 'don dieu', 'cuc tri', 'min max', 'tiem can', '单调', '极值'],
    formulas: [
      { label: 'Đơn điệu', value: m`\(f'(x)>0\Rightarrow f\text{ tăng},\quad f'(x)<0\Rightarrow f\text{ giảm}\)` },
      { label: 'Cực trị', value: m`\(f'(x_0)=0\) và \(f'\) đổi dấu tại \(x_0\Rightarrow x_0\) là điểm cực trị.` },
      { label: 'Cực đại', value: m`\(f':+\to-\Rightarrow f(x_0)\text{ là cực đại}\)` },
      { label: 'Cực tiểu', value: m`\(f':-\to+\Rightarrow f(x_0)\text{ là cực tiểu}\)` },
      { label: 'Tiệm cận đứng', value: m`\(\lim_{x\to x_0^\pm}f(x)=\pm\infty\Rightarrow x=x_0\)` },
      { label: 'Tiệm cận ngang', value: m`\(\lim_{x\to\pm\infty}f(x)=y_0\Rightarrow y=y_0\)` },
      { label: 'Tiệm cận xiên', value: m`\(y=ax+b,\quad a=\lim_{x\to\infty}\frac{f(x)}x,\quad b=\lim_{x\to\infty}[f(x)-ax]\)` },
      { label: 'Tương giao', value: m`\(\text{số giao điểm của }y=f(x),y=g(x)\text{ là số nghiệm }f(x)=g(x)\)` },
      { label: 'GTLN GTNN trên đoạn', value: m`\(\max_{[a,b]}f,\min_{[a,b]}f\) lấy trong \(f(a),f(b)\) và các điểm \(f'(x)=0\) trong \((a,b)\).` },
    ],
    notes: ['Với câu tham số, thường chuyển về số nghiệm của phương trình hoặc vị trí tương đối đồ thị.'],
  },
  {
    id: 'exponential-log-equations',
    title: 'Phương trình, bất phương trình mũ log',
    grade: '12',
    area: 'Mũ log',
    chinese: '指数方程、对数方程',
    summary: 'Quy tắc biến đổi, điều kiện, đổi cơ số, xét đơn điệu.',
    keywords: ['phuong trinh mu log', 'bat phuong trinh log', '指数', '对数方程'],
    formulas: [
      { label: 'Cùng cơ số mũ', value: m`\(a^{f(x)}=a^{g(x)}\Leftrightarrow f(x)=g(x)\quad(a>0,a\ne1)\)` },
      { label: 'Cùng cơ số log', value: m`\(\log_a f(x)=\log_a g(x)\Leftrightarrow f(x)=g(x)>0\)` },
      { label: 'So sánh mũ', value: m`\(a^{f(x)}>a^{g(x)}\Leftrightarrow f(x)>g(x)\) nếu \(a>1\); đổi chiều nếu \(0<a<1\).` },
      { label: 'So sánh log', value: m`\(\log_a f(x)>\log_a g(x)\Leftrightarrow f(x)>g(x)>0\) nếu \(a>1\); đổi chiều nếu \(0<a<1\).` },
      { label: 'Đặt ẩn phụ mũ', value: m`\(a^{2x}=(a^x)^2,\quad t=a^x>0\)` },
      { label: 'Đặt ẩn phụ log', value: m`\((\log_a x)^2\Rightarrow t=\log_a x\)` },
      { label: 'Mũ tự nhiên', value: m`\(e^{\ln x}=x,\quad \ln e^x=x\)` },
    ],
    notes: ['Bất phương trình log luôn xử lý điều kiện xác định trước.'],
  },
  {
    id: 'solid-geometry-polyhedra',
    title: 'Khối đa diện: lăng trụ, chóp và chóp cụt',
    grade: '11',
    area: 'Hình học không gian',
    chinese: '多面体、棱柱、棱锥',
    summary: 'Thể tích, diện tích và đường chéo của các khối đa diện thường gặp; giải thích rõ từng ký hiệu.',
    keywords: ['khong gian', 'the tich', 'dien tich', 'lang tru', 'hinh chop', 'chop cut', '立体几何', '棱柱', '棱锥'],
    illustration: 'polyhedra',
    formulas: [
      {
        label: 'Lăng trụ bất kỳ',
        value: m`\(V=Bh\)`,
        note: m`\(B\) là diện tích một đáy; \(h\) là khoảng cách vuông góc giữa hai mặt đáy. Không lấy cạnh bên xiên thay cho \(h\).`,
      },
      {
        label: 'Lăng trụ đứng',
        value: m`\(S_{xq}=ph,\qquad S_{tp}=2B+ph\)`,
        note: m`\(p\) là chu vi đáy. Công thức này dùng khi cạnh bên vuông góc với đáy nên cạnh bên chính là \(h\).`,
      },
      {
        label: 'Hình hộp chữ nhật',
        value: m`\(V=abc,\quad S_{tp}=2(ab+bc+ca),\quad d=\sqrt{a^2+b^2+c^2}\)`,
        note: m`\(a,b,c\) là ba kích thước; \(d\) là đường chéo nối hai đỉnh đối diện của khối hộp.`,
      },
      {
        label: 'Hình lập phương',
        value: m`\(V=a^3,\quad S_{tp}=6a^2,\quad d=a\sqrt3\)`,
        note: m`Đường chéo một mặt bằng \(a\sqrt2\), còn đường chéo của khối lập phương bằng \(a\sqrt3\).`,
      },
      {
        label: 'Hình chóp bất kỳ',
        value: m`\(V=\frac13Bh\)`,
        note: m`\(h\) là đoạn vuông góc từ đỉnh xuống mặt đáy. Hình chiếu của đỉnh có thể nằm trong hoặc ngoài đa giác đáy.`,
      },
      {
        label: 'Chóp đều',
        value: m`\(S_{xq}=\frac12pl,\qquad S_{tp}=B+\frac12pl\)`,
        note: m`\(l\) là trung đoạn (đường cao của một mặt bên), không phải cạnh bên; \(p\) là chu vi đáy.`,
      },
      {
        label: 'Chóp cụt',
        value: m`\(V=\frac{h}{3}\left(B_1+B_2+\sqrt{B_1B_2}\right)\)`,
        note: m`\(B_1,B_2\) là diện tích hai đáy song song; \(h\) là khoảng cách giữa hai mặt đáy.`,
      },
      {
        label: 'Chóp cụt đều',
        value: m`\(S_{xq}=\frac12(p_1+p_2)l\)`,
        note: m`\(p_1,p_2\) là chu vi hai đáy và \(l\) là đường cao của mỗi mặt bên hình thang.`,
      },
      {
        label: 'Tỉ số thể tích hai chóp chung đỉnh',
        value: m`\(\frac{V_{S.A'B'C'}}{V_{S.ABC}}=\frac{SA'}{SA}\cdot\frac{SB'}{SB}\cdot\frac{SC'}{SC}\)`,
        note: m`Dùng khi \(A'\in SA, B'\in SB, C'\in SC\). Nếu ba tỉ số cùng bằng \(k\) thì tỉ số thể tích bằng \(k^3\).`,
      },
      {
        label: 'Tứ diện bằng tích hỗn tạp',
        value: m`\(V_{ABCD}=\frac16\left|\overrightarrow{AB}\cdot\left(\overrightarrow{AC}\times\overrightarrow{AD}\right)\right|\)`,
        note: 'Hữu ích trong bài tọa độ khi biết bốn đỉnh; lấy trị tuyệt đối để thể tích luôn không âm.',
      },
    ],
    notes: [
      m`Quy trình an toàn: xác định đúng mặt đáy \(\rightarrow\) tính \(B\) và \(p\) \(\rightarrow\) dựng chiều cao vuông góc \(h\) \(\rightarrow\) thay vào công thức.`,
    ],
  },
  {
    id: 'solid-geometry-round-solids',
    title: 'Khối tròn xoay: trụ, nón, nón cụt và cầu',
    grade: '12',
    area: 'Hình học không gian',
    chinese: '旋转体、圆柱、圆锥、球',
    summary: 'Bộ công thức thể tích và diện tích khối tròn xoay, kèm cách phân biệt bán kính, chiều cao và đường sinh.',
    keywords: ['khoi tron xoay', 'hinh tru', 'hinh non', 'non cut', 'mat cau', 'hinh cau', '圆柱', '圆锥', '球'],
    illustration: 'round-solids',
    formulas: [
      {
        label: 'Khối trụ',
        value: m`\(V=\pi R^2h\)`,
        note: m`\(R\) là bán kính đáy, \(h\) là khoảng cách vuông góc giữa hai đáy.`,
      },
      {
        label: 'Diện tích hình trụ',
        value: m`\(S_{xq}=2\pi Rh,\qquad S_{tp}=2\pi R(h+R)\)`,
        note: m`Khai triển mặt xung quanh được hình chữ nhật có hai cạnh \(2\pi R\) và \(h\).`,
      },
      {
        label: 'Khối nón',
        value: m`\(V=\frac13\pi R^2h\)`,
        note: m`Chiều cao \(h\) vuông góc với đáy; trong nón tròn xoay, chân đường cao là tâm đáy.`,
      },
      {
        label: 'Đường sinh nón',
        value: m`\(l=\sqrt{R^2+h^2}\)`,
        note: 'Áp dụng định lý Pythagore cho tam giác vuông tạo bởi bán kính, chiều cao và đường sinh.',
      },
      {
        label: 'Diện tích hình nón',
        value: m`\(S_{xq}=\pi Rl,\qquad S_{tp}=\pi R(l+R)\)`,
        note: m`Diện tích toàn phần bằng diện tích xung quanh cộng diện tích một đáy \(\pi R^2\).`,
      },
      {
        label: 'Khối nón cụt',
        value: m`\(V=\frac{\pi h}{3}(R^2+Rr+r^2)\)`,
        note: m`\(R,r\) là hai bán kính đáy \((R>r)\); \(h\) là khoảng cách giữa hai đáy.`,
      },
      {
        label: 'Diện tích nón cụt',
        value: m`\(S_{xq}=\pi(R+r)l,\quad S_{tp}=\pi(R+r)l+\pi(R^2+r^2)\)`,
        note: m`Với nón cụt tròn xoay: \(l=\sqrt{h^2+(R-r)^2}\).`,
      },
      {
        label: 'Khối cầu và mặt cầu',
        value: m`\(V=\frac43\pi R^3,\qquad S=4\pi R^2\)`,
        note: m`\(V\) là thể tích khối cầu; \(S\) là diện tích mặt cầu, không phải diện tích một hình tròn lớn.`,
      },
      {
        label: 'Chỏm cầu cao h',
        value: m`\(V=\frac{\pi h^2}{3}(3R-h),\qquad S_{xq}=2\pi Rh\)`,
        note: m`Điều kiện \(0\le h\le2R\). \(S_{xq}\) chỉ là diện tích mặt cong của chỏm cầu.`,
      },
      {
        label: 'Cầu nội tiếp hình lập phương',
        value: m`\(R=\frac a2\)`,
        note: 'Đường kính cầu bằng cạnh hình lập phương vì mặt cầu tiếp xúc với cả sáu mặt.',
      },
      {
        label: 'Cầu ngoại tiếp hình lập phương',
        value: m`\(R=\frac{a\sqrt3}{2}\)`,
        note: 'Đường kính cầu bằng đường chéo của khối lập phương.',
      },
    ],
    notes: [
      m`Đừng nhầm \(l\) với \(h\): \(l\) nằm trên mặt bên, còn \(h\) vuông góc với mặt đáy.`,
    ],
  },
  {
    id: 'solid-geometry-angles-distances',
    title: 'Góc, vuông góc và khoảng cách trong không gian',
    grade: '11',
    area: 'Hình học không gian',
    chinese: '空间角与距离',
    summary: 'Cách dựng đúng góc và đoạn khoảng cách trước khi tính bằng lượng giác hoặc định lý Pythagore.',
    keywords: ['goc duong mat', 'goc nhi dien', 'khoang cach', 'vuong goc', 'duong cheo nhau', '空间角', '距离', '垂直'],
    illustration: 'spatial-relations',
    formulas: [
      {
        label: 'Góc đường thẳng – mặt phẳng',
        value: m`\(\varphi=(d,d')\) với \(d'\) là hình chiếu vuông góc của \(d\) lên \((P)\).`,
        note: m`Luôn có \(0^\circ\le\varphi\le90^\circ\). Nếu \(d\perp(P)\) thì \(\varphi=90^\circ\).`,
      },
      {
        label: 'Tính góc đường – mặt',
        value: m`\(\sin\varphi=\frac{h}{a},\qquad \tan\varphi=\frac{h}{a'}\)`,
        note: m`Trong tam giác vuông: \(a\) là độ dài đoạn xiên trên đường thẳng, \(a'\) là độ dài hình chiếu và \(h\) là độ chênh vuông góc với mặt phẳng.`,
      },
      {
        label: 'Góc giữa hai mặt phẳng',
        value: m`\(\varphi=((P),(Q))=(a,b)\)`,
        note: m`Chọn \(a\subset(P), b\subset(Q)\) cùng vuông góc với giao tuyến tại một điểm. Góc nhọn giữa \(a,b\) là góc giữa hai mặt phẳng.`,
      },
      {
        label: 'Hai mặt phẳng vuông góc',
        value: m`\((P)\perp(Q)\Leftarrow(P)\text{ chứa một đường thẳng }d\perp(Q)\)`,
        note: 'Đây là dấu hiệu thường dùng nhất để chứng minh hai mặt phẳng vuông góc.',
      },
      {
        label: 'Đường thẳng vuông góc mặt phẳng',
        value: m`\(d\perp(P)\Leftarrow d\perp a,\ d\perp b\)`,
        note: m`Hai đường \(a,b\subset(P)\) phải cắt nhau. Vuông góc với hai đường song song là chưa đủ.`,
      },
      {
        label: 'Khoảng cách điểm – mặt',
        value: m`\(d(M,(P))=MH\quad\text{khi }H\in(P),\ MH\perp(P)\)`,
        note: 'Bài hình thuần túy cần dựng đúng chân H; sau đó tính MH trong một tam giác vuông thích hợp.',
      },
      {
        label: 'Khoảng cách đường – mặt song song',
        value: m`\(d(d,(P))=d(M,(P)),\quad M\in d,\ d\parallel(P)\)`,
        note: 'Có thể chọn điểm M thuận lợi bất kỳ trên d vì mọi điểm của d cách mặt phẳng một khoảng bằng nhau.',
      },
      {
        label: 'Khoảng cách hai mặt song song',
        value: m`\(d((P),(Q))=d(M,(Q)),\quad M\in(P),\ (P)\parallel(Q)\)`,
        note: 'Chọn M sao cho việc dựng đường vuông góc đến mặt phẳng còn lại đơn giản nhất.',
      },
      {
        label: 'Khoảng cách hai đường chéo nhau',
        value: m`\(d(a,b)=MN\quad\text{khi }M\in a,\ N\in b,\ MN\perp a,\ MN\perp b\)`,
        note: 'MN là đoạn vuông góc chung. Cũng có thể dựng mặt phẳng chứa a và song song với b rồi đổi về khoảng cách đường – mặt.',
      },
      {
        label: 'Thể tích để tính khoảng cách',
        value: m`\(h=\frac{3V}{B}\)`,
        note: m`Nếu xem khối chóp theo một mặt khác làm đáy, chiều cao \(h\) chính là khoảng cách từ đỉnh đối diện đến mặt đáy đó.`,
      },
      {
        label: 'Định lý ba đường vuông góc',
        value: m`\(a\perp d'\Rightarrow a\perp d\)`,
        note: m`Với \(d'\) là hình chiếu của đường xiên \(d\) lên mặt phẳng chứa \(a\). Dùng để chuyển bài vuông góc trong không gian về trên mặt phẳng.`,
      },
    ],
    notes: [
      'Góc phải được dựng thành một góc phẳng cụ thể; khoảng cách phải được dựng thành một đoạn vuông góc cụ thể rồi mới tính.',
    ],
  },
  {
    id: 'coordinate-space-oxyz',
    title: 'Tọa độ Oxyz',
    grade: '12',
    area: 'Hình tọa độ',
    chinese: '空间解析几何',
    summary: 'Vectơ 3D, mặt phẳng, đường thẳng, mặt cầu, khoảng cách, góc.',
    keywords: ['oxyz', 'khong gian', 'mat phang', 'duong thang', 'mat cau', '空间解析几何'],
    illustration: 'oxyz',
    formulas: [
      { label: 'Khoảng cách hai điểm', value: m`\(AB=\sqrt{(x_B-x_A)^2+(y_B-y_A)^2+(z_B-z_A)^2}\)`, note: 'Lấy hiệu tọa độ cùng trục, bình phương, cộng rồi khai căn.' },
      { label: 'Trung điểm đoạn thẳng', value: m`\(M\left(\frac{x_A+x_B}{2},\frac{y_A+y_B}{2},\frac{z_A+z_B}{2}\right)\)` },
      { label: 'Trọng tâm tam giác', value: m`\(G\left(\frac{x_A+x_B+x_C}{3},\frac{y_A+y_B+y_C}{3},\frac{z_A+z_B+z_C}{3}\right)\)` },
      { label: 'Tích vô hướng', value: m`\(\vec a\cdot\vec b=x_1x_2+y_1y_2+z_1z_2\)`, note: m`\(\vec a\perp\vec b\Leftrightarrow\vec a\cdot\vec b=0\).` },
      { label: 'Tích có hướng', value: m`\([\vec a,\vec b]=(y_1z_2-z_1y_2,\ z_1x_2-x_1z_2,\ x_1y_2-y_1x_2)\)`, note: m`Vectơ kết quả vuông góc với cả \(\vec a\) và \(\vec b\); độ dài bằng diện tích hình bình hành tạo bởi hai vectơ.` },
      { label: 'Góc hai vectơ', value: m`\(\cos(\vec a,\vec b)=\frac{\vec a\cdot\vec b}{|\vec a||\vec b|}\)` },
      { label: 'Mặt phẳng tổng quát', value: m`\(Ax+By+Cz+D=0\)`, note: m`Một vectơ pháp tuyến là \(\vec n=(A,B,C)\).` },
      { label: 'Mặt phẳng qua điểm', value: m`\(A(x-x_0)+B(y-y_0)+C(z-z_0)=0\)`, note: m`Dùng khi biết điểm \(M_0(x_0,y_0,z_0)\) và vectơ pháp tuyến \((A,B,C)\).` },
      { label: 'Khoảng cách điểm – mặt', value: m`\(d(M,(P))=\frac{|Ax_M+By_M+Cz_M+D|}{\sqrt{A^2+B^2+C^2}}\)`, note: 'Thay tọa độ điểm vào vế trái phương trình mặt phẳng rồi lấy trị tuyệt đối.' },
      { label: 'Khoảng cách hai mặt song song', value: m`\(d((P),(Q))=\frac{|D_1-D_2|}{\sqrt{A^2+B^2+C^2}}\)`, note: m`Hai phương trình phải được đưa về cùng bộ hệ số \(A,B,C\): \(Ax+By+Cz+D_1=0\), \(Ax+By+Cz+D_2=0\).` },
      { label: 'Đường thẳng tham số', value: m`\(\begin{cases}x=x_0+at\\y=y_0+bt\\z=z_0+ct\end{cases}\)`, note: m`Đường thẳng đi qua \(M_0(x_0,y_0,z_0)\) và có vectơ chỉ phương \(\vec u=(a,b,c)\).` },
      { label: 'Đường thẳng chính tắc', value: m`\(\frac{x-x_0}{a}=\frac{y-y_0}{b}=\frac{z-z_0}{c}\)` },
      { label: 'Mặt cầu', value: m`\((x-a)^2+(y-b)^2+(z-c)^2=R^2\)` },
      { label: 'Mặt cầu tổng quát', value: m`\(x^2+y^2+z^2-2ax-2by-2cz+d=0,\quad R=\sqrt{a^2+b^2+c^2-d}\)`, note: m`Tâm là \(I(a,b,c)\); cần \(a^2+b^2+c^2-d>0\) để có mặt cầu thực.` },
      { label: 'Góc hai đường thẳng', value: m`\(\cos\varphi=\frac{|\vec u_1\cdot\vec u_2|}{|\vec u_1||\vec u_2|}\)`, note: 'Lấy trị tuyệt đối để nhận góc nhọn hoặc vuông giữa hai đường.' },
      { label: 'Góc đường – mặt', value: m`\(\sin\varphi=\frac{|\vec u\cdot\vec n|}{|\vec u||\vec n|}\)`, note: m`\(\vec u\) là vectơ chỉ phương của đường, \(\vec n\) là pháp tuyến của mặt phẳng.` },
      { label: 'Góc hai mặt phẳng', value: m`\(\cos\varphi=\frac{|\vec n_1\cdot\vec n_2|}{|\vec n_1||\vec n_2|}\)`, note: 'Góc giữa hai mặt phẳng bằng góc nhọn giữa hai vectơ pháp tuyến của chúng.' },
      { label: 'Khoảng cách điểm – đường', value: m`\(d(M,d)=\frac{|\overrightarrow{AM}\times\vec u|}{|\vec u|},\quad A\in d\)`, note: m`Chọn điểm \(A\) bất kỳ trên đường thẳng và \(\vec u\) là vectơ chỉ phương của \(d\).` },
      { label: 'Khoảng cách hai đường chéo nhau', value: m`\(d(d_1,d_2)=\frac{|\overrightarrow{AB}\cdot(\vec u_1\times\vec u_2)|}{|\vec u_1\times\vec u_2|}\)`, note: m`Dùng khi \(A\in d_1, B\in d_2\) và hai vectơ chỉ phương không cùng phương.` },
    ],
    notes: ['Trước khi dùng công thức tọa độ, hãy ghi rõ điểm đi qua, vectơ chỉ phương hoặc vectơ pháp tuyến để tránh thay nhầm dữ kiện.'],
  },
  {
    id: 'combinatorics-probability',
    title: 'Tổ hợp và xác suất',
    grade: '11',
    area: 'Xác suất',
    chinese: '排列组合、概率',
    summary: 'Quy tắc đếm, hoán vị, chỉnh hợp, tổ hợp, nhị thức, xác suất.',
    keywords: ['to hop', 'xac suat', 'hoan vi', 'chinh hop', '概率', '排列组合'],
    formulas: [
      { label: 'Quy tắc cộng', value: m`\(m+n\)` },
      { label: 'Quy tắc nhân', value: m`\(m\cdot n\)` },
      { label: 'Hoán vị', value: m`\(P_n=n!\)` },
      { label: 'Chỉnh hợp', value: m`\(A_n^k=\frac{n!}{(n-k)!}\)` },
      { label: 'Tổ hợp', value: m`\(C_n^k=\frac{n!}{k!(n-k)!}\)` },
      { label: 'Tính chất tổ hợp', value: m`\(C_n^k=C_n^{n-k},\quad C_n^k+C_n^{k+1}=C_{n+1}^{k+1}\)` },
      { label: 'Nhị thức Newton', value: m`\((a+b)^n=\sum_{k=0}^{n}C_n^k a^{n-k}b^k\)` },
      { label: 'Xác suất cổ điển', value: m`\(P(A)=\frac{n(A)}{n(\Omega)}\)` },
      { label: 'Cộng xác suất', value: m`\(P(A\cup B)=P(A)+P(B)-P(A\cap B)\)` },
      { label: 'Biến cố đối', value: m`\(P(\overline A)=1-P(A)\)` },
      { label: 'Độc lập', value: m`\(A,B\text{ độc lập}\Leftrightarrow P(A\cap B)=P(A)P(B)\)` },
      { label: 'Có điều kiện', value: m`\(P(A|B)=\frac{P(A\cap B)}{P(B)}\)` },
      { label: 'Bayes', value: m`\(P(A_i|B)=\frac{P(A_i)P(B|A_i)}{\sum_k P(A_k)P(B|A_k)}\)` },
    ],
  },
  {
    id: 'statistics-data',
    title: 'Thống kê cơ bản',
    grade: '10',
    area: 'Thống kê',
    chinese: '统计',
    summary: 'Trung bình, phương sai, độ lệch chuẩn, trung vị, tứ phân vị.',
    keywords: ['thong ke', 'trung binh', 'phuong sai', 'do lech chuan', '统计'],
    formulas: [
      { label: 'Trung bình', value: m`\(\bar{x}=\frac{x_1+x_2+\cdots+x_n}{n}\)` },
      { label: 'Trung bình có tần số', value: m`\(\bar{x}=\frac{n_1x_1+n_2x_2+\cdots+n_kx_k}{n_1+n_2+\cdots+n_k}\)` },
      { label: 'Phương sai', value: m`\(s^2=\frac{1}{n}\sum_{i=1}^{n}(x_i-\bar{x})^2\)` },
      { label: 'Độ lệch chuẩn', value: m`\(s=\sqrt{s^2}\)` },
      { label: 'Khoảng biến thiên', value: m`\(R=x_{\max}-x_{\min}\)` },
      { label: 'Mốt', value: 'Giá trị xuất hiện nhiều nhất trong mẫu số liệu.' },
      { label: 'Trung vị', value: 'Giá trị đứng giữa khi sắp xếp mẫu số liệu tăng dần.' },
      { label: 'Tứ phân vị', value: m`\(Q_1,Q_2,Q_3\) chia mẫu đã sắp xếp thành bốn phần gần bằng nhau.` },
      { label: 'Khoảng tứ phân vị', value: m`\(\Delta_Q=Q_3-Q_1\)` },
    ],
  },
  {
    id: 'antiderivatives-integrals',
    title: 'Nguyên hàm và tích phân',
    grade: '12',
    area: 'Tích phân',
    chinese: '原函数、积分',
    summary: 'Bảng nguyên hàm, đổi biến, từng phần, Newton Leibniz.',
    keywords: ['nguyen ham', 'tich phan', 'doi bien', 'tung phan', '积分'],
    formulas: [
      { label: 'Lũy thừa', value: m`\(\int x^\alpha\,dx=\frac{x^{\alpha+1}}{\alpha+1}+C\quad(\alpha\ne-1)\)` },
      { label: '1/x', value: m`\(\int\frac{1}{x}\,dx=\ln|x|+C\)` },
      { label: 'Mũ', value: m`\(\int e^x\,dx=e^x+C,\quad \int a^x\,dx=\frac{a^x}{\ln a}+C\)` },
      { label: 'Sin cos', value: m`\(\int\sin x\,dx=-\cos x+C,\quad \int\cos x\,dx=\sin x+C\)` },
      { label: '1/cos²', value: m`\(\int\frac{1}{\cos^2x}\,dx=\tan x+C\)` },
      { label: '1/sin²', value: m`\(\int\frac{1}{\sin^2x}\,dx=-\cot x+C\)` },
      { label: 'Đổi biến', value: m`\(\int f(u)u'\,dx=\int f(u)\,du\)` },
      { label: 'Từng phần', value: m`\(\int u\,dv=uv-\int v\,du\)` },
      { label: 'Newton Leibniz', value: m`\(\int_a^b f(x)\,dx=F(b)-F(a)\)` },
      { label: 'Tính chất', value: m`\(\int_a^b f(x)\,dx=-\int_b^a f(x)\,dx,\quad \int_a^a f(x)\,dx=0\)` },
    ],
  },
  {
    id: 'integral-applications',
    title: 'Ứng dụng tích phân',
    grade: '12',
    area: 'Tích phân',
    chinese: '积分应用',
    summary: 'Diện tích hình phẳng, thể tích khối tròn xoay, quãng đường.',
    keywords: ['ung dung tich phan', 'dien tich', 'the tich xoay', '积分应用'],
    formulas: [
      { label: 'Diện tích dưới đồ thị', value: m`\(S=\int_a^b |f(x)|\,dx\)` },
      { label: 'Diện tích giữa hai đồ thị', value: m`\(S=\int_a^b |f(x)-g(x)|\,dx\)` },
      { label: 'Thể tích quanh Ox', value: m`\(V=\pi\int_a^b f^2(x)\,dx\)` },
      { label: 'Thể tích quanh Oy', value: m`\(V=\pi\int_c^d g^2(y)\,dy\)` },
      { label: 'Thể tích lát cắt', value: m`\(V=\int_a^b S(x)\,dx\)` },
      { label: 'Quãng đường', value: m`\(s=\int_{t_1}^{t_2}|v(t)|\,dt\)` },
      { label: 'Vận tốc', value: m`\(v(t)=s'(t),\quad a(t)=v'(t)=s''(t)\)` },
      { label: 'Giá trị trung bình', value: m`\(f_{\text{tb}}=\frac{1}{b-a}\int_a^b f(x)\,dx\)` },
    ],
  },
  {
    id: 'complex-numbers',
    title: 'Số phức',
    grade: '12',
    area: 'Số phức',
    chinese: '复数',
    summary: 'Dạng đại số, môđun, liên hợp, chia số phức, lượng giác, tập hợp điểm.',
    keywords: ['so phuc', 'modun', 'lien hop', '复数'],
    formulas: [
      { label: 'Dạng đại số', value: m`\(z=a+bi,\quad i^2=-1\)` },
      { label: 'Môđun', value: m`\(|z|=\sqrt{a^2+b^2}\)` },
      { label: 'Liên hợp', value: m`\(\bar z=a-bi\)` },
      { label: 'Tích liên hợp', value: m`\(z\bar z=|z|^2\)` },
      { label: 'Chia số phức', value: m`\(\frac{z_1}{z_2}=\frac{z_1\bar z_2}{|z_2|^2}\quad(z_2\ne0)\)` },
      { label: 'Dạng lượng giác', value: m`\(z=r(\cos\varphi+i\sin\varphi)\)` },
      { label: 'Nhân dạng lượng giác', value: m`\(z_1z_2=r_1r_2[\cos(\varphi_1+\varphi_2)+i\sin(\varphi_1+\varphi_2)]\)` },
      { label: 'Moivre', value: m`\(z^n=r^n(\cos n\varphi+i\sin n\varphi)\)` },
      { label: 'Căn bậc hai', value: m`\(w^2=z\Rightarrow |w|^2=|z|\)` },
      { label: 'Tập hợp điểm tròn', value: m`\(|z-z_0|=R\)` },
    ],
  },
  {
    id: 'quick-chinese-exam-patterns',
    title: 'Mẫu nhận diện nhanh trong đề CSCA',
    grade: 'Chung',
    area: 'Chiến thuật',
    chinese: '考试常见表达',
    summary: 'Từ khóa tiếng Trung hay kéo theo công thức tương ứng trong đề Toán CSCA.',
    keywords: ['csca', 'tu khoa trung', 'doc de', '关键词', '公式'],
    formulas: [
      { label: '定义域', value: m`Tìm tập xác định: kiểm tra mẫu khác 0, căn bậc chẵn không âm, log dương.` },
      { label: '值域', value: 'Tìm tập giá trị: dùng biến đổi tương đương, đạo hàm hoặc đồ thị.' },
      { label: '单调递增 / 单调递减', value: m`Xét dấu đạo hàm: \(f'(x)>0\) tăng, \(f'(x)<0\) giảm.` },
      { label: '极大值 / 极小值', value: 'Cực đại / cực tiểu: đạo hàm đổi dấu tại nghiệm.' },
      { label: '切线', value: m`Tiếp tuyến: \(y=f'(x_0)(x-x_0)+f(x_0)\).` },
      { label: '等差数列', value: m`Cấp số cộng: \(u_n=u_1+(n-1)d,\ S_n=\frac{n(u_1+u_n)}2\).` },
      { label: '等比数列', value: m`Cấp số nhân: \(u_n=u_1q^{n-1},\ S_n=u_1\frac{1-q^n}{1-q}\).` },
      { label: '垂直 / 平行', value: m`Vuông góc dùng tích vô hướng bằng 0; song song dùng cùng phương hoặc hệ số góc bằng nhau.` },
      { label: '至少一个', value: m`Ít nhất một: thường dùng biến cố đối \(P=1-P(\text{không xảy ra})\).` },
      { label: '圆锥曲线', value: 'Conic: kiểm tra elip, hypebol, parabol theo phương trình chính tắc.' },
    ],
    notes: ['Phần này giúp đọc đề Trung nhanh, không thay thế công thức chính ở các mục trên.'],
  },
];

export const MATH_FORMULA_GRADE_OPTIONS: MathFormulaGrade[] = ['Chung', '10', '11', '12'];

export const MATH_FORMULA_AREAS = Array.from(
  new Set(MATH_CSCA_FORMULA_TOPICS.map(topic => topic.area)),
);
