export type PhysicsFormulaGrade = '10' | '11' | '12' | 'Chung';

export interface PhysicsFormulaLine {
  label: string;
  value: string;
  note?: string;
}

export interface PhysicsCscaFormulaTopic {
  id: string;
  title: string;
  grade: PhysicsFormulaGrade;
  area: string;
  chinese?: string;
  summary: string;
  keywords: string[];
  formulas: PhysicsFormulaLine[];
  notes?: string[];
}

export const PHYSICS_CSCA_FORMULA_TOPICS: PhysicsCscaFormulaTopic[] = [
  {
    id: 'constants-units',
    title: 'Hang so, don vi va doi don vi nhanh',
    grade: 'Chung',
    area: 'Nen tang',
    chinese: '常量与单位',
    summary: 'Cac hang so vat ly hay gap va quan he don vi can dung trong tinh nhanh.',
    keywords: ['hang so', 'don vi', 'doi don vi', 'si', 'constant', '单位', '常量'],
    formulas: [
      { label: 'Gia toc trong truong', value: '\\(g\\approx9.8\\,\\text{m/s}^2\\)', note: 'Lam tron theo de: thuong dung \\(10\\,\\text{m/s}^2\\).' },
      { label: 'Toc do anh sang', value: '\\(c=3.0\\times10^8\\,\\text{m/s}\\)' },
      { label: 'Dien tich nguyen to', value: '\\(e=1.6\\times10^{-19}\\,\\text{C}\\)' },
      { label: 'Hang so Planck', value: '\\(h=6.625\\times10^{-34}\\,\\text{J.s}\\)' },
      { label: 'So Avogadro', value: '\\(N_A=6.02\\times10^{23}\\,\\text{mol}^{-1}\\)' },
      { label: 'Hang so khi ly tuong', value: '\\(R=8.31\\,\\text{J/(mol.K)}\\)' },
      { label: 'Hang so Boltzmann', value: '\\(k=1.38\\times10^{-23}\\,\\text{J/K}\\)' },
      { label: 'Hang so Coulomb', value: '\\(k_e=9.0\\times10^9\\,\\text{N.m}^2/\\text{C}^2\\)' },
      { label: 'Do dien tham chan khong', value: '\\(\\varepsilon_0=8.85\\times10^{-12}\\,\\text{F/m}\\)' },
      { label: 'Do tu tham chan khong', value: '\\(\\mu_0=4\\pi\\times10^{-7}\\,\\text{H/m}\\)' },
      { label: 'Doi nhiet do', value: '\\(T(K)=t(^\\circ C)+273\\)' },
      { label: 'Doi cong suat dien', value: '\\(1\\,\\text{kWh}=3.6\\times10^6\\,\\text{J}\\)' },
    ],
    notes: ['Neu de cho gia tri hang so rieng, uu tien dung gia tri trong de.'],
  },
  {
    id: 'vector-projection',
    title: 'Vectơ, hinh chieu va tong hop luc',
    grade: 'Chung',
    area: 'Nen tang',
    chinese: '矢量与分解',
    summary: 'Dung cho co hoc, dien truong, tu truong: tach thanh phan, cong vectơ, chieu luc.',
    keywords: ['vector', 'vecto', 'hinh chieu', 'tong hop luc', 'phan tich luc', '矢量'],
    formulas: [
      { label: 'Do lon tong hai vectơ', value: '\\(|\\vec a+\\vec b|=\\sqrt{a^2+b^2+2ab\\cos\\alpha}\\)' },
      { label: 'Hieu hai vectơ', value: '\\(|\\vec a-\\vec b|=\\sqrt{a^2+b^2-2ab\\cos\\alpha}\\)' },
      { label: 'Tich vo huong', value: '\\(\\vec a\\cdot\\vec b=ab\\cos\\alpha\\)' },
      { label: 'Thanh phan theo truc', value: '\\(A_x=A\\cos\\alpha,\\quad A_y=A\\sin\\alpha\\)' },
      { label: 'Do lon tu thanh phan', value: '\\(A=\\sqrt{A_x^2+A_y^2}\\)' },
      { label: 'Goc tu thanh phan', value: '\\(\\tan\\alpha=\\frac{A_y}{A_x}\\)' },
      { label: 'Hai vectơ vuong goc', value: '\\(\\vec a\\perp\\vec b\\Leftrightarrow \\vec a\\cdot\\vec b=0\\)' },
      { label: 'Hai vectơ cung phuong', value: '\\(\\vec a=k\\vec b\\)' },
    ],
  },
  {
    id: 'kinematics-straight',
    title: 'Dong hoc chat diem: chuyen dong thang',
    grade: '10',
    area: 'Co hoc',
    chinese: '直线运动',
    summary: 'Chuyen dong thang deu, bien doi deu, do thi va cac cong thuc rut nhanh.',
    keywords: ['dong hoc', 'chuyen dong thang', 'van toc', 'gia toc', 'roi tu do', '直线运动', '速度'],
    formulas: [
      { label: 'Van toc trung binh', value: '\\(v_{tb}=\\frac{\\Delta s}{\\Delta t}\\)' },
      { label: 'Toc do trung binh', value: '\\(\\bar v=\\frac{s}{t}\\)' },
      { label: 'Gia toc', value: '\\(a=\\frac{\\Delta v}{\\Delta t}\\)' },
      { label: 'Thang deu', value: '\\(x=x_0+vt\\)' },
      { label: 'Bien doi deu - van toc', value: '\\(v=v_0+at\\)' },
      { label: 'Bien doi deu - toa do', value: '\\(x=x_0+v_0t+\\frac12at^2\\)' },
      { label: 'Lien he doc lap thoi gian', value: '\\(v^2-v_0^2=2a(x-x_0)\\)' },
      { label: 'Duong di bien doi deu', value: '\\(s=v_0t+\\frac12at^2\\)', note: 'Dung khi chieu duong cung chieu chuyen dong ban dau.' },
      { label: 'Quang duong trong giay thu n', value: '\\(\\Delta s_n=v_0+\\frac{a}{2}(2n-1)\\)' },
      { label: 'Van toc trung binh bien doi deu', value: '\\(v_{tb}=\\frac{v_0+v}{2}\\)' },
    ],
    notes: ['Chon chieu duong truoc, roi gan dau cho \\(v_0,a,x\\).'],
  },
  {
    id: 'free-fall-projectile-relative',
    title: 'Roi tu do, nem va chuyen dong tuong doi',
    grade: '10',
    area: 'Co hoc',
    chinese: '自由落体与相对运动',
    summary: 'Cong thuc nem ngang, nem xien, roi tu do va bai toan thuyen, may bay, vat moc.',
    keywords: ['roi tu do', 'nem ngang', 'nem xien', 'tuong doi', 'free fall', '自由落体', '抛体'],
    formulas: [
      { label: 'Roi tu do - van toc', value: '\\(v=gt\\)' },
      { label: 'Roi tu do - quang duong', value: '\\(h=\\frac12gt^2\\)' },
      { label: 'Lien he roi tu do', value: '\\(v^2=2gh\\)' },
      { label: 'Nem thang dung', value: '\\(y=y_0+v_0t-\\frac12gt^2,\\quad v=v_0-gt\\)' },
      { label: 'Do cao cuc dai nem dung', value: '\\(h_{max}=\\frac{v_0^2}{2g}\\)' },
      { label: 'Nem ngang', value: '\\(x=v_0t,\\quad y=\\frac12gt^2\\)' },
      { label: 'Thoi gian nem ngang tu do cao h', value: '\\(t=\\sqrt{\\frac{2h}{g}}\\)' },
      { label: 'Tam xa nem ngang', value: '\\(L=v_0\\sqrt{\\frac{2h}{g}}\\)' },
      { label: 'Nem xien - thanh phan', value: '\\(v_{0x}=v_0\\cos\\alpha,\\quad v_{0y}=v_0\\sin\\alpha\\)' },
      { label: 'Tam cao nem xien', value: '\\(H=\\frac{v_0^2\\sin^2\\alpha}{2g}\\)' },
      { label: 'Tam xa nem xien cung do cao', value: '\\(L=\\frac{v_0^2\\sin2\\alpha}{g}\\)' },
      { label: 'Van toc tuong doi', value: '\\(\\vec v_{13}=\\vec v_{12}+\\vec v_{23}\\)' },
    ],
  },
  {
    id: 'circular-motion',
    title: 'Chuyen dong tron deu va gia toc huong tam',
    grade: '10',
    area: 'Co hoc',
    chinese: '匀速圆周运动',
    summary: 'Tan so, chu ky, toc do goc, luc huong tam; dung nhieu trong con lac, hat mang dien, ve tinh.',
    keywords: ['chuyen dong tron', 'toc do goc', 'huong tam', 'tan so', 'chu ky', '圆周运动'],
    formulas: [
      { label: 'Tan so - chu ky', value: '\\(f=\\frac1T,\\quad \\omega=2\\pi f=\\frac{2\\pi}{T}\\)' },
      { label: 'Toc do dai', value: '\\(v=\\omega r=\\frac{2\\pi r}{T}\\)' },
      { label: 'Goc quay', value: '\\(\\varphi=\\omega t\\)' },
      { label: 'Gia toc huong tam', value: '\\(a_{ht}=\\frac{v^2}{r}=\\omega^2r\\)' },
      { label: 'Luc huong tam', value: '\\(F_{ht}=ma_{ht}=m\\frac{v^2}{r}=m\\omega^2r\\)' },
      { label: 'Lien he cung - goc', value: '\\(s=r\\varphi\\)', note: '\\(\\varphi\\) tinh bang radian.' },
      { label: 'Toc do goc cua kim dong ho', value: '\\(\\omega=\\frac{2\\pi}{T}\\)' },
      { label: 'Do bien thien van toc', value: '\\(|\\Delta\\vec v|=2v\\sin\\frac{\\Delta\\varphi}{2}\\)' },
    ],
  },
  {
    id: 'dynamics-forces',
    title: 'Dong luc hoc: Newton, ma sat, mat phang nghieng',
    grade: '10',
    area: 'Co hoc',
    chinese: '牛顿定律与受力分析',
    summary: 'Nhan dien luc, ap dung dinh luat II Newton, luc dan hoi, ma sat, luc cang day.',
    keywords: ['newton', 'luc', 'ma sat', 'mat phang nghieng', 'hooke', '牛顿', '摩擦力'],
    formulas: [
      { label: 'Dinh luat II Newton', value: '\\(\\sum\\vec F=m\\vec a\\)' },
      { label: 'Trong luc', value: '\\(\\vec P=m\\vec g\\)' },
      { label: 'Luc dan hoi Hooke', value: '\\(F_{dh}=k|\\Delta l|\\)' },
      { label: 'Luc ma sat truot', value: '\\(F_{mst}=\\mu_t N\\)' },
      { label: 'Luc ma sat nghi cuc dai', value: '\\(F_{msn,max}=\\mu_n N\\)' },
      { label: 'Mat phang ngang', value: '\\(N=mg\\)' },
      { label: 'Mat phang nghieng', value: '\\(P_{\\parallel}=mg\\sin\\alpha,\\quad P_{\\perp}=mg\\cos\\alpha\\)' },
      { label: 'Phan luc tren mat phang nghieng', value: '\\(N=mg\\cos\\alpha\\)' },
      { label: 'Chuyen dong tren mat phang nghieng co ma sat', value: '\\(a=g(\\sin\\alpha-\\mu\\cos\\alpha)\\)', note: 'Vat truot xuong, luc ma sat huong len.' },
      { label: 'He vat noi day', value: '\\(a=\\frac{F_{ngoai}}{m_1+m_2+\\cdots}\\)' },
      { label: 'Thang may', value: '\\(N=m(g\\pm a)\\)', note: 'Tang toc len: \\(+a\\); tang toc xuong: \\(-a\\).' },
    ],
  },
  {
    id: 'gravitation-kepler',
    title: 'Hap dan, trong truong va ve tinh',
    grade: '10',
    area: 'Co hoc',
    chinese: '万有引力',
    summary: 'Luc hap dan, gia toc trong truong bien thien theo do cao, chuyen dong ve tinh tron.',
    keywords: ['hap dan', 've tinh', 'kepler', 'trong truong', '万有引力'],
    formulas: [
      { label: 'Luc hap dan', value: '\\(F=G\\frac{m_1m_2}{r^2}\\)' },
      { label: 'Gia toc trong truong tai cach tam r', value: '\\(g=G\\frac{M}{r^2}\\)' },
      { label: 'Tai mat dat', value: '\\(g_0=G\\frac{M}{R^2}\\)' },
      { label: 'Theo do cao h', value: '\\(g_h=g_0\\left(\\frac{R}{R+h}\\right)^2\\)' },
      { label: 'Trong luong bieu kien', value: '\\(P_{bk}=N\\)' },
      { label: 'Ve tinh tron', value: '\\(G\\frac{Mm}{r^2}=m\\frac{v^2}{r}\\)' },
      { label: 'Toc do ve tinh tron', value: '\\(v=\\sqrt{\\frac{GM}{r}}\\)' },
      { label: 'Chu ky ve tinh', value: '\\(T=2\\pi\\sqrt{\\frac{r^3}{GM}}\\)' },
      { label: 'Kepler III', value: '\\(\\frac{T_1^2}{T_2^2}=\\frac{r_1^3}{r_2^3}\\)' },
    ],
  },
  {
    id: 'work-energy-power',
    title: 'Cong, cong suat, dong nang, the nang',
    grade: '10',
    area: 'Co hoc',
    chinese: '功与能量',
    summary: 'Bao toan va bien thien co nang, cong cua luc, hieu suat, bai toan vat truot/nem/lo xo.',
    keywords: ['cong', 'nang luong', 'co nang', 'dong nang', 'the nang', 'cong suat', '功', '能量'],
    formulas: [
      { label: 'Cong cua luc khong doi', value: '\\(A=Fs\\cos\\alpha\\)' },
      { label: 'Cong suat', value: '\\(P=\\frac{A}{t}=Fv\\cos\\alpha\\)' },
      { label: 'Dong nang', value: '\\(W_d=\\frac12mv^2\\)' },
      { label: 'Dinh ly dong nang', value: '\\(A_{\\sum F}=\\Delta W_d\\)' },
      { label: 'The nang trong truong', value: '\\(W_t=mgh\\)' },
      { label: 'The nang dan hoi', value: '\\(W_{dh}=\\frac12k(\\Delta l)^2\\)' },
      { label: 'Co nang', value: '\\(W=W_d+W_t\\)' },
      { label: 'Bao toan co nang', value: '\\(W_1=W_2\\)', note: 'Chi dung khi chi co luc the sinh cong.' },
      { label: 'Co luc khong the', value: '\\(A_{khong\\ the}=\\Delta W\\)' },
      { label: 'Hieu suat', value: '\\(H=\\frac{A_{ich}}{A_{toan}}\\times100\\%=\\frac{P_{ich}}{P_{toan}}\\times100\\%\\)' },
      { label: 'The nang hap dan tong quat', value: '\\(W_t=-G\\frac{Mm}{r}\\)' },
    ],
  },
  {
    id: 'momentum-collisions',
    title: 'Dong luong, xung luong va va cham',
    grade: '10',
    area: 'Co hoc',
    chinese: '动量与碰撞',
    summary: 'Dung cho va cham mem, va cham dan hoi, no, he kin, sung dan.',
    keywords: ['dong luong', 'xung luong', 'va cham', 'he kin', '动量', '碰撞'],
    formulas: [
      { label: 'Dong luong', value: '\\(\\vec p=m\\vec v\\)' },
      { label: 'Xung luong cua luc', value: '\\(\\vec I=\\vec F\\Delta t\\)' },
      { label: 'Dinh ly bien thien dong luong', value: '\\(\\vec F\\Delta t=\\Delta\\vec p\\)' },
      { label: 'Bao toan dong luong', value: '\\(\\sum\\vec p_{truoc}=\\sum\\vec p_{sau}\\)' },
      { label: 'Va cham mem mot chieu', value: '\\(v=\\frac{m_1v_1+m_2v_2}{m_1+m_2}\\)' },
      { label: 'Do giam dong nang va cham mem', value: '\\(\\Delta W_d=W_{d,sau}-W_{d,truoc}<0\\)' },
      { label: 'Va cham dan hoi', value: '\\(\\sum\\vec p=\\text{const},\\quad \\sum W_d=\\text{const}\\)' },
      { label: 'No tu trang thai nghi', value: '\\(m_1\\vec v_1+m_2\\vec v_2+\\cdots=0\\)' },
      { label: 'Khoi tam', value: '\\(\\vec v_G=\\frac{m_1\\vec v_1+m_2\\vec v_2+\\cdots}{m_1+m_2+\\cdots}\\)' },
    ],
  },
  {
    id: 'rotation-equilibrium',
    title: 'Vat ran, momen luc va can bang',
    grade: '10',
    area: 'Co hoc',
    chinese: '力矩与平衡',
    summary: 'Can bang vat ran, don bay, ngau luc, quy tac momen, chuyen dong quay co ban.',
    keywords: ['vat ran', 'momen luc', 'can bang', 'don bay', 'ngau luc', '力矩', '平衡'],
    formulas: [
      { label: 'Momen luc', value: '\\(M=Fd\\)' },
      { label: 'Dieu kien can bang tong quat', value: '\\(\\sum\\vec F=0,\\quad \\sum M=0\\)' },
      { label: 'Quy tac momen', value: '\\(F_1d_1=F_2d_2\\)' },
      { label: 'Ngau luc', value: '\\(M=Fd\\)', note: '\\(d\\) la khoang cach giua hai gia luc song song nguoc chieu.' },
      { label: 'Trong tam he chat diem', value: '\\(x_G=\\frac{\\sum m_ix_i}{\\sum m_i}\\)' },
      { label: 'Toc do goc trung binh', value: '\\(\\omega_{tb}=\\frac{\\Delta\\varphi}{\\Delta t}\\)' },
      { label: 'Gia toc goc', value: '\\(\\gamma=\\frac{\\Delta\\omega}{\\Delta t}\\)' },
      { label: 'Lien he quay - dai', value: '\\(v=\\omega r,\\quad a_t=\\gamma r\\)' },
    ],
  },
  {
    id: 'fluids',
    title: 'Chat long, ap suat va luc day Archimedes',
    grade: '10',
    area: 'Chat long',
    chinese: '流体压强',
    summary: 'Ap suat thuy tinh, binh thong nhau, luc day, dong chay lien tuc va Bernoulli co ban.',
    keywords: ['chat long', 'ap suat', 'archimedes', 'binh thong nhau', 'bernoulli', '压强', '浮力'],
    formulas: [
      { label: 'Ap suat', value: '\\(p=\\frac{F}{S}\\)' },
      { label: 'Ap suat thuy tinh', value: '\\(p=p_0+\\rho gh\\)' },
      { label: 'Luc day Archimedes', value: '\\(F_A=\\rho_{long}gV_{chim}\\)' },
      { label: 'Vat noi', value: '\\(F_A=P\\Rightarrow \\rho_{long}V_{chim}=\\rho_{vat}V_{vat}\\)' },
      { label: 'Luu luong', value: '\\(Q=Sv\\)' },
      { label: 'Phuong trinh lien tuc', value: '\\(S_1v_1=S_2v_2\\)' },
      { label: 'Bernoulli', value: '\\(p+\\frac12\\rho v^2+\\rho gh=\\text{const}\\)' },
      { label: 'Luc cang be mat', value: '\\(F=\\sigma l\\)' },
      { label: 'Do chenh ap Laplace', value: '\\(\\Delta p=\\frac{2\\sigma}{R}\\)', note: 'Giot cau mot mat cong.' },
    ],
  },
  {
    id: 'thermal-calorimetry',
    title: 'Nhiet hoc: nhiet luong, chuyen the, no vi nhiet',
    grade: '10',
    area: 'Nhiet hoc',
    chinese: '热学',
    summary: 'Can bang nhiet, nong chay, hoa hoi, no dai, no khoi; hay gap trong bai toan tong hop.',
    keywords: ['nhiet luong', 'can bang nhiet', 'nong chay', 'hoa hoi', 'no vi nhiet', '热量'],
    formulas: [
      { label: 'Nhiet luong', value: '\\(Q=mc\\Delta t\\)' },
      { label: 'Nhiet nong chay', value: '\\(Q=\\lambda m\\)' },
      { label: 'Nhiet hoa hoi', value: '\\(Q=Lm\\)' },
      { label: 'Phuong trinh can bang nhiet', value: '\\(\\sum Q_{toa}=\\sum Q_{thu}\\)' },
      { label: 'No dai', value: '\\(l=l_0(1+\\alpha\\Delta t)\\)' },
      { label: 'Do no dai', value: '\\(\\Delta l=\\alpha l_0\\Delta t\\)' },
      { label: 'No dien tich', value: '\\(S=S_0(1+2\\alpha\\Delta t)\\)' },
      { label: 'No the tich', value: '\\(V=V_0(1+\\beta\\Delta t),\\quad \\beta\\approx3\\alpha\\)' },
      { label: 'Do am ti doi', value: '\\(f=\\frac{a}{A}\\times100\\%\\)' },
    ],
  },
  {
    id: 'ideal-gas-thermodynamics',
    title: 'Khi ly tuong va nguyen ly nhiet dong luc hoc',
    grade: '10',
    area: 'Nhiet hoc',
    chinese: '理想气体与热力学',
    summary: 'Dinh luat Boyle, Charles, Gay-Lussac, phuong trinh trang thai, cong cua khi.',
    keywords: ['khi ly tuong', 'boyle', 'charles', 'nhiet dong luc', '理想气体'],
    formulas: [
      { label: 'Boyle - Mariotte', value: '\\(pV=\\text{const}\\quad(T=\\text{const})\\)' },
      { label: 'Charles', value: '\\(\\frac{V}{T}=\\text{const}\\quad(p=\\text{const})\\)' },
      { label: 'Gay-Lussac', value: '\\(\\frac{p}{T}=\\text{const}\\quad(V=\\text{const})\\)' },
      { label: 'Trang thai khi ly tuong', value: '\\(\\frac{pV}{T}=\\text{const}\\)' },
      { label: 'Clapeyron - Mendeleev', value: '\\(pV=nRT=\\frac{m}{M}RT\\)' },
      { label: 'Dong nang tinh tien phan tu', value: '\\(\\bar W_d=\\frac32kT\\)' },
      { label: 'Noi nang khi don nguyen tu', value: '\\(U=\\frac32nRT\\)' },
      { label: 'Cong cua khi dang ap', value: '\\(A=p\\Delta V\\)' },
      { label: 'Nguyen ly I', value: '\\(\\Delta U=Q+A\\)', note: '\\(A\\) la cong ngoai luc thuc hien len khi theo quy uoc pho thong.' },
      { label: 'Hieu suat dong co nhiet', value: '\\(H=\\frac{A}{Q_1}=1-\\frac{Q_2}{Q_1}\\)' },
      { label: 'Carnot', value: '\\(H_{max}=1-\\frac{T_2}{T_1}\\)' },
    ],
  },
  {
    id: 'electrostatics',
    title: 'Dien tich, luc Coulomb va dien truong',
    grade: '11',
    area: 'Dien hoc',
    chinese: '静电场',
    summary: 'Luc giua hai dien tich, cuong do dien truong, nguyen ly chong chat, dien truong deu.',
    keywords: ['dien tich', 'coulomb', 'dien truong', 'field', '静电场', '库仑定律'],
    formulas: [
      { label: 'Dinh luat Coulomb', value: '\\(F=k\\frac{|q_1q_2|}{\\varepsilon r^2}\\)' },
      { label: 'Cuong do dien truong', value: '\\(\\vec E=\\frac{\\vec F}{q}\\)' },
      { label: 'Dien truong dien tich diem', value: '\\(E=k\\frac{|Q|}{\\varepsilon r^2}\\)' },
      { label: 'Luc dien', value: '\\(\\vec F=q\\vec E\\)' },
      { label: 'Chong chat dien truong', value: '\\(\\vec E=\\vec E_1+\\vec E_2+\\cdots\\)' },
      { label: 'Dien truong deu', value: '\\(E=\\frac{U}{d}\\)' },
      { label: 'Cong cua luc dien trong dien truong deu', value: '\\(A=qEd\\)' },
      { label: 'Mat do dien tich mat', value: '\\(\\sigma=\\frac{q}{S}\\)' },
      { label: 'Thong luong dien truong', value: '\\(\\Phi=ES\\cos\\alpha\\)' },
    ],
  },
  {
    id: 'potential-capacitor',
    title: 'Dien the, hieu dien the va tu dien',
    grade: '11',
    area: 'Dien hoc',
    chinese: '电势与电容',
    summary: 'Lien he cong - hieu dien the, the nang dien, tu dien phang, ghep tu dien.',
    keywords: ['dien the', 'hieu dien the', 'tu dien', 'dien dung', '电势', '电容'],
    formulas: [
      { label: 'Hieu dien the', value: '\\(U_{MN}=V_M-V_N=\\frac{A_{MN}}{q}\\)' },
      { label: 'Cong cua luc dien', value: '\\(A_{MN}=qU_{MN}\\)' },
      { label: 'Dien the dien tich diem', value: '\\(V=k\\frac{Q}{\\varepsilon r}\\)' },
      { label: 'The nang dien', value: '\\(W=qV\\)' },
      { label: 'Lien he E va U', value: '\\(E=\\frac{U}{d}\\)' },
      { label: 'Dien dung', value: '\\(C=\\frac{Q}{U}\\)' },
      { label: 'Tu dien phang', value: '\\(C=\\frac{\\varepsilon\\varepsilon_0S}{d}\\)' },
      { label: 'Nang luong tu dien', value: '\\(W=\\frac12CU^2=\\frac{Q^2}{2C}=\\frac12QU\\)' },
      { label: 'Ghep song song', value: '\\(C_b=C_1+C_2+\\cdots\\)' },
      { label: 'Ghep noi tiep', value: '\\(\\frac1{C_b}=\\frac1{C_1}+\\frac1{C_2}+\\cdots\\)' },
      { label: 'Noi tiep cung dien tich', value: '\\(Q_1=Q_2=\\cdots=Q\\)' },
      { label: 'Song song cung hieu dien the', value: '\\(U_1=U_2=\\cdots=U\\)' },
    ],
  },
  {
    id: 'dc-current',
    title: 'Dong dien khong doi, dien tro va mach dien',
    grade: '11',
    area: 'Dien hoc',
    chinese: '恒定电流',
    summary: 'Dinh luat Ohm, ghep dien tro, dien nang, cong suat, mach cau co ban.',
    keywords: ['dong dien', 'ohm', 'dien tro', 'mach dien', 'cong suat dien', '电流', '欧姆定律'],
    formulas: [
      { label: 'Cuong do dong dien', value: '\\(I=\\frac{\\Delta q}{\\Delta t}\\)' },
      { label: 'Dinh luat Ohm doan mach', value: '\\(I=\\frac{U}{R}\\)' },
      { label: 'Dien tro day dan', value: '\\(R=\\rho\\frac{l}{S}\\)' },
      { label: 'Phu thuoc nhiet do', value: '\\(R=R_0[1+\\alpha(t-t_0)]\\)' },
      { label: 'Noi tiep dien tro', value: '\\(R_b=R_1+R_2+\\cdots\\)' },
      { label: 'Song song dien tro', value: '\\(\\frac1{R_b}=\\frac1{R_1}+\\frac1{R_2}+\\cdots\\)' },
      { label: 'Hai dien tro song song', value: '\\(R_b=\\frac{R_1R_2}{R_1+R_2}\\)' },
      { label: 'Cong dong dien', value: '\\(A=UIt\\)' },
      { label: 'Cong suat dien', value: '\\(P=UI=I^2R=\\frac{U^2}{R}\\)' },
      { label: 'Dinh luat Joule - Lenz', value: '\\(Q=I^2Rt\\)' },
      { label: 'Dieu kien cau can bang', value: '\\(\\frac{R_1}{R_2}=\\frac{R_3}{R_4}\\)' },
    ],
  },
  {
    id: 'source-closed-circuit',
    title: 'Nguon dien, may thu va dinh luat Ohm toan mach',
    grade: '11',
    area: 'Dien hoc',
    chinese: '闭合电路欧姆定律',
    summary: 'Suat dien dong, dien tro trong, hieu suat nguon, ghep nguon, may thu dien.',
    keywords: ['nguon dien', 'suat dien dong', 'dien tro trong', 'toan mach', '电源'],
    formulas: [
      { label: 'Suat dien dong', value: '\\(\\mathcal E=\\frac{A_{nguon}}{q}\\)' },
      { label: 'Ohm toan mach', value: '\\(I=\\frac{\\mathcal E}{R+r}\\)' },
      { label: 'Hieu dien the mach ngoai', value: '\\(U=\\mathcal E-Ir=IR\\)' },
      { label: 'Doan mach co nguon', value: '\\(U_{AB}=\\mathcal E-I(R+r)\\)', note: 'Dau tuy chieu di qua nguon va chieu dong dien.' },
      { label: 'Cong suat nguon', value: '\\(P_{nguon}=\\mathcal EI\\)' },
      { label: 'Cong suat co ich', value: '\\(P_{ich}=UI=I^2R\\)' },
      { label: 'Hieu suat nguon', value: '\\(H=\\frac{U}{\\mathcal E}=\\frac{R}{R+r}\\)' },
      { label: 'Ghep nguon noi tiep', value: '\\(\\mathcal E_b=n\\mathcal E,\\quad r_b=nr\\)' },
      { label: 'Ghep nguon song song giong nhau', value: '\\(\\mathcal E_b=\\mathcal E,\\quad r_b=\\frac{r}{n}\\)' },
      { label: 'May thu dien', value: '\\(U=\\mathcal E^{\\prime}+Ir^{\\prime}\\)' },
    ],
  },
  {
    id: 'current-in-media',
    title: 'Dong dien trong cac moi truong',
    grade: '11',
    area: 'Dien hoc',
    chinese: '介质中的电流',
    summary: 'Kim loai, dien phan, chat khi, chan khong, ban dan; cong thuc hay hoi trong de tong hop.',
    keywords: ['dien phan', 'faraday', 'ban dan', 'chat khi', 'moi truong', '法拉第电解'],
    formulas: [
      { label: 'Mat do dong dien', value: '\\(j=\\frac{I}{S}\\)' },
      { label: 'Van toc troi', value: '\\(I=n|q|Sv_d\\)' },
      { label: 'Dien tro kim loai theo nhiet do', value: '\\(R=R_0(1+\\alpha\\Delta t)\\)' },
      { label: 'Dinh luat Faraday dien phan', value: '\\(m=\\frac{A}{nF}It\\)' },
      { label: 'Hang so Faraday', value: '\\(F=96500\\,\\text{C/mol}\\)' },
      { label: 'Dien luong dien phan', value: '\\(q=It\\)' },
      { label: 'Dien tro nhiet NTC', value: '\\(R\\) giam khi \\(t\\) tang', note: 'Dung nhan dien dinh tinh.' },
      { label: 'Diot ban dan ly tuong', value: '\\(I\\approx0\\) khi phan cuc nguoc, dan khi phan cuc thuan.' },
    ],
  },
  {
    id: 'magnetic-field-force',
    title: 'Tu truong, luc tu va chuyen dong hat mang dien',
    grade: '11',
    area: 'Tu hoc',
    chinese: '磁场与磁力',
    summary: 'Cam ung tu, luc tu len day dan, Lorentz, ban kinh quy dao, moment ngau luc tu.',
    keywords: ['tu truong', 'luc tu', 'lorentz', 'cam ung tu', 'magnetic', '磁场', '洛伦兹力'],
    formulas: [
      { label: 'Luc tu len day dan', value: '\\(F=BIl\\sin\\alpha\\)' },
      { label: 'Luc Lorentz', value: '\\(F=|q|vB\\sin\\alpha\\)' },
      { label: 'Ban kinh quy dao tron', value: '\\(R=\\frac{mv}{|q|B}\\)' },
      { label: 'Chu ky chuyen dong tron trong B', value: '\\(T=\\frac{2\\pi m}{|q|B}\\)' },
      { label: 'Tu truong day thang dai', value: '\\(B=2\\times10^{-7}\\frac{I}{r}\\)' },
      { label: 'Tu truong vong day tron', value: '\\(B=2\\pi\\times10^{-7}\\frac{NI}{R}\\)' },
      { label: 'Ong day dai', value: '\\(B=4\\pi\\times10^{-7}nI\\)' },
      { label: 'Momen ngau luc tu', value: '\\(M=NBIS\\sin\\alpha\\)' },
      { label: 'Tu thong', value: '\\(\\Phi=BS\\cos\\alpha\\)' },
      { label: 'Quy tac chong chat', value: '\\(\\vec B=\\vec B_1+\\vec B_2+\\cdots\\)' },
    ],
  },
  {
    id: 'electromagnetic-induction',
    title: 'Cam ung dien tu va tu cam',
    grade: '11',
    area: 'Tu hoc',
    chinese: '电磁感应',
    summary: 'Faraday, Lenz, suat dien dong cam ung, tu cam, nang luong tu truong.',
    keywords: ['cam ung dien tu', 'faraday', 'lenz', 'tu cam', '电磁感应'],
    formulas: [
      { label: 'Tu thong', value: '\\(\\Phi=BS\\cos\\alpha\\)' },
      { label: 'Faraday', value: '\\(|e_c|=\\left|\\frac{\\Delta\\Phi}{\\Delta t}\\right|\\)' },
      { label: 'Vong day N vong', value: '\\(|e_c|=N\\left|\\frac{\\Delta\\Phi}{\\Delta t}\\right|\\)' },
      { label: 'Thanh dan chuyen dong cat B', value: '\\(e=Blv\\sin\\alpha\\)' },
      { label: 'Dong cam ung', value: '\\(I_c=\\frac{e_c}{R}\\)' },
      { label: 'Tu cam', value: '\\(e_{tc}=-L\\frac{\\Delta I}{\\Delta t}\\)' },
      { label: 'Do tu cam ong day', value: '\\(L=4\\pi\\times10^{-7}\\frac{N^2S}{l}\\)' },
      { label: 'Nang luong tu truong', value: '\\(W=\\frac12LI^2\\)' },
      { label: 'Mat do nang luong tu truong', value: '\\(w=\\frac{B^2}{2\\mu}\\)' },
    ],
    notes: ['Dau tru trong Faraday-Lenz chi chieu chong lai nguyen nhan sinh ra cam ung.'],
  },
  {
    id: 'geometrical-optics',
    title: 'Khuc xa, phan xa toan phan va lang kinh',
    grade: '11',
    area: 'Quang hinh',
    chinese: '几何光学',
    summary: 'Dinh luat Snell, goc gioi han, lang kinh, duong truyen anh sang qua mat phan cach.',
    keywords: ['khuc xa', 'phan xa toan phan', 'lang kinh', 'snell', '折射', '全反射'],
    formulas: [
      { label: 'Chiet suat tuyet doi', value: '\\(n=\\frac{c}{v}\\)' },
      { label: 'Snell', value: '\\(n_1\\sin i=n_2\\sin r\\)' },
      { label: 'Chiet suat ti doi', value: '\\(n_{21}=\\frac{n_2}{n_1}=\\frac{\\sin i}{\\sin r}\\)' },
      { label: 'Goc gioi han', value: '\\(\\sin i_{gh}=\\frac{n_2}{n_1}\\quad(n_1>n_2)\\)' },
      { label: 'Dieu kien phan xa toan phan', value: '\\(n_1>n_2,\\quad i\\ge i_{gh}\\)' },
      { label: 'Lang kinh - goc lech', value: '\\(D=i_1+i_2-A\\)' },
      { label: 'Lang kinh - hinh hoc', value: '\\(r_1+r_2=A\\)' },
      { label: 'Goc lech cuc tieu', value: '\\(i_1=i_2,\\quad r_1=r_2=\\frac{A}{2}\\)' },
      { label: 'Chiet suat lang kinh luc lech cuc tieu', value: '\\(n=\\frac{\\sin\\frac{A+D_{min}}2}{\\sin\\frac A2}\\)' },
    ],
  },
  {
    id: 'lenses-mirrors-eye',
    title: 'Thau kinh, guong cau va mat',
    grade: '11',
    area: 'Quang hinh',
    chinese: '透镜与眼睛',
    summary: 'Cong thuc thau kinh mong, do phong dai, do tu, mat can/vien/lao, kinh lup.',
    keywords: ['thau kinh', 'guong cau', 'mat', 'kinh lup', 'do tu', '透镜', '眼睛'],
    formulas: [
      { label: 'Thau kinh mong', value: '\\(\\frac1f=\\frac1d+\\frac1{d^{\\prime}}\\)' },
      { label: 'Do phong dai anh', value: '\\(k=-\\frac{d^{\\prime}}{d}=\\frac{A^{\\prime}B^{\\prime}}{AB}\\)' },
      { label: 'Do tu thau kinh', value: '\\(D=\\frac1f\\)', note: '\\(f\\) tinh bang met, \\(D\\) tinh bang diop.' },
      { label: 'Ghep thau kinh sat nhau', value: '\\(D=D_1+D_2\\)' },
      { label: 'Guong cau', value: '\\(\\frac1f=\\frac1d+\\frac1{d^{\\prime}},\\quad f=\\frac R2\\)' },
      { label: 'Mat khong dieu tiet', value: '\\(f_{max}=OV\\)' },
      { label: 'Kinh sua can thi', value: '\\(f_k=-OC_v\\)', note: 'Khi deo sat mat de nhin vat o vo cuc.' },
      { label: 'Kinh sua vien thi', value: '\\(d^{\\prime}=-OC_c\\)', note: 'Vat o cuc can moi, anh ao tai cuc can cua mat.' },
      { label: 'So boi giac kinh lup ngan gon', value: '\\(G=\\frac{\\tan\\alpha}{\\tan\\alpha_0}\\)' },
      { label: 'Kinh lup ngam chung vo cuc', value: '\\(G_\\infty=\\frac{D}{f}\\)', note: '\\(D=25\\,\\text{cm}\\).' },
    ],
  },
  {
    id: 'harmonic-oscillation',
    title: 'Dao dong dieu hoa: phuong trinh va dai luong',
    grade: '12',
    area: 'Dao dong',
    chinese: '简谐振动',
    summary: 'Ly thuyet goc lop 12: li do, van toc, gia toc, pha, thoi gian, do thi.',
    keywords: ['dao dong dieu hoa', 'li do', 'pha', 'van toc', 'gia toc', '简谐振动'],
    formulas: [
      { label: 'Phuong trinh li do', value: '\\(x=A\\cos(\\omega t+\\varphi)\\)' },
      { label: 'Van toc', value: '\\(v=-\\omega A\\sin(\\omega t+\\varphi)\\)' },
      { label: 'Gia toc', value: '\\(a=-\\omega^2A\\cos(\\omega t+\\varphi)=-\\omega^2x\\)' },
      { label: 'Lien he doc lap thoi gian', value: '\\(\\frac{x^2}{A^2}+\\frac{v^2}{\\omega^2A^2}=1\\)' },
      { label: 'Toc do cuc dai', value: '\\(v_{max}=\\omega A\\)' },
      { label: 'Gia toc cuc dai', value: '\\(a_{max}=\\omega^2A\\)' },
      { label: 'Chu ky - tan so', value: '\\(T=\\frac{2\\pi}{\\omega},\\quad f=\\frac1T\\)' },
      { label: 'Quang duong trong mot chu ky', value: '\\(S_T=4A\\)' },
      { label: 'Co nang', value: '\\(W=\\frac12m\\omega^2A^2\\)' },
      { label: 'Dong nang', value: '\\(W_d=\\frac12mv^2=\\frac12m\\omega^2(A^2-x^2)\\)' },
      { label: 'The nang', value: '\\(W_t=\\frac12m\\omega^2x^2\\)' },
      { label: 'Luc keo ve', value: '\\(F=-kx=-m\\omega^2x\\)' },
    ],
  },
  {
    id: 'spring-pendulum',
    title: 'Con lac lo xo va con lac don',
    grade: '12',
    area: 'Dao dong',
    chinese: '弹簧振子与单摆',
    summary: 'Chu ky, nang luong, luc dan hoi, chieu dai con lac; phan hay ra trong de THPT.',
    keywords: ['con lac lo xo', 'con lac don', 'lo xo', 'dao dong', 'pendulum', '弹簧', '单摆'],
    formulas: [
      { label: 'Tan so goc lo xo', value: '\\(\\omega=\\sqrt{\\frac{k}{m}}\\)' },
      { label: 'Chu ky lo xo', value: '\\(T=2\\pi\\sqrt{\\frac{m}{k}}\\)' },
      { label: 'Do gian can bang lo xo thang dung', value: '\\(\\Delta l_0=\\frac{mg}{k}\\)' },
      { label: 'Luc dan hoi', value: '\\(F_{dh}=k|\\Delta l|\\)' },
      { label: 'Luc keo ve lo xo', value: '\\(F_{kv}=-kx\\)' },
      { label: 'Nang luong lo xo', value: '\\(W=\\frac12kA^2\\)' },
      { label: 'Tan so goc con lac don', value: '\\(\\omega=\\sqrt{\\frac{g}{l}}\\)' },
      { label: 'Chu ky con lac don', value: '\\(T=2\\pi\\sqrt{\\frac{l}{g}}\\)' },
      { label: 'Van toc con lac don', value: '\\(v=\\sqrt{2gl(\\cos\\alpha-\\cos\\alpha_0)}\\)' },
      { label: 'Luc cang day', value: '\\(T_d=mg(3\\cos\\alpha-2\\cos\\alpha_0)\\)' },
      { label: 'Bien thien chu ky theo nhiet do', value: '\\(\\frac{\\Delta T}{T}=\\frac12\\alpha\\Delta t\\)' },
      { label: 'Bien thien chu ky theo do cao', value: '\\(\\frac{\\Delta T}{T}=\\frac{h}{R}\\)' },
    ],
  },
  {
    id: 'mechanical-waves',
    title: 'Song co, giao thoa va song dung',
    grade: '12',
    area: 'Song co',
    chinese: '机械波',
    summary: 'Phuong trinh song, do lech pha, giao thoa hai nguon, song dung tren day va am hoc.',
    keywords: ['song co', 'giao thoa', 'song dung', 'buoc song', 'am hoc', '机械波', '驻波'],
    formulas: [
      { label: 'Buoc song', value: '\\(\\lambda=vT=\\frac{v}{f}\\)' },
      { label: 'Phuong trinh song', value: '\\(u_M=A\\cos\\left(\\omega t-\\frac{2\\pi x}{\\lambda}+\\varphi\\right)\\)' },
      { label: 'Do lech pha hai diem', value: '\\(\\Delta\\varphi=\\frac{2\\pi d}{\\lambda}\\)' },
      { label: 'Cung pha', value: '\\(d=k\\lambda\\)' },
      { label: 'Nguoc pha', value: '\\(d=\\left(k+\\frac12\\right)\\lambda\\)' },
      { label: 'Giao thoa cuc dai', value: '\\(d_2-d_1=k\\lambda\\)' },
      { label: 'Giao thoa cuc tieu', value: '\\(d_2-d_1=\\left(k+\\frac12\\right)\\lambda\\)' },
      { label: 'Song dung hai dau co dinh', value: '\\(l=k\\frac{\\lambda}{2}\\)' },
      { label: 'Mot dau co dinh mot dau tu do', value: '\\(l=(2k+1)\\frac{\\lambda}{4}\\)' },
      { label: 'Khoang cach nut - bung lien tiep', value: '\\(\\frac{\\lambda}{4}\\)' },
      { label: 'Khoang cach hai nut lien tiep', value: '\\(\\frac{\\lambda}{2}\\)' },
    ],
  },
  {
    id: 'sound-waves',
    title: 'Song am, muc cuong do am va hieu ung Doppler',
    grade: '12',
    area: 'Song co',
    chinese: '声波',
    summary: 'Cuong do am, muc cuong do am, quan he cong suat - khoang cach, Doppler co ban.',
    keywords: ['song am', 'muc cuong do am', 'doppler', 'cuong do am', '声波', '多普勒'],
    formulas: [
      { label: 'Cuong do am', value: '\\(I=\\frac{P}{S}\\)' },
      { label: 'Nguon diem', value: '\\(I=\\frac{P}{4\\pi r^2}\\)' },
      { label: 'Muc cuong do am', value: '\\(L=10\\log\\frac{I}{I_0}\\,\\text{dB}\\)' },
      { label: 'Chuan nghe', value: '\\(I_0=10^{-12}\\,\\text{W/m}^2\\)' },
      { label: 'Chenh lech muc am', value: '\\(L_2-L_1=10\\log\\frac{I_2}{I_1}\\)' },
      { label: 'Tang gap n lan cuong do', value: '\\(\\Delta L=10\\log n\\)' },
      { label: 'Quan he khoang cach', value: '\\(L_2-L_1=20\\log\\frac{r_1}{r_2}\\)' },
      { label: 'Doppler tong quat', value: '\\(f^{\\prime}=f\\frac{v\\pm v_M}{v\\mp v_S}\\)' },
      { label: 'Hoa am', value: '\\(f_n=nf_1\\)' },
    ],
  },
  {
    id: 'ac-rlc',
    title: 'Dong dien xoay chieu RLC',
    grade: '12',
    area: 'Dien xoay chieu',
    chinese: '交流电路',
    summary: 'Gia tri hieu dung, cam khang, dung khang, tong tro, cong suat, cong huong.',
    keywords: ['dien xoay chieu', 'rlc', 'cong huong', 'cong suat', '交流电', '共振'],
    formulas: [
      { label: 'Dien ap - dong dien tuc thoi', value: '\\(u=U_0\\cos(\\omega t+\\varphi_u),\\quad i=I_0\\cos(\\omega t+\\varphi_i)\\)' },
      { label: 'Gia tri hieu dung', value: '\\(U=\\frac{U_0}{\\sqrt2},\\quad I=\\frac{I_0}{\\sqrt2}\\)' },
      { label: 'Cam khang', value: '\\(Z_L=\\omega L\\)' },
      { label: 'Dung khang', value: '\\(Z_C=\\frac1{\\omega C}\\)' },
      { label: 'Tong tro RLC noi tiep', value: '\\(Z=\\sqrt{R^2+(Z_L-Z_C)^2}\\)' },
      { label: 'Dinh luat Ohm AC', value: '\\(I=\\frac{U}{Z}\\)' },
      { label: 'Do lech pha', value: '\\(\\tan\\varphi=\\frac{Z_L-Z_C}{R}\\)' },
      { label: 'He so cong suat', value: '\\(\\cos\\varphi=\\frac{R}{Z}\\)' },
      { label: 'Cong suat tieu thu', value: '\\(P=UI\\cos\\varphi=I^2R=\\frac{U^2R}{Z^2}\\)' },
      { label: 'Cong huong', value: '\\(Z_L=Z_C\\Leftrightarrow \\omega_0=\\frac1{\\sqrt{LC}}\\)' },
      { label: 'Tan so cong huong', value: '\\(f_0=\\frac1{2\\pi\\sqrt{LC}}\\)' },
      { label: 'He so pham chat', value: '\\(Q=\\frac{\\omega_0L}{R}=\\frac1{\\omega_0CR}\\)' },
      { label: 'May bien ap ly tuong', value: '\\(\\frac{U_1}{U_2}=\\frac{N_1}{N_2}=\\frac{I_2}{I_1}\\)' },
      { label: 'Truyen tai dien', value: '\\(\\Delta P=I^2R=\\frac{P^2R}{U^2\\cos^2\\varphi}\\)' },
    ],
  },
  {
    id: 'electromagnetic-oscillation-waves',
    title: 'Mach dao dong LC va song dien tu',
    grade: '12',
    area: 'Dien tu',
    chinese: '电磁振荡与电磁波',
    summary: 'Dao dong dien tu tu do, nang luong dien tu, buoc song may thu phat.',
    keywords: ['mach lc', 'song dien tu', 'dao dong dien tu', 'dien tu', '电磁波'],
    formulas: [
      { label: 'Tan so goc LC', value: '\\(\\omega=\\frac1{\\sqrt{LC}}\\)' },
      { label: 'Chu ky LC', value: '\\(T=2\\pi\\sqrt{LC}\\)' },
      { label: 'Tan so LC', value: '\\(f=\\frac1{2\\pi\\sqrt{LC}}\\)' },
      { label: 'Dien tich', value: '\\(q=Q_0\\cos(\\omega t+\\varphi)\\)' },
      { label: 'Dong dien', value: '\\(i=q^{\\prime}=-\\omega Q_0\\sin(\\omega t+\\varphi)\\)' },
      { label: 'Dong cuc dai', value: '\\(I_0=\\omega Q_0\\)' },
      { label: 'Nang luong dien truong', value: '\\(W_C=\\frac{q^2}{2C}=\\frac12Cu^2\\)' },
      { label: 'Nang luong tu truong', value: '\\(W_L=\\frac12Li^2\\)' },
      { label: 'Nang luong mach', value: '\\(W=\\frac{Q_0^2}{2C}=\\frac12LI_0^2\\)' },
      { label: 'Buoc song thu phat', value: '\\(\\lambda=cT=2\\pi c\\sqrt{LC}\\)' },
    ],
  },
  {
    id: 'wave-optics',
    title: 'Song anh sang, giao thoa va quang pho',
    grade: '12',
    area: 'Quang song',
    chinese: '光的波动性',
    summary: 'Young, khoang van, vi tri van, tan sac, may quang pho, tia hong ngoai - tu ngoai.',
    keywords: ['song anh sang', 'giao thoa anh sang', 'young', 'khoang van', 'quang pho', '光的干涉'],
    formulas: [
      { label: 'Khoang van Young', value: '\\(i=\\frac{\\lambda D}{a}\\)' },
      { label: 'Vi tri van sang', value: '\\(x_s=ki\\)' },
      { label: 'Vi tri van toi', value: '\\(x_t=\\left(k+\\frac12\\right)i\\)' },
      { label: 'Buoc song trong moi truong', value: '\\(\\lambda=\\frac{\\lambda_0}{n}\\)' },
      { label: 'Tan so anh sang', value: '\\(f=\\frac{c}{\\lambda}\\)' },
      { label: 'Chenh lech duong di', value: '\\(\\Delta d=\\frac{ax}{D}\\)' },
      { label: 'Van sang theo lech duong', value: '\\(\\Delta d=k\\lambda\\)' },
      { label: 'Van toi theo lech duong', value: '\\(\\Delta d=\\left(k+\\frac12\\right)\\lambda\\)' },
      { label: 'Nang luong photon', value: '\\(\\varepsilon=hf=\\frac{hc}{\\lambda}\\)' },
      { label: 'Tan sac', value: '\\(n_{tim}>n_{do}\\Rightarrow D_{tim}>D_{do}\\)' },
    ],
  },
  {
    id: 'photoelectric-quantum',
    title: 'Luong tu anh sang va hien tuong quang dien',
    grade: '12',
    area: 'Luong tu',
    chinese: '光电效应',
    summary: 'Photon, cong thoat, gioi han quang dien, Einstein, tia X co ban.',
    keywords: ['quang dien', 'photon', 'einstein', 'cong thoat', 'luong tu', '光电效应'],
    formulas: [
      { label: 'Nang luong photon', value: '\\(\\varepsilon=hf=\\frac{hc}{\\lambda}\\)' },
      { label: 'Gioi han quang dien', value: '\\(\\lambda_0=\\frac{hc}{A}\\)' },
      { label: 'Dieu kien quang dien ngoai', value: '\\(\\lambda\\le\\lambda_0\\)' },
      { label: 'Einstein quang dien', value: '\\(hf=A+\\frac12mv_{0max}^2\\)' },
      { label: 'Hieu dien the ham', value: '\\(eU_h=\\frac12mv_{0max}^2\\)' },
      { label: 'Dong quang dien bao hoa', value: '\\(I_{bh}=ne\\)' },
      { label: 'Cong suat chum photon', value: '\\(P=N\\varepsilon\\)' },
      { label: 'Hieu suat luong tu', value: '\\(H=\\frac{N_e}{N_{photon}}\\times100\\%\\)' },
      { label: 'Tien de Bohr hap thu/phat xa', value: '\\(hf=E_m-E_n\\)' },
      { label: 'Tia X ngan nhat', value: '\\(\\lambda_{min}=\\frac{hc}{eU}\\)' },
    ],
  },
  {
    id: 'atomic-physics',
    title: 'Mau nguyen tu Bohr va quang pho hidro',
    grade: '12',
    area: 'Luong tu',
    chinese: '玻尔原子模型',
    summary: 'Muc nang luong, ban kinh quy dao, day Lyman/Balmer/Paschen, photon phat xa.',
    keywords: ['bohr', 'hidro', 'quang pho', 'nguyen tu', 'bo', '氢原子'],
    formulas: [
      { label: 'Muc nang luong hidro', value: '\\(E_n=-\\frac{13.6}{n^2}\\,\\text{eV}\\)' },
      { label: 'Ban kinh quy dao', value: '\\(r_n=n^2r_0,\\quad r_0=5.3\\times10^{-11}\\,\\text{m}\\)' },
      { label: 'Photon phat xa/hap thu', value: '\\(hf=|E_m-E_n|\\)' },
      { label: 'Buoc song photon', value: '\\(\\lambda=\\frac{hc}{|E_m-E_n|}\\)' },
      { label: 'Lyman', value: '\\(n\\to1\\)', note: 'Vung tu ngoai.' },
      { label: 'Balmer', value: '\\(n\\to2\\)', note: 'Co cac vach nhin thay.' },
      { label: 'Paschen', value: '\\(n\\to3\\)', note: 'Vung hong ngoai.' },
      { label: 'Doi eV sang J', value: '\\(1\\,\\text{eV}=1.6\\times10^{-19}\\,\\text{J}\\)' },
    ],
  },
  {
    id: 'nuclear-physics',
    title: 'Hat nhan, phong xa va nang luong lien ket',
    grade: '12',
    area: 'Hat nhan',
    chinese: '核物理',
    summary: 'Cau tao hat nhan, do hut khoi, nang luong lien ket, phong xa, phan ung hat nhan.',
    keywords: ['hat nhan', 'phong xa', 'chu ky ban ra', 'nang luong lien ket', '核物理'],
    formulas: [
      { label: 'Ky hieu hat nhan', value: '\\({}^{A}_{Z}X\\)', note: '\\(A=Z+N\\).' },
      { label: 'Do hut khoi', value: '\\(\\Delta m=Zm_p+Nm_n-m_{hn}\\)' },
      { label: 'Nang luong lien ket', value: '\\(W_{lk}=\\Delta mc^2\\)' },
      { label: 'Nang luong lien ket rieng', value: '\\(\\varepsilon=\\frac{W_{lk}}{A}\\)' },
      { label: 'Doi khoi luong - nang luong', value: '\\(1u=931.5\\,\\text{MeV}/c^2\\)' },
      { label: 'Dinh luat phong xa', value: '\\(N=N_0e^{-\\lambda t}=N_0\\left(\\frac12\\right)^{t/T}\\)' },
      { label: 'So hat da phan ra', value: '\\(\\Delta N=N_0-N\\)' },
      { label: 'Do phong xa', value: '\\(H=\\lambda N\\)' },
      { label: 'Chu ky ban ra', value: '\\(T=\\frac{\\ln2}{\\lambda}\\)' },
      { label: 'Khoi luong con lai', value: '\\(m=m_0\\left(\\frac12\\right)^{t/T}\\)' },
      { label: 'Nang luong phan ung', value: '\\(Q=(m_{truoc}-m_{sau})c^2\\)' },
      { label: 'Bao toan trong phan ung', value: '\\(\\sum A_{truoc}=\\sum A_{sau},\\quad \\sum Z_{truoc}=\\sum Z_{sau}\\)' },
    ],
  },
  {
    id: 'relativity-modern',
    title: 'Tuong doi hep va he thuc hien dai hay gap',
    grade: '12',
    area: 'Vat ly hien dai',
    chinese: '狭义相对论',
    summary: 'Mot so cong thuc hien dai dung khi de co cau hoi nang cao ve nang luong, khoi luong, hat.',
    keywords: ['tuong doi', 'einstein', 'nang luong nghi', 'hien dai', '相对论'],
    formulas: [
      { label: 'He so Lorentz', value: '\\(\\gamma=\\frac1{\\sqrt{1-\\frac{v^2}{c^2}}}\\)' },
      { label: 'Khoi luong tuong doi', value: '\\(m=\\gamma m_0\\)' },
      { label: 'Nang luong nghi', value: '\\(E_0=m_0c^2\\)' },
      { label: 'Nang luong toan phan', value: '\\(E=mc^2=\\gamma m_0c^2\\)' },
      { label: 'Dong nang tuong doi', value: '\\(W_d=(m-m_0)c^2\\)' },
      { label: 'He thuc photon', value: '\\(p=\\frac{h}{\\lambda}=\\frac{\\varepsilon}{c}\\)' },
    ],
  },
  {
    id: 'exam-shortcuts',
    title: 'Mau nhan dien nhanh trong de Ly CSCA/THPT',
    grade: 'Chung',
    area: 'Chien thuat',
    chinese: '考试常见表达',
    summary: 'Tu khoa trong de thuong dan den cong thuc nao, giup tim nhanh khi doc de tieng Trung.',
    keywords: ['csca', 'thi thpt', 'tu khoa', 'nhan dien', '考试', '关键词'],
    formulas: [
      { label: '匀变速直线运动', value: 'Dung \\(v=v_0+at\\), \\(s=v_0t+\\frac12at^2\\), \\(v^2-v_0^2=2as\\).' },
      { label: '向心力 / 圆周运动', value: 'Dung \\(F_{ht}=m\\frac{v^2}{r}=m\\omega^2r\\).' },
      { label: '机械能守恒', value: 'Dung \\(\\frac12mv_1^2+mgh_1=\\frac12mv_2^2+mgh_2\\).' },
      { label: '电场强度 / 电势差', value: 'Dung \\(E=\\frac{F}{q}\\), \\(A=qU\\), \\(E=\\frac Ud\\).' },
      { label: '闭合电路', value: 'Dung \\(I=\\frac{\\mathcal E}{R+r}\\), \\(U=\\mathcal E-Ir\\).' },
      { label: '电磁感应', value: 'Dung \\(|e|=N\\left|\\frac{\\Delta\\Phi}{\\Delta t}\\right|\\), \\(\\Phi=BS\\cos\\alpha\\).' },
      { label: '简谐振动', value: 'Dung \\(x=A\\cos(\\omega t+\\varphi)\\), \\(v_{max}=\\omega A\\), \\(a=-\\omega^2x\\).' },
      { label: '交流电路 RLC', value: 'Dung \\(Z=\\sqrt{R^2+(Z_L-Z_C)^2}\\), \\(P=UI\\cos\\varphi\\).' },
      { label: '光电效应', value: 'Dung \\(hf=A+\\frac12mv_{0max}^2\\), \\(\\lambda_0=\\frac{hc}{A}\\).' },
      { label: '核反应', value: 'Dung bao toan \\(A,Z\\) va \\(Q=(m_{truoc}-m_{sau})c^2\\).' },
    ],
    notes: ['Tu khoa chi la goi y. Van can doc ky don vi, chieu duong, dieu kien ap dung.'],
  },
];

export const PHYSICS_FORMULA_GRADE_OPTIONS: PhysicsFormulaGrade[] = ['Chung', '10', '11', '12'];

export const PHYSICS_FORMULA_AREAS = Array.from(
  new Set(PHYSICS_CSCA_FORMULA_TOPICS.map(topic => topic.area)),
);
