export type PhysicsFormulaGrade = '10' | '11' | '12' | 'Chung';

export interface PhysicsFormulaLine {
  label: string;
  value: string;
  note?: string;
}

export interface PhysicsCscaFormulaTopic {
  id: string;
  title: string;
  grade: PhysicsFormulaGrade;
  area: string;
  chinese?: string;
  summary: string;
  keywords: string[];
  formulas: PhysicsFormulaLine[];
  notes?: string[];
}

export const PHYSICS_CSCA_FORMULA_TOPICS: PhysicsCscaFormulaTopic[] = [
  {
    id: 'constants-units',
    title: 'Hằng số, đơn vị và đổi đơn vị nhanh',
    grade: 'Chung',
    area: 'Nền tảng',
    summary: 'Các hằng số vật lý hay gặp và quan hệ đơn vị cần dùng trong tính nhanh.',
    keywords: ['hang so', 'don vi', 'doi don vi', 'si', 'constant', '单位', '常量'],
    formulas: [
      { label: 'Gia tốc trọng trường', value: '\\(g\\approx9.8\\,\\text{m/s}^2\\)', note: 'Làm tròn theo đề: thường dùng \\(10\\,\\text{m/s}^2\\).' },
      { label: 'Tốc độ ánh sáng', value: '\\(c=3.0\\times10^8\\,\\text{m/s}\\)' },
      { label: 'Điện tích nguyên tố', value: '\\(e=1.6\\times10^{-19}\\,\\text{C}\\)' },
      { label: 'Hằng số Planck', value: '\\(h=6.625\\times10^{-34}\\,\\text{J.s}\\)' },
      { label: 'Số Avogadro', value: '\\(N_A=6.02\\times10^{23}\\,\\text{mol}^{-1}\\)' },
      { label: 'Hằng số khí lý tưởng', value: '\\(R=8.31\\,\\text{J/(mol.K)}\\)' },
      { label: 'Hằng số Boltzmann', value: '\\(k=1.38\\times10^{-23}\\,\\text{J/K}\\)' },
      { label: 'Hằng số Coulomb', value: '\\(k_e=9.0\\times10^9\\,\\text{N.m}^2/\\text{C}^2\\)' },
      { label: 'Độ điện thẩm chân không', value: '\\(\\varepsilon_0=8.85\\times10^{-12}\\,\\text{F/m}\\)' },
      { label: 'Độ từ thẩm chân không', value: '\\(\\mu_0=4\\pi\\times10^{-7}\\,\\text{H/m}\\)' },
      { label: 'Đổi nhiệt độ', value: '\\(T(K)=t(^\\circ C)+273\\)' },
      { label: 'Đổi công suất điện', value: '\\(1\\,\\text{kWh}=3.6\\times10^6\\,\\text{J}\\)' },
    ],
    notes: ['Nếu đề cho giá trị hằng số riêng, ưu tiên dùng giá trị trong đề.'],
  },
  {
    id: 'vector-projection',
    title: 'Vectơ, hình chiếu và tổng hợp lực',
    grade: 'Chung',
    area: 'Nền tảng',
    summary: 'Dùng cho cơ học, điện trường, từ trường: tách thành phần, cộng vectơ, chiếu lực.',
    keywords: ['vector', 'vecto', 'hinh chieu', 'tong hop luc', 'phan tich luc', '矢量'],
    formulas: [
      { label: 'Độ lớn tổng hai vectơ', value: '\\(|\\vec a+\\vec b|=\\sqrt{a^2+b^2+2ab\\cos\\alpha}\\)' },
      { label: 'Hiệu hai vectơ', value: '\\(|\\vec a-\\vec b|=\\sqrt{a^2+b^2-2ab\\cos\\alpha}\\)' },
      { label: 'Tích vô hướng', value: '\\(\\vec a\\cdot\\vec b=ab\\cos\\alpha\\)' },
      { label: 'Thành phần theo trục', value: '\\(A_x=A\\cos\\alpha,\\quad A_y=A\\sin\\alpha\\)' },
      { label: 'Độ lớn từ thành phần', value: '\\(A=\\sqrt{A_x^2+A_y^2}\\)' },
      { label: 'Góc từ thành phần', value: '\\(\\tan\\alpha=\\frac{A_y}{A_x}\\)' },
      { label: 'Hai vectơ vuông góc', value: '\\(\\vec a\\perp\\vec b\\Leftrightarrow \\vec a\\cdot\\vec b=0\\)' },
      { label: 'Hai vectơ cùng phương', value: '\\(\\vec a=k\\vec b\\)' },
    ],
  },
  {
    id: 'kinematics-straight',
    title: 'Động học chất điểm: chuyển động thẳng',
    grade: '10',
    area: 'Cơ học',
    summary: 'Chuyển động thẳng đều, biến đổi đều, đồ thị và các công thức rút nhanh.',
    keywords: ['dong hoc', 'chuyen dong thang', 'van toc', 'gia toc', 'roi tu do', '直线运动', '速度'],
    formulas: [
      { label: 'Vận tốc trung bình', value: '\\(v_{tb}=\\frac{\\Delta s}{\\Delta t}\\)' },
      { label: 'Tốc độ trung bình', value: '\\(\\bar v=\\frac{s}{t}\\)' },
      { label: 'Gia tốc', value: '\\(a=\\frac{\\Delta v}{\\Delta t}\\)' },
      { label: 'Thẳng đều', value: '\\(x=x_0+vt\\)' },
      { label: 'Biến đổi đều - vận tốc', value: '\\(v=v_0+at\\)' },
      { label: 'Biến đổi đều - tọa độ', value: '\\(x=x_0+v_0t+\\frac{1}{2}at^2\\)' },
      { label: 'Liên hệ độc lập thời gian', value: '\\(v^2-v_0^2=2a(x-x_0)\\)' },
      { label: 'Đường đi biến đổi đều', value: '\\(s=v_0t+\\frac{1}{2}at^2\\)', note: 'Dùng khi chiều dương cùng chiều chuyển động ban đầu.' },
      { label: 'Quãng đường trong giây thứ n', value: '\\(\\Delta s_n=v_0+\\frac{a}{2}(2n-1)\\)' },
      { label: 'Vận tốc trung bình biến đổi đều', value: '\\(v_{tb}=\\frac{v_0+v}{2}\\)' },
    ],
    notes: ['Chọn chiều dương trước, rồi gán dấu cho \\(v_0,a,x\\).'],
  },
  {
    id: 'free-fall-projectile-relative',
    title: 'Rơi tự do, ném và chuyển động tương đối',
    grade: '10',
    area: 'Cơ học',
    summary: 'Công thức ném ngang, ném xiên, rơi tự do và bài toán thuyền, máy bay, vật mốc.',
    keywords: ['roi tu do', 'nem ngang', 'nem xien', 'tuong doi', 'free fall', '自由落体', '抛体'],
    formulas: [
      { label: 'Rơi tự do - vận tốc', value: '\\(v=gt\\)' },
      { label: 'Rơi tự do - quãng đường', value: '\\(h=\\frac{1}{2}gt^2\\)' },
      { label: 'Liên hệ rơi tự do', value: '\\(v^2=2gh\\)' },
      { label: 'Ném thẳng đứng', value: '\\(y=y_0+v_0t-\\frac{1}{2}gt^2,\\quad v=v_0-gt\\)' },
      { label: 'Độ cao cực đại ném đứng', value: '\\(h_{max}=\\frac{v_0^2}{2g}\\)' },
      { label: 'Ném ngang', value: '\\(x=v_0t,\\quad y=\\frac{1}{2}gt^2\\)' },
      { label: 'Thời gian ném ngang từ độ cao h', value: '\\(t=\\sqrt{\\frac{2h}{g}}\\)' },
      { label: 'Tầm xa ném ngang', value: '\\(L=v_0\\sqrt{\\frac{2h}{g}}\\)' },
      { label: 'Ném xiên - thành phần', value: '\\(v_{0x}=v_0\\cos\\alpha,\\quad v_{0y}=v_0\\sin\\alpha\\)' },
      { label: 'Tầm cao ném xiên', value: '\\(H=\\frac{v_0^2\\sin^2\\alpha}{2g}\\)' },
      { label: 'Tầm xa ném xiên cùng độ cao', value: '\\(L=\\frac{v_0^2\\sin2\\alpha}{g}\\)' },
      { label: 'Vận tốc tương đối', value: '\\(\\vec v_{13}=\\vec v_{12}+\\vec v_{23}\\)' },
    ],
  },
  {
    id: 'circular-motion',
    title: 'Chuyển động tròn đều và gia tốc hướng tâm',
    grade: '10',
    area: 'Cơ học',
    summary: 'Tần số, chu kỳ, tốc độ góc, lực hướng tâm; dùng nhiều trong con lắc, hạt mang điện, vệ tinh.',
    keywords: ['chuyen dong tron', 'toc do goc', 'huong tam', 'tan so', 'chu ky', '圆周运动'],
    formulas: [
      { label: 'Tần số - chu kỳ', value: '\\(f=\\frac1T,\\quad \\omega=2\\pi f=\\frac{2\\pi}{T}\\)' },
      { label: 'Tốc độ dài', value: '\\(v=\\omega r=\\frac{2\\pi r}{T}\\)' },
      { label: 'Góc quay', value: '\\(\\varphi=\\omega t\\)' },
      { label: 'Gia tốc hướng tâm', value: '\\(a_{ht}=\\frac{v^2}{r}=\\omega^2r\\)' },
      { label: 'Lực hướng tâm', value: '\\(F_{ht}=ma_{ht}=m\\frac{v^2}{r}=m\\omega^2r\\)' },
      { label: 'Liên hệ cung - góc', value: '\\(s=r\\varphi\\)', note: '\\(\\varphi\\) tính bằng radian.' },
      { label: 'Tốc độ góc của kim đồng hồ', value: '\\(\\omega=\\frac{2\\pi}{T}\\)' },
      { label: 'Độ biến thiên vận tốc', value: '\\(|\\Delta\\vec v|=2v\\sin\\frac{\\Delta\\varphi}{2}\\)' },
    ],
  },
  {
    id: 'dynamics-forces',
    title: 'Động lực học: Newton, ma sát, mặt phẳng nghiêng',
    grade: '10',
    area: 'Cơ học',
    summary: 'Nhận diện lực, áp dụng định luật II Newton, lực đàn hồi, ma sát, lực căng dây.',
    keywords: ['newton', 'luc', 'ma sat', 'mat phang nghieng', 'hooke', '牛顿', '摩擦力'],
    formulas: [
      { label: 'Định luật II Newton', value: '\\(\\sum\\vec F=m\\vec a\\)' },
      { label: 'Trọng lực', value: '\\(\\vec P=m\\vec g\\)' },
      { label: 'Lực đàn hồi Hooke', value: '\\(F_{dh}=k|\\Delta l|\\)' },
      { label: 'Lực ma sát trượt', value: '\\(F_{mst}=\\mu_t N\\)' },
      { label: 'Lực ma sát nghỉ cực đại', value: '\\(F_{msn,max}=\\mu_n N\\)' },
      { label: 'Mặt phẳng ngang', value: '\\(N=mg\\)' },
      { label: 'Mặt phẳng nghiêng', value: '\\(P_{\\parallel}=mg\\sin\\alpha,\\quad P_{\\perp}=mg\\cos\\alpha\\)' },
      { label: 'Phản lực trên mặt phẳng nghiêng', value: '\\(N=mg\\cos\\alpha\\)' },
      { label: 'Chuyển động trên mặt phẳng nghiêng có ma sát', value: '\\(a=g(\\sin\\alpha-\\mu\\cos\\alpha)\\)', note: 'Vật trượt xuống, lực ma sát hướng lên.' },
      { label: 'Hệ vật nối dây', value: '\\(a=\\frac{F_{ngoai}}{m_1+m_2+\\cdots}\\)' },
      { label: 'Thang máy', value: '\\(N=m(g\\pm a)\\)', note: 'Tăng tốc lên: \\(+a\\); tăng tốc xuống: \\(-a\\).' },
    ],
  },
  {
    id: 'gravitation-kepler',
    title: 'Hấp dẫn, trọng trường và vệ tinh',
    grade: '10',
    area: 'Cơ học',
    summary: 'Lực hấp dẫn, gia tốc trọng trường biến thiên theo độ cao, chuyển động vệ tinh tròn.',
    keywords: ['hap dan', 've tinh', 'kepler', 'trong truong', '万有引力'],
    formulas: [
      { label: 'Lực hấp dẫn', value: '\\(F=G\\frac{m_1m_2}{r^2}\\)' },
      { label: 'Gia tốc trọng trường tại cách tâm r', value: '\\(g=G\\frac{M}{r^2}\\)' },
      { label: 'Tại mặt đất', value: '\\(g_0=G\\frac{M}{R^2}\\)' },
      { label: 'Theo độ cao h', value: '\\(g_h=g_0(\\frac{R}{R+h})^2\\)' },
      { label: 'Trọng lượng biểu kiến', value: '\\(P_{bk}=N\\)' },
      { label: 'Vệ tinh tròn', value: '\\(G\\frac{Mm}{r^2}=m\\frac{v^2}{r}\\)' },
      { label: 'Tốc độ vệ tinh tròn', value: '\\(v=\\sqrt{\\frac{GM}{r}}\\)' },
      { label: 'Chu kỳ vệ tinh', value: '\\(T=2\\pi\\sqrt{\\frac{r^3}{GM}}\\)' },
      { label: 'Kepler III', value: '\\(\\frac{T_1^2}{T_2^2}=\\frac{r_1^3}{r_2^3}\\)' },
    ],
  },
  {
    id: 'work-energy-power',
    title: 'Công, công suất, động năng, thế năng',
    grade: '10',
    area: 'Cơ học',
    summary: 'Bảo toàn và biến thiên cơ năng, công của lực, hiệu suất, bài toán vật trượt/ném/lò xo.',
    keywords: ['cong', 'nang luong', 'co nang', 'dong nang', 'the nang', 'cong suat', '功', '能量'],
    formulas: [
      { label: 'Công của lực không đổi', value: '\\(A=Fs\\cos\\alpha\\)' },
      { label: 'Công suất', value: '\\(P=\\frac{A}{t}=Fv\\cos\\alpha\\)' },
      { label: 'Động năng', value: '\\(W_d=\\frac{1}{2}mv^2\\)' },
      { label: 'Định lý động năng', value: '\\(A_{\\sum F}=\\Delta W_d\\)' },
      { label: 'Thế năng trọng trường', value: '\\(W_t=mgh\\)' },
      { label: 'Thế năng đàn hồi', value: '\\(W_{dh}=\\frac{1}{2}k(\\Delta l)^2\\)' },
      { label: 'Cơ năng', value: '\\(W=W_d+W_t\\)' },
      { label: 'Bảo toàn cơ năng', value: '\\(W_1=W_2\\)', note: 'Chỉ dùng khi chỉ có lực thế sinh công.' },
      { label: 'Có lực không thế', value: '\\(A_{khong\\ the}=\\Delta W\\)' },
      { label: 'Hiệu suất', value: '\\(H=\\frac{A_{ich}}{A_{toan}}\\times100\\%=\\frac{P_{ich}}{P_{toan}}\\times100\\%\\)' },
      { label: 'Thế năng hấp dẫn tổng quát', value: '\\(W_t=-G\\frac{Mm}{r}\\)' },
    ],
  },
  {
    id: 'momentum-collisions',
    title: 'Động lượng, xung lượng và va chạm',
    grade: '10',
    area: 'Cơ học',
    summary: 'Dùng cho va chạm mềm, va chạm đàn hồi, nổ, hệ kín, súng đạn.',
    keywords: ['dong luong', 'xung luong', 'va cham', 'he kin', '动量', '碰撞'],
    formulas: [
      { label: 'Động lượng', value: '\\(\\vec p=m\\vec v\\)' },
      { label: 'Xung lượng của lực', value: '\\(\\vec I=\\vec F\\Delta t\\)' },
      { label: 'Định lý biến thiên động lượng', value: '\\(\\vec F\\Delta t=\\Delta\\vec p\\)' },
      { label: 'Bảo toàn động lượng', value: '\\(\\sum\\vec p_{truoc}=\\sum\\vec p_{sau}\\)' },
      { label: 'Va chạm mềm một chiều', value: '\\(v=\\frac{m_1v_1+m_2v_2}{m_1+m_2}\\)' },
      { label: 'Độ giảm động năng va chạm mềm', value: '\\(\\Delta W_d=W_{d,sau}-W_{d,truoc}<0\\)' },
      { label: 'Va chạm đàn hồi', value: '\\(\\sum\\vec p=\\text{const},\\quad \\sum W_d=\\text{const}\\)' },
      { label: 'Nổ từ trạng thái nghỉ', value: '\\(m_1\\vec v_1+m_2\\vec v_2+\\cdots=0\\)' },
      { label: 'Khối tâm', value: '\\(\\vec v_G=\\frac{m_1\\vec v_1+m_2\\vec v_2+\\cdots}{m_1+m_2+\\cdots}\\)' },
    ],
  },
  {
    id: 'rotation-equilibrium',
    title: 'Vật rắn, momen lực và cân bằng',
    grade: '10',
    area: 'Cơ học',
    summary: 'Cân bằng vật rắn, đòn bẩy, ngẫu lực, quy tắc momen, chuyển động quay cơ bản.',
    keywords: ['vat ran', 'momen luc', 'can bang', 'don bay', 'ngau luc', '力矩', '平衡'],
    formulas: [
      { label: 'Momen lực', value: '\\(M=Fd\\)' },
      { label: 'Điều kiện cân bằng tổng quát', value: '\\(\\sum\\vec F=0,\\quad \\sum M=0\\)' },
      { label: 'Quy tắc momen', value: '\\(F_1d_1=F_2d_2\\)' },
      { label: 'Ngẫu lực', value: '\\(M=Fd\\)', note: '\\(d\\) là khoảng cách giữa hai giá lực song song ngược chiều.' },
      { label: 'Trọng tâm hệ chất điểm', value: '\\(x_G=\\frac{\\sum m_ix_i}{\\sum m_i}\\)' },
      { label: 'Tốc độ góc trung bình', value: '\\(\\omega_{tb}=\\frac{\\Delta\\varphi}{\\Delta t}\\)' },
      { label: 'Gia tốc góc', value: '\\(\\gamma=\\frac{\\Delta\\omega}{\\Delta t}\\)' },
      { label: 'Liên hệ quay - dài', value: '\\(v=\\omega r,\\quad a_t=\\gamma r\\)' },
    ],
  },
  {
    id: 'fluids',
    title: 'Chất lỏng, áp suất và lực đẩy Archimedes',
    grade: '10',
    area: 'Chất lỏng',
    summary: 'Áp suất thủy tĩnh, bình thông nhau, lực đẩy, dòng chảy liên tục và Bernoulli cơ bản.',
    keywords: ['chat long', 'ap suat', 'archimedes', 'binh thong nhau', 'bernoulli', '压强', '浮力'],
    formulas: [
      { label: 'Áp suất', value: '\\(p=\\frac{F}{S}\\)' },
      { label: 'Áp suất thủy tĩnh', value: '\\(p=p_0+\\rho gh\\)' },
      { label: 'Lực đẩy Archimedes', value: '\\(F_A=\\rho_{long}gV_{chim}\\)' },
      { label: 'Vật nổi', value: '\\(F_A=P\\Rightarrow \\rho_{long}V_{chim}=\\rho_{vat}V_{vat}\\)' },
      { label: 'Lưu lượng', value: '\\(Q=Sv\\)' },
      { label: 'Phương trình liên tục', value: '\\(S_1v_1=S_2v_2\\)' },
      { label: 'Bernoulli', value: '\\(p+\\frac{1}{2}\\rho v^2+\\rho gh=\\text{const}\\)' },
      { label: 'Lực căng bề mặt', value: '\\(F=\\sigma l\\)' },
      { label: 'Độ chênh áp Laplace', value: '\\(\\Delta p=\\frac{2\\sigma}{R}\\)', note: 'Giọt cầu một mặt cong.' },
    ],
  },
  {
    id: 'thermal-calorimetry',
    title: 'Nhiệt học: nhiệt lượng, chuyển thể, nở vì nhiệt',
    grade: '10',
    area: 'Nhiệt học',
    summary: 'Cân bằng nhiệt, nóng chảy, hóa hơi, nở dài, nở khối; hay gặp trong bài toán tổng hợp.',
    keywords: ['nhiet luong', 'can bang nhiet', 'nong chay', 'hoa hoi', 'no vi nhiet', '热量'],
    formulas: [
      { label: 'Nhiệt lượng', value: '\\(Q=mc\\Delta t\\)' },
      { label: 'Nhiệt nóng chảy', value: '\\(Q=\\lambda m\\)' },
      { label: 'Nhiệt hóa hơi', value: '\\(Q=Lm\\)' },
      { label: 'Phương trình cân bằng nhiệt', value: '\\(\\sum Q_{toa}=\\sum Q_{thu}\\)' },
      { label: 'Nở dài', value: '\\(l=l_0(1+\\alpha\\Delta t)\\)' },
      { label: 'Độ nở dài', value: '\\(\\Delta l=\\alpha l_0\\Delta t\\)' },
      { label: 'Nở diện tích', value: '\\(S=S_0(1+2\\alpha\\Delta t)\\)' },
      { label: 'Nở thể tích', value: '\\(V=V_0(1+\\beta\\Delta t),\\quad \\beta\\approx3\\alpha\\)' },
      { label: 'Độ ẩm tỉ đối', value: '\\(f=\\frac{a}{A}\\times100\\%\\)' },
    ],
  },
  {
    id: 'ideal-gas-thermodynamics',
    title: 'Khí lý tưởng và nguyên lý nhiệt động lực học',
    grade: '10',
    area: 'Nhiệt học',
    summary: 'Định luật Boyle, Charles, Gay-Lussac, phương trình trạng thái, công của khí.',
    keywords: ['khi ly tuong', 'boyle', 'charles', 'nhiet dong luc', '理想气体'],
    formulas: [
      { label: 'Boyle - Mariotte', value: '\\(pV=\\text{const}\\quad(T=\\text{const})\\)' },
      { label: 'Charles', value: '\\(\\frac{V}{T}=\\text{const}\\quad(p=\\text{const})\\)' },
      { label: 'Gay-Lussac', value: '\\(\\frac{p}{T}=\\text{const}\\quad(V=\\text{const})\\)' },
      { label: 'Trạng thái khí lý tưởng', value: '\\(\\frac{pV}{T}=\\text{const}\\)' },
      { label: 'Clapeyron - Mendeleev', value: '\\(pV=nRT=\\frac{m}{M}RT\\)' },
      { label: 'Động năng tịnh tiến phân tử', value: '\\(\\bar W_d=\\frac32kT\\)' },
      { label: 'Nội năng khí đơn nguyên tử', value: '\\(U=\\frac32nRT\\)' },
      { label: 'Công của khí đẳng áp', value: '\\(A=p\\Delta V\\)' },
      { label: 'Nguyên lý I', value: '\\(\\Delta U=Q+A\\)', note: '\\(A\\) là công ngoại lực thực hiện lên khí theo quy ước phổ thông.' },
      { label: 'Hiệu suất động cơ nhiệt', value: '\\(H=\\frac{A}{Q_1}=1-\\frac{Q_2}{Q_1}\\)' },
      { label: 'Carnot', value: '\\(H_{max}=1-\\frac{T_2}{T_1}\\)' },
    ],
  },
  {
    id: 'electrostatics',
    title: 'Điện tích, lực Coulomb và điện trường',
    grade: '11',
    area: 'Điện học',
    summary: 'Lực giữa hai điện tích, cường độ điện trường, nguyên lý chồng chất, điện trường đều.',
    keywords: ['dien tich', 'coulomb', 'dien truong', 'field', '静电场', '库仑定律'],
    formulas: [
      { label: 'Định luật Coulomb', value: '\\(F=k\\frac{|q_1q_2|}{\\varepsilon r^2}\\)' },
      { label: 'Cường độ điện trường', value: '\\(\\vec E=\\frac{\\vec F}{q}\\)' },
      { label: 'Điện trường điện tích điểm', value: '\\(E=k\\frac{|Q|}{\\varepsilon r^2}\\)' },
      { label: 'Lực điện', value: '\\(\\vec F=q\\vec E\\)' },
      { label: 'Chồng chất điện trường', value: '\\(\\vec E=\\vec E_1+\\vec E_2+\\cdots\\)' },
      { label: 'Điện trường đều', value: '\\(E=\\frac{U}{d}\\)' },
      { label: 'Công của lực điện trong điện trường đều', value: '\\(A=qEd\\)' },
      { label: 'Mật độ điện tích mặt', value: '\\(\\sigma=\\frac{q}{S}\\)' },
      { label: 'Thông lượng điện trường', value: '\\(\\Phi=ES\\cos\\alpha\\)' },
    ],
  },
  {
    id: 'potential-capacitor',
    title: 'Điện thế, hiệu điện thế và tụ điện',
    grade: '11',
    area: 'Điện học',
    summary: 'Liên hệ công - hiệu điện thế, thế năng điện, tụ điện phẳng, ghép tụ điện.',
    keywords: ['dien the', 'hieu dien the', 'tu dien', 'dien dung', '电势', '电容'],
    formulas: [
      { label: 'Hiệu điện thế', value: '\\(U_{MN}=V_M-V_N=\\frac{A_{MN}}{q}\\)' },
      { label: 'Công của lực điện', value: '\\(A_{MN}=qU_{MN}\\)' },
      { label: 'Điện thế điện tích điểm', value: '\\(V=k\\frac{Q}{\\varepsilon r}\\)' },
      { label: 'Thế năng điện', value: '\\(W=qV\\)' },
      { label: 'Liên hệ E và U', value: '\\(E=\\frac{U}{d}\\)' },
      { label: 'Điện dung', value: '\\(C=\\frac{Q}{U}\\)' },
      { label: 'Tụ điện phẳng', value: '\\(C=\\frac{\\varepsilon\\varepsilon_0S}{d}\\)' },
      { label: 'Năng lượng tụ điện', value: '\\(W=\\frac{1}{2}CU^2=\\frac{Q^2}{2C}=\\frac{1}{2}QU\\)' },
      { label: 'Ghép song song', value: '\\(C_b=C_1+C_2+\\cdots\\)' },
      { label: 'Ghép nối tiếp', value: '\\(\\frac1{C_b}=\\frac1{C_1}+\\frac1{C_2}+\\cdots\\)' },
      { label: 'Nối tiếp cùng điện tích', value: '\\(Q_1=Q_2=\\cdots=Q\\)' },
      { label: 'Song song cùng hiệu điện thế', value: '\\(U_1=U_2=\\cdots=U\\)' },
    ],
  },
  {
    id: 'dc-current',
    title: 'Dòng điện không đổi, điện trở và mạch điện',
    grade: '11',
    area: 'Điện học',
    summary: 'Định luật Ohm, ghép điện trở, điện năng, công suất, mạch cầu cơ bản.',
    keywords: ['dong dien', 'ohm', 'dien tro', 'mach dien', 'cong suat dien', '电流', '欧姆定律'],
    formulas: [
      { label: 'Cường độ dòng điện', value: '\\(I=\\frac{\\Delta q}{\\Delta t}\\)' },
      { label: 'Định luật Ohm đoạn mạch', value: '\\(I=\\frac{U}{R}\\)' },
      { label: 'Điện trở dây dẫn', value: '\\(R=\\rho\\frac{l}{S}\\)' },
      { label: 'Phụ thuộc nhiệt độ', value: '\\(R=R_0[1+\\alpha(t-t_0)]\\)' },
      { label: 'Nối tiếp điện trở', value: '\\(R_b=R_1+R_2+\\cdots\\)' },
      { label: 'Song song điện trở', value: '\\(\\frac1{R_b}=\\frac1{R_1}+\\frac1{R_2}+\\cdots\\)' },
      { label: 'Hai điện trở song song', value: '\\(R_b=\\frac{R_1R_2}{R_1+R_2}\\)' },
      { label: 'Công dòng điện', value: '\\(A=UIt\\)' },
      { label: 'Công suất điện', value: '\\(P=UI=I^2R=\\frac{U^2}{R}\\)' },
      { label: 'Định luật Joule - Lenz', value: '\\(Q=I^2Rt\\)' },
      { label: 'Điều kiện cầu cân bằng', value: '\\(\\frac{R_1}{R_2}=\\frac{R_3}{R_4}\\)' },
    ],
  },
  {
    id: 'source-closed-circuit',
    title: 'Nguồn điện, máy thu và định luật Ohm toàn mạch',
    grade: '11',
    area: 'Điện học',
    summary: 'Suất điện động, điện trở trong, hiệu suất nguồn, ghép nguồn, máy thu điện.',
    keywords: ['nguon dien', 'suat dien dong', 'dien tro trong', 'toan mach', '电源'],
    formulas: [
      { label: 'Suất điện động', value: '\\(\\mathcal E=\\frac{A_{nguon}}{q}\\)' },
      { label: 'Ohm toàn mạch', value: '\\(I=\\frac{\\mathcal E}{R+r}\\)' },
      { label: 'Hiệu điện thế mạch ngoài', value: '\\(U=\\mathcal E-Ir=IR\\)' },
      { label: 'Đoạn mạch có nguồn', value: '\\(U_{AB}=\\mathcal E-I(R+r)\\)', note: 'Dấu tùy chiều đi qua nguồn và chiều dòng điện.' },
      { label: 'Công suất nguồn', value: '\\(P_{nguon}=\\mathcal EI\\)' },
      { label: 'Công suất có ích', value: '\\(P_{ich}=UI=I^2R\\)' },
      { label: 'Hiệu suất nguồn', value: '\\(H=\\frac{U}{\\mathcal E}=\\frac{R}{R+r}\\)' },
      { label: 'Ghép nguồn nối tiếp', value: '\\(\\mathcal E_b=n\\mathcal E,\\quad r_b=nr\\)' },
      { label: 'Ghép nguồn song song giống nhau', value: '\\(\\mathcal E_b=\\mathcal E,\\quad r_b=\\frac{r}{n}\\)' },
      { label: 'Máy thu điện', value: '\\(U=\\mathcal E^{\\prime}+Ir^{\\prime}\\)' },
    ],
  },
  {
    id: 'current-in-media',
    title: 'Dòng điện trong các môi trường',
    grade: '11',
    area: 'Điện học',
    summary: 'Kim loại, điện phân, chất khí, chân không, bán dẫn; công thức hay hỏi trong đề tổng hợp.',
    keywords: ['dien phan', 'faraday', 'ban dan', 'chat khi', 'moi truong', '法拉第电解'],
    formulas: [
      { label: 'Mật độ dòng điện', value: '\\(j=\\frac{I}{S}\\)' },
      { label: 'Vận tốc trôi', value: '\\(I=n|q|Sv_d\\)' },
      { label: 'Điện trở kim loại theo nhiệt độ', value: '\\(R=R_0(1+\\alpha\\Delta t)\\)' },
      { label: 'Định luật Faraday điện phân', value: '\\(m=\\frac{A}{nF}It\\)' },
      { label: 'Hằng số Faraday', value: '\\(F=96500\\,\\text{C/mol}\\)' },
      { label: 'Điện lượng điện phân', value: '\\(q=It\\)' },
      { label: 'Điện trở nhiệt NTC', value: '\\(R\\) giảm khi \\(t\\) tăng', note: 'Dùng nhận diện định tính.' },
      { label: 'Diot bán dẫn lý tưởng', value: '\\(I\\approx0\\) khi phân cực ngược, dẫn khi phân cực thuận.' },
    ],
  },
  {
    id: 'magnetic-field-force',
    title: 'Từ trường, lực từ và chuyển động hạt mang điện',
    grade: '11',
    area: 'Từ học',
    summary: 'Cảm ứng từ, lực từ lên dây dẫn, Lorentz, bán kính quỹ đạo, momen ngẫu lực từ.',
    keywords: ['tu truong', 'luc tu', 'lorentz', 'cam ung tu', 'magnetic', '磁场', '洛伦兹力'],
    formulas: [
      { label: 'Lực từ lên dây dẫn', value: '\\(F=BIl\\sin\\alpha\\)' },
      { label: 'Lực Lorentz', value: '\\(F=|q|vB\\sin\\alpha\\)' },
      { label: 'Bán kính quỹ đạo tròn', value: '\\(R=\\frac{mv}{|q|B}\\)' },
      { label: 'Chu kỳ chuyển động tròn trong B', value: '\\(T=\\frac{2\\pi m}{|q|B}\\)' },
      { label: 'Từ trường dây thẳng dài', value: '\\(B=2\\times10^{-7}\\frac{I}{r}\\)' },
      { label: 'Từ trường vòng dây tròn', value: '\\(B=2\\pi\\times10^{-7}\\frac{NI}{R}\\)' },
      { label: 'Ống dây dài', value: '\\(B=4\\pi\\times10^{-7}nI\\)' },
      { label: 'Momen ngẫu lực từ', value: '\\(M=NBIS\\sin\\alpha\\)' },
      { label: 'Từ thông', value: '\\(\\Phi=BS\\cos\\alpha\\)' },
      { label: 'Quy tắc chồng chất', value: '\\(\\vec B=\\vec B_1+\\vec B_2+\\cdots\\)' },
    ],
  },
  {
    id: 'electromagnetic-induction',
    title: 'Cảm ứng điện từ và tự cảm',
    grade: '11',
    area: 'Từ học',
    summary: 'Faraday, Lenz, suất điện động cảm ứng, tự cảm, năng lượng từ trường.',
    keywords: ['cam ung dien tu', 'faraday', 'lenz', 'tu cam', '电磁感应'],
    formulas: [
      { label: 'Từ thông', value: '\\(\\Phi=BS\\cos\\alpha\\)' },
      { label: 'Faraday', value: '\\(|e_c|=\\lvert\\frac{\\Delta\\Phi}{\\Delta t}\\rvert\\)' },
      { label: 'Vòng dây N vòng', value: '\\(|e_c|=N\\lvert\\frac{\\Delta\\Phi}{\\Delta t}\\rvert\\)' },
      { label: 'Thanh dẫn chuyển động cắt B', value: '\\(e=Blv\\sin\\alpha\\)' },
      { label: 'Dòng cảm ứng', value: '\\(I_c=\\frac{e_c}{R}\\)' },
      { label: 'Tự cảm', value: '\\(e_{tc}=-L\\frac{\\Delta I}{\\Delta t}\\)' },
      { label: 'Độ tự cảm ống dây', value: '\\(L=4\\pi\\times10^{-7}\\frac{N^2S}{l}\\)' },
      { label: 'Năng lượng từ trường', value: '\\(W=\\frac{1}{2}LI^2\\)' },
      { label: 'Mật độ năng lượng từ trường', value: '\\(w=\\frac{B^2}{2\\mu}\\)' },
    ],
    notes: ['Dấu trừ trong Faraday-Lenz chỉ chiều chống lại nguyên nhân sinh ra cảm ứng.'],
  },
  {
    id: 'geometrical-optics',
    title: 'Khúc xạ, phản xạ toàn phần và lăng kính',
    grade: '11',
    area: 'Quang hình',
    summary: 'Định luật Snell, góc giới hạn, lăng kính, đường truyền ánh sáng qua mặt phân cách.',
    keywords: ['khuc xa', 'phan xa toan phan', 'lang kinh', 'snell', '折射', '全反射'],
    formulas: [
      { label: 'Chiết suất tuyệt đối', value: '\\(n=\\frac{c}{v}\\)' },
      { label: 'Snell', value: '\\(n_1\\sin i=n_2\\sin r\\)' },
      { label: 'Chiết suất tỉ đối', value: '\\(n_{21}=\\frac{n_2}{n_1}=\\frac{\\sin i}{\\sin r}\\)' },
      { label: 'Góc giới hạn', value: '\\(\\sin i_{gh}=\\frac{n_2}{n_1}\\quad(n_1>n_2)\\)' },
      { label: 'Điều kiện phản xạ toàn phần', value: '\\(n_1>n_2,\\quad i\\ge i_{gh}\\)' },
      { label: 'Lăng kính - góc lệch', value: '\\(D=i_1+i_2-A\\)' },
      { label: 'Lăng kính - hình học', value: '\\(r_1+r_2=A\\)' },
      { label: 'Góc lệch cực tiểu', value: '\\(i_1=i_2,\\quad r_1=r_2=\\frac{A}{2}\\)' },
      { label: 'Chiết suất lăng kính lúc lệch cực tiểu', value: '\\(n=\\frac{\\sin\\frac{A+D_{min}}{2}}{\\sin\\frac{A}{2}}\\)' },
    ],
  },
  {
    id: 'lenses-mirrors-eye',
    title: 'Thấu kính, gương cầu và mắt',
    grade: '11',
    area: 'Quang hình',
    summary: 'Công thức thấu kính mỏng, độ phóng đại, độ tụ, mắt cận/viễn/lão, kính lúp.',
    keywords: ['thau kinh', 'guong cau', 'mat', 'kinh lup', 'do tu', '透镜', '眼睛'],
    formulas: [
      { label: 'Thấu kính mỏng', value: '\\(\\frac1f=\\frac1d+\\frac1{d^{\\prime}}\\)' },
      { label: 'Độ phóng đại ảnh', value: '\\(k=-\\frac{d^{\\prime}}{d}=\\frac{A^{\\prime}B^{\\prime}}{AB}\\)' },
      { label: 'Độ tụ thấu kính', value: '\\(D=\\frac1f\\)', note: '\\(f\\) tính bằng mét, \\(D\\) tính bằng điốp.' },
      { label: 'Ghép thấu kính sát nhau', value: '\\(D=D_1+D_2\\)' },
      { label: 'Gương cầu', value: '\\(\\frac{1}{f}=\\frac{1}{d}+\\frac{1}{d^{\\prime}},\\quad f=\\frac{R}{2}\\)' },
      { label: 'Mắt không điều tiết', value: '\\(f_{max}=OV\\)' },
      { label: 'Kính sửa cận thị', value: '\\(f_k=-OC_v\\)', note: 'Khi đeo sát mắt để nhìn vật ở vô cực.' },
      { label: 'Kính sửa viễn thị', value: '\\(d^{\\prime}=-OC_c\\)', note: 'Vật ở cực cận mới, ảnh ảo tại cực cận của mắt.' },
      { label: 'Số bội giác kính lúp ngắn gọn', value: '\\(G=\\frac{\\tan\\alpha}{\\tan\\alpha_0}\\)' },
      { label: 'Kính lúp ngắm chừng vô cực', value: '\\(G_\\infty=\\frac{D}{f}\\)', note: '\\(D=25\\,\\text{cm}\\).' },
    ],
  },
  {
    id: 'harmonic-oscillation',
    title: 'Dao động điều hòa: phương trình và đại lượng',
    grade: '12',
    area: 'Dao động',
    summary: 'Lý thuyết gốc lớp 12: li độ, vận tốc, gia tốc, pha, thời gian, đồ thị.',
    keywords: ['dao dong dieu hoa', 'li do', 'pha', 'van toc', 'gia toc', '简谐振动'],
    formulas: [
      { label: 'Phương trình li độ', value: '\\(x=A\\cos(\\omega t+\\varphi)\\)' },
      { label: 'Vận tốc', value: '\\(v=-\\omega A\\sin(\\omega t+\\varphi)\\)' },
      { label: 'Gia tốc', value: '\\(a=-\\omega^2A\\cos(\\omega t+\\varphi)=-\\omega^2x\\)' },
      { label: 'Liên hệ độc lập thời gian', value: '\\(\\frac{x^2}{A^2}+\\frac{v^2}{\\omega^2A^2}=1\\)' },
      { label: 'Tốc độ cực đại', value: '\\(v_{max}=\\omega A\\)' },
      { label: 'Gia tốc cực đại', value: '\\(a_{max}=\\omega^2A\\)' },
      { label: 'Chu kỳ - tần số', value: '\\(T=\\frac{2\\pi}{\\omega},\\quad f=\\frac1T\\)' },
      { label: 'Quãng đường trong một chu kỳ', value: '\\(S_T=4A\\)' },
      { label: 'Cơ năng', value: '\\(W=\\frac{1}{2}m\\omega^2A^2\\)' },
      { label: 'Động năng', value: '\\(W_d=\\frac{1}{2}mv^2=\\frac{1}{2}m\\omega^2(A^2-x^2)\\)' },
      { label: 'Thế năng', value: '\\(W_t=\\frac{1}{2}m\\omega^2x^2\\)' },
      { label: 'Lực kéo về', value: '\\(F=-kx=-m\\omega^2x\\)' },
    ],
  },
  {
    id: 'spring-pendulum',
    title: 'Con lắc lò xo và con lắc đơn',
    grade: '12',
    area: 'Dao động',
    summary: 'Chu kỳ, năng lượng, lực đàn hồi, chiều dài con lắc; phần hay ra trong đề THPT.',
    keywords: ['con lac lo xo', 'con lac don', 'lo xo', 'dao dong', 'pendulum', '弹簧', '单摆'],
    formulas: [
      { label: 'Tần số góc lò xo', value: '\\(\\omega=\\sqrt{\\frac{k}{m}}\\)' },
      { label: 'Chu kỳ lò xo', value: '\\(T=2\\pi\\sqrt{\\frac{m}{k}}\\)' },
      { label: 'Độ giãn cân bằng lò xo thẳng đứng', value: '\\(\\Delta l_0=\\frac{mg}{k}\\)' },
      { label: 'Lực đàn hồi', value: '\\(F_{dh}=k|\\Delta l|\\)' },
      { label: 'Lực kéo về lò xo', value: '\\(F_{kv}=-kx\\)' },
      { label: 'Năng lượng lò xo', value: '\\(W=\\frac{1}{2}kA^2\\)' },
      { label: 'Tần số góc con lắc đơn', value: '\\(\\omega=\\sqrt{\\frac{g}{l}}\\)' },
      { label: 'Chu kỳ con lắc đơn', value: '\\(T=2\\pi\\sqrt{\\frac{l}{g}}\\)' },
      { label: 'Vận tốc con lắc đơn', value: '\\(v=\\sqrt{2gl(\\cos\\alpha-\\cos\\alpha_0)}\\)' },
      { label: 'Lực căng dây', value: '\\(T_d=mg(3\\cos\\alpha-2\\cos\\alpha_0)\\)' },
      { label: 'Biến thiên chu kỳ theo nhiệt độ', value: '\\(\\frac{\\Delta T}{T}=\\frac{1}{2}\\alpha\\Delta t\\)' },
      { label: 'Biến thiên chu kỳ theo độ cao', value: '\\(\\frac{\\Delta T}{T}=\\frac{h}{R}\\)' },
    ],
  },
  {
    id: 'mechanical-waves',
    title: 'Sóng cơ, giao thoa và sóng dừng',
    grade: '12',
    area: 'Sóng cơ',
    summary: 'Phương trình sóng, độ lệch pha, giao thoa hai nguồn, sóng dừng trên dây và âm học.',
    keywords: ['song co', 'giao thoa', 'song dung', 'buoc song', 'am hoc', '机械波', '驻波'],
    formulas: [
      { label: 'Bước sóng', value: '\\(\\lambda=vT=\\frac{v}{f}\\)' },
      { label: 'Phương trình sóng', value: '\\(u_M=A\\cos(\\omega t-\\frac{2\\pi x}{\\lambda}+\\varphi)\\)' },
      { label: 'Độ lệch pha hai điểm', value: '\\(\\Delta\\varphi=\\frac{2\\pi d}{\\lambda}\\)' },
      { label: 'Cùng pha', value: '\\(d=k\\lambda\\)' },
      { label: 'Ngược pha', value: '\\(d=(k+\\frac{1}{2})\\lambda\\)' },
      { label: 'Giao thoa cực đại', value: '\\(d_2-d_1=k\\lambda\\)' },
      { label: 'Giao thoa cực tiểu', value: '\\(d_2-d_1=(k+\\frac{1}{2})\\lambda\\)' },
      { label: 'Sóng dừng hai đầu cố định', value: '\\(l=k\\frac{\\lambda}{2}\\)' },
      { label: 'Một đầu cố định một đầu tự do', value: '\\(l=(2k+1)\\frac{\\lambda}{4}\\)' },
      { label: 'Khoảng cách nút - bụng liên tiếp', value: '\\(\\frac{\\lambda}{4}\\)' },
      { label: 'Khoảng cách hai nút liên tiếp', value: '\\(\\frac{\\lambda}{2}\\)' },
    ],
  },
  {
    id: 'sound-waves',
    title: 'Sóng âm, mức cường độ âm và hiệu ứng Doppler',
    grade: '12',
    area: 'Sóng cơ',
    summary: 'Cường độ âm, mức cường độ âm, quan hệ công suất - khoảng cách, Doppler cơ bản.',
    keywords: ['song am', 'muc cuong do am', 'doppler', 'cuong do am', '声波', '多普勒'],
    formulas: [
      { label: 'Cường độ âm', value: '\\(I=\\frac{P}{S}\\)' },
      { label: 'Nguồn điểm', value: '\\(I=\\frac{P}{4\\pi r^2}\\)' },
      { label: 'Mức cường độ âm', value: '\\(L=10\\log\\frac{I}{I_0}\\,\\text{dB}\\)' },
      { label: 'Chuẩn nghe', value: '\\(I_0=10^{-12}\\,\\text{W/m}^2\\)' },
      { label: 'Chênh lệch mức âm', value: '\\(L_2-L_1=10\\log\\frac{I_2}{I_1}\\)' },
      { label: 'Tăng gấp n lần cường độ', value: '\\(\\Delta L=10\\log n\\)' },
      { label: 'Quan hệ khoảng cách', value: '\\(L_2-L_1=20\\log\\frac{r_1}{r_2}\\)' },
      { label: 'Doppler tổng quát', value: '\\(f^{\\prime}=f\\frac{v\\pm v_M}{v\\mp v_S}\\)' },
      { label: 'Họa âm', value: '\\(f_n=nf_1\\)' },
    ],
  },
  {
    id: 'ac-rlc',
    title: 'Dòng điện xoay chiều RLC',
    grade: '12',
    area: 'Điện xoay chiều',
    summary: 'Giá trị hiệu dụng, cảm kháng, dung kháng, tổng trở, công suất, cộng hưởng.',
    keywords: ['dien xoay chieu', 'rlc', 'cong huong', 'cong suat', '交流电', '共振'],
    formulas: [
      { label: 'Điện áp - dòng điện tức thời', value: '\\(u=U_0\\cos(\\omega t+\\varphi_u),\\quad i=I_0\\cos(\\omega t+\\varphi_i)\\)' },
      { label: 'Giá trị hiệu dụng', value: '\\(U=\\frac{U_0}{\\sqrt2},\\quad I=\\frac{I_0}{\\sqrt2}\\)' },
      { label: 'Cảm kháng', value: '\\(Z_L=\\omega L\\)' },
      { label: 'Dung kháng', value: '\\(Z_C=\\frac1{\\omega C}\\)' },
      { label: 'Tổng trở RLC nối tiếp', value: '\\(Z=\\sqrt{R^2+(Z_L-Z_C)^2}\\)' },
      { label: 'Định luật Ohm AC', value: '\\(I=\\frac{U}{Z}\\)' },
      { label: 'Độ lệch pha', value: '\\(\\tan\\varphi=\\frac{Z_L-Z_C}{R}\\)' },
      { label: 'Hệ số công suất', value: '\\(\\cos\\varphi=\\frac{R}{Z}\\)' },
      { label: 'Công suất tiêu thụ', value: '\\(P=UI\\cos\\varphi=I^2R=\\frac{U^2R}{Z^2}\\)' },
      { label: 'Cộng hưởng', value: '\\(Z_L=Z_C\\Leftrightarrow \\omega_0=\\frac1{\\sqrt{LC}}\\)' },
      { label: 'Tần số cộng hưởng', value: '\\(f_0=\\frac1{2\\pi\\sqrt{LC}}\\)' },
      { label: 'Hệ số phẩm chất', value: '\\(Q=\\frac{\\omega_0L}{R}=\\frac1{\\omega_0CR}\\)' },
      { label: 'Máy biến áp lý tưởng', value: '\\(\\frac{U_1}{U_2}=\\frac{N_1}{N_2}=\\frac{I_2}{I_1}\\)' },
      { label: 'Truyền tải điện', value: '\\(\\Delta P=I^2R=\\frac{P^2R}{U^2\\cos^2\\varphi}\\)' },
    ],
  },
  {
    id: 'electromagnetic-oscillation-waves',
    title: 'Mạch dao động LC và sóng điện từ',
    grade: '12',
    area: 'Điện từ',
    summary: 'Dao động điện từ tự do, năng lượng điện từ, bước sóng máy thu phát.',
    keywords: ['mach lc', 'song dien tu', 'dao dong dien tu', 'dien tu', '电磁波'],
    formulas: [
      { label: 'Tần số góc LC', value: '\\(\\omega=\\frac1{\\sqrt{LC}}\\)' },
      { label: 'Chu kỳ LC', value: '\\(T=2\\pi\\sqrt{LC}\\)' },
      { label: 'Tần số LC', value: '\\(f=\\frac1{2\\pi\\sqrt{LC}}\\)' },
      { label: 'Điện tích', value: '\\(q=Q_0\\cos(\\omega t+\\varphi)\\)' },
      { label: 'Dòng điện', value: '\\(i=q^{\\prime}=-\\omega Q_0\\sin(\\omega t+\\varphi)\\)' },
      { label: 'Dòng cực đại', value: '\\(I_0=\\omega Q_0\\)' },
      { label: 'Năng lượng điện trường', value: '\\(W_C=\\frac{q^2}{2C}=\\frac{1}{2}Cu^2\\)' },
      { label: 'Năng lượng từ trường', value: '\\(W_L=\\frac{1}{2}Li^2\\)' },
      { label: 'Năng lượng mạch', value: '\\(W=\\frac{Q_0^2}{2C}=\\frac{1}{2}LI_0^2\\)' },
      { label: 'Bước sóng thu phát', value: '\\(\\lambda=cT=2\\pi c\\sqrt{LC}\\)' },
    ],
  },
  {
    id: 'wave-optics',
    title: 'Sóng ánh sáng, giao thoa và quang phổ',
    grade: '12',
    area: 'Quang sóng',
    summary: 'Young, khoảng vân, vị trí vân, tán sắc, máy quang phổ, tia hồng ngoại - tử ngoại.',
    keywords: ['song anh sang', 'giao thoa anh sang', 'young', 'khoang van', 'quang pho', '光的干涉'],
    formulas: [
      { label: 'Khoảng vân Young', value: '\\(i=\\frac{\\lambda D}{a}\\)' },
      { label: 'Vị trí vân sáng', value: '\\(x_s=ki\\)' },
      { label: 'Vị trí vân tối', value: '\\(x_t=(k+\\frac{1}{2})i\\)' },
      { label: 'Bước sóng trong môi trường', value: '\\(\\lambda=\\frac{\\lambda_0}{n}\\)' },
      { label: 'Tần số ánh sáng', value: '\\(f=\\frac{c}{\\lambda}\\)' },
      { label: 'Chênh lệch đường đi', value: '\\(\\Delta d=\\frac{ax}{D}\\)' },
      { label: 'Vân sáng theo lệch đường', value: '\\(\\Delta d=k\\lambda\\)' },
      { label: 'Vân tối theo lệch đường', value: '\\(\\Delta d=(k+\\frac{1}{2})\\lambda\\)' },
      { label: 'Năng lượng photon', value: '\\(\\varepsilon=hf=\\frac{hc}{\\lambda}\\)' },
      { label: 'Tán sắc', value: '\\(n_{tim}>n_{do}\\Rightarrow D_{tim}>D_{do}\\)' },
    ],
  },
  {
    id: 'photoelectric-quantum',
    title: 'Lượng tử ánh sáng và hiện tượng quang điện',
    grade: '12',
    area: 'Lượng tử',
    summary: 'Photon, công thoát, giới hạn quang điện, Einstein, tia X cơ bản.',
    keywords: ['quang dien', 'photon', 'einstein', 'cong thoat', 'luong tu', '光电效应'],
    formulas: [
      { label: 'Năng lượng photon', value: '\\(\\varepsilon=hf=\\frac{hc}{\\lambda}\\)' },
      { label: 'Giới hạn quang điện', value: '\\(\\lambda_0=\\frac{hc}{A}\\)' },
      { label: 'Điều kiện quang điện ngoài', value: '\\(\\lambda\\le\\lambda_0\\)' },
      { label: 'Einstein quang điện', value: '\\(hf=A+\\frac{1}{2}mv_{0max}^2\\)' },
      { label: 'Hiệu điện thế hãm', value: '\\(eU_h=\\frac{1}{2}mv_{0max}^2\\)' },
      { label: 'Dòng quang điện bão hòa', value: '\\(I_{bh}=ne\\)' },
      { label: 'Công suất chùm photon', value: '\\(P=N\\varepsilon\\)' },
      { label: 'Hiệu suất lượng tử', value: '\\(H=\\frac{N_e}{N_{photon}}\\times100\\%\\)' },
      { label: 'Tiên đề Bohr hấp thụ/phát xạ', value: '\\(hf=E_m-E_n\\)' },
      { label: 'Tia X ngắn nhất', value: '\\(\\lambda_{min}=\\frac{hc}{eU}\\)' },
    ],
  },
  {
    id: 'atomic-physics',
    title: 'Mẫu nguyên tử Bohr và quang phổ hiđrô',
    grade: '12',
    area: 'Lượng tử',
    summary: 'Mức năng lượng, bán kính quỹ đạo, dãy Lyman/Balmer/Paschen, photon phát xạ.',
    keywords: ['bohr', 'hidro', 'quang pho', 'nguyen tu', 'bo', '氢原子'],
    formulas: [
      { label: 'Mức năng lượng hiđrô', value: '\\(E_n=-\\frac{13.6}{n^2}\\,\\text{eV}\\)' },
      { label: 'Bán kính quỹ đạo', value: '\\(r_n=n^2r_0,\\quad r_0=5.3\\times10^{-11}\\,\\text{m}\\)' },
      { label: 'Photon phát xạ/hấp thụ', value: '\\(hf=|E_m-E_n|\\)' },
      { label: 'Bước sóng photon', value: '\\(\\lambda=\\frac{hc}{|E_m-E_n|}\\)' },
      { label: 'Lyman', value: '\\(n\\to1\\)', note: 'Vùng tử ngoại.' },
      { label: 'Balmer', value: '\\(n\\to2\\)', note: 'Có các vạch nhìn thấy.' },
      { label: 'Paschen', value: '\\(n\\to3\\)', note: 'Vùng hồng ngoại.' },
      { label: 'Đổi eV sang J', value: '\\(1\\,\\text{eV}=1.6\\times10^{-19}\\,\\text{J}\\)' },
    ],
  },
  {
    id: 'nuclear-physics',
    title: 'Hạt nhân, phóng xạ và năng lượng liên kết',
    grade: '12',
    area: 'Hạt nhân',
    summary: 'Cấu tạo hạt nhân, độ hụt khối, năng lượng liên kết, phóng xạ, phản ứng hạt nhân.',
    keywords: ['hat nhan', 'phong xa', 'chu ky ban ra', 'nang luong lien ket', '核物理'],
    formulas: [
      { label: 'Ký hiệu hạt nhân', value: '\\({}^{A}_{Z}X\\)', note: '\\(A=Z+N\\).' },
      { label: 'Độ hụt khối', value: '\\(\\Delta m=Zm_p+Nm_n-m_X\\)' },
      { label: 'Năng lượng liên kết', value: '\\(W_{lk}=\\Delta mc^2\\)' },
      { label: 'Năng lượng liên kết riêng', value: '\\(\\varepsilon=\\frac{W_{lk}}{A}\\)' },
      { label: 'Đổi khối lượng - năng lượng', value: '\\(1u=931.5\\,\\text{MeV}/c^2\\)' },
      { label: 'Định luật phóng xạ', value: '\\(N=N_0e^{-\\lambda t}=N_0(\\frac{1}{2})^{t/T}\\)' },
      { label: 'Số hạt đã phân rã', value: '\\(\\Delta N=N_0-N\\)' },
      { label: 'Độ phóng xạ', value: '\\(H=\\lambda N\\)' },
      { label: 'Chu kỳ bán rã', value: '\\(T=\\frac{\\ln2}{\\lambda}\\)' },
      { label: 'Khối lượng còn lại', value: '\\(m=m_0(\\frac{1}{2})^{t/T}\\)' },
      { label: 'Năng lượng phản ứng', value: '\\(Q=(m_{truoc}-m_{sau})c^2\\)' },
      { label: 'Bảo toàn trong phản ứng', value: '\\(\\sum A_{truoc}=\\sum A_{sau},\\quad \\sum Z_{truoc}=\\sum Z_{sau}\\)' },
    ],
  },
  {
    id: 'relativity-modern',
    title: 'Tương đối hẹp và hệ thức hiện đại hay gặp',
    grade: '12',
    area: 'Vật lý hiện đại',
    summary: 'Một số công thức hiện đại dùng khi đề có câu hỏi nâng cao về năng lượng, khối lượng, hạt.',
    keywords: ['tuong doi', 'einstein', 'nang luong nghi', 'hien dai', '相对论'],
    formulas: [
      { label: 'Hệ số Lorentz', value: '\\(\\gamma=\\frac1{\\sqrt{1-\\frac{v^2}{c^2}}}\\)' },
      { label: 'Khối lượng tương đối', value: '\\(m=\\gamma m_0\\)' },
      { label: 'Năng lượng nghỉ', value: '\\(E_0=m_0c^2\\)' },
      { label: 'Năng lượng toàn phần', value: '\\(E=mc^2=\\gamma m_0c^2\\)' },
      { label: 'Động năng tương đối', value: '\\(W_d=(m-m_0)c^2\\)' },
      { label: 'Hệ thức photon', value: '\\(p=\\frac{h}{\\lambda}=\\frac{\\varepsilon}{c}\\)' },
    ],
  },
  {
    id: 'exam-shortcuts',
    title: 'Mẫu nhận diện nhanh trong đề Lý CSCA/THPT',
    grade: 'Chung',
    area: 'Chiến thuật',
    summary: 'Từ khóa trong đề thường dẫn đến công thức nào, giúp tìm nhanh khi đọc đề tiếng Trung.',
    keywords: ['csca', 'thi thpt', 'tu khoa', 'nhan dien', '考试', '关键词'],
    formulas: [
      { label: '匀变速直线运动', value: 'Dùng \\(v=v_0+at\\), \\(s=v_0t+\\frac{1}{2}at^2\\), \\(v^2-v_0^2=2as\\).' },
      { label: '向心力 / 圆周运动', value: 'Dùng \\(F_{ht}=m\\frac{v^2}{r}=m\\omega^2r\\).' },
      { label: '机械能守恒', value: 'Dùng \\(\\frac{1}{2}mv_1^2+mgh_1=\\frac{1}{2}mv_2^2+mgh_2\\).' },
      { label: '电场强度 / 电势差', value: 'Dùng \\(E=\\frac{F}{q}\\), \\(A=qU\\), \\(E=\\frac Ud\\).' },
      { label: '闭合电路', value: 'Dùng \\(I=\\frac{\\mathcal E}{R+r}\\), \\(U=\\mathcal E-Ir\\).' },
      { label: '电磁感应', value: 'Dùng \\(|e|=N\\lvert\\frac{\\Delta\\Phi}{\\Delta t}\\rvert\\), \\(\\Phi=BS\\cos\\alpha\\).' },
      { label: '简谐振动', value: 'Dùng \\(x=A\\cos(\\omega t+\\varphi)\\), \\(v_{max}=\\omega A\\), \\(a=-\\omega^2x\\).' },
      { label: '交流电路 RLC', value: 'Dùng \\(Z=\\sqrt{R^2+(Z_L-Z_C)^2}\\), \\(P=UI\\cos\\varphi\\).' },
      { label: '光电效应', value: 'Dùng \\(hf=A+\\frac{1}{2}mv_{0max}^2\\), \\(\\lambda_0=\\frac{hc}{A}\\).' },
      { label: '核反应', value: 'Dùng bảo toàn \\(A,Z\\) và \\(Q=(m_{truoc}-m_{sau})c^2\\).' },
    ],
    notes: ['Từ khóa chỉ là gợi ý. Vẫn cần đọc kỹ đơn vị, chiều dương, điều kiện áp dụng.'],
  },
];

export const PHYSICS_FORMULA_GRADE_OPTIONS: PhysicsFormulaGrade[] = ['Chung', '10', '11', '12'];

export const PHYSICS_FORMULA_AREAS = Array.from(
  new Set(PHYSICS_CSCA_FORMULA_TOPICS.map(topic => topic.area)),
);
