'use client';
import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import AdminLayout from '@/components/layout/AdminLayout';
import { useAuthStore } from '@/lib/store/authStore';
import { hasPermission } from '@/lib/utils/permissions';
import { seoBlogApi, SeoPost, SeoIdea } from '@/lib/api/seoBlog';
import { FiArchive, FiCalendar, FiCheckCircle, FiEdit3, FiExternalLink, FiFileText, FiPlus, FiRefreshCw, FiSearch, FiSend, FiTrash2, FiX } from 'react-icons/fi';

const TOPICS=[['Luyện thi CSCA','luyện thi CSCA'],['Toán CSCA','toán CSCA'],['Vật lý CSCA','vật lý CSCA'],['Hóa học CSCA','hóa học CSCA'],['Tiếng Trung CSCA','tiếng Trung CSCA'],['Đề thi & chiến thuật','đề thi CSCA'],['Học bổng CSC','học bổng CSC'],['Học bổng trường','học bổng đại học Trung Quốc'],['Hồ sơ du học','hồ sơ du học Trung Quốc'],['Visa & thủ tục','visa du học Trung Quốc'],['Chọn trường & ngành','chọn trường Trung Quốc'],['Chi phí du học','chi phí du học Trung Quốc'],['Đời sống du học sinh','đời sống du học Trung Quốc'],['Kinh nghiệm apply','kinh nghiệm apply Trung Quốc'],['Công cụ & tài liệu học','tài liệu ôn thi CSCA']];
const blank:Partial<SeoPost>={title:'',slug:'',excerpt:'',content:'',meta_title:'',meta_description:'',primary_keyword:'',secondary_keywords:[],category:'Luyện thi CSCA',search_intent:'informational',status:'draft'};
const cls='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-violet-500 focus:ring-2 focus:ring-violet-100 dark:border-slate-700 dark:bg-slate-900 dark:text-white';

export default function Page(){
 const router=useRouter(),{user}=useAuthStore(),allowed=hasPermission(user,'content.manage');
 const [posts,setPosts]=useState<SeoPost[]>([]),[draft,setDraft]=useState<Partial<SeoPost>>(blank),[secondary,setSecondary]=useState(''),[ideas,setIdeas]=useState<SeoIdea[]>([]),[ideaFocus,setIdeaFocus]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[notice,setNotice]=useState('');
 const load=async()=>{setLoading(true);try{setPosts((await seoBlogApi.list({search,status})).posts)}catch{setNotice('Không tải được danh sách bài viết.')}finally{setLoading(false)}};
 useEffect(()=>{if(user&&!allowed)router.replace('/admin')},[user,allowed,router]); useEffect(()=>{if(allowed)void load()},[allowed,status]); // eslint-disable-line react-hooks/exhaustive-deps
 const edit=(p?:SeoPost)=>{const v=p||blank;setDraft({...v});setSecondary((v.secondary_keywords||[]).join(', '));setOpen(true)};
 const payload=()=>({...draft,secondary_keywords:secondary.split(',').map(x=>x.trim()).filter(Boolean)});
 const save=async()=>{setBusy(true);try{const p=payload();const x=draft.id?await seoBlogApi.update(draft.id,p):await seoBlogApi.create(p);setDraft(x);setNotice('Đã lưu bản nháp.');await load()}catch{setNotice('Lưu bài thất bại.')}finally{setBusy(false)}};
 const findImage=async()=>{if(!draft.primary_keyword){setNotice('Hãy nhập từ khóa chính trước khi tìm ảnh.');return}setBusy(true);try{const image=await seoBlogApi.searchImage(draft.primary_keyword);if(!image){setNotice('Chưa tìm thấy ảnh. Hãy cấu hình Pexels, Unsplash hoặc thư viện ảnh chủ đề.');return}setDraft({...draft,cover_image:image.url,cover_image_alt:image.alt,cover_image_source:image.source,cover_image_source_url:image.source_url});setNotice('Đã chọn ảnh đúng chủ đề, nhớ lưu lại bản nháp.')}catch{setNotice('Tìm ảnh thất bại.')}finally{setBusy(false)}};
 const suggestIdeas=async()=>{setBusy(true);setNotice('AI đang nghiên cứu các cụm chủ đề chưa bị trùng...');try{const next=await seoBlogApi.suggestIdeas(ideaFocus);setIdeas(next);setNotice(`AI đã tạo ${next.length} ý tưởng khác nhau. Chọn một ý tưởng bên dưới.`)}catch{setNotice('Không thể tạo ý tưởng lúc này.')}finally{setBusy(false)}};
 const chooseIdea=(idea:SeoIdea)=>{setDraft({...draft,topic:idea.topic,category:idea.category,primary_keyword:idea.primary_keyword,search_intent:idea.search_intent});setSecondary((idea.secondary_keywords||[]).join(', '));setNotice(`Đã chọn: ${idea.primary_keyword}`)};
 const generate=async()=>{if(!draft.primary_keyword){setNotice('Hãy nhập từ khóa chính.');return}setBusy(true);setNotice('AI đang viết bản nháp...');try{const x=await seoBlogApi.generateDraft({primary_keyword:draft.primary_keyword,secondary_keywords:payload().secondary_keywords||[],category:draft.category||'',search_intent:draft.search_intent||'informational',topic:draft.topic});setDraft(x);setSecondary((x.secondary_keywords||[]).join(', '));setNotice('Đã tạo xong, hãy duyệt kỹ trước khi đăng.');await load()}catch{setNotice('Tạo bài thất bại. Kiểm tra cấu hình AI/backend.')}finally{setBusy(false)}};
 const act=async(k:string)=>{if(!draft.id){setNotice('Hãy lưu bản nháp trước.');return}if(k==='delete'&&!confirm('Xóa vĩnh viễn bài này?'))return;setBusy(true);try{if(k==='publish')await seoBlogApi.publish(draft.id);if(k==='schedule'){if(!draft.scheduled_at)throw 0;await seoBlogApi.schedule(draft.id,new Date(draft.scheduled_at).toISOString())}if(k==='archive')await seoBlogApi.archive(draft.id);if(k==='delete')await seoBlogApi.remove(draft.id);setOpen(false);setNotice('Đã cập nhật bài viết.');await load()}catch{setNotice('Thao tác thất bại.')}finally{setBusy(false)}};
 const shown=useMemo(()=>posts.filter(p=>!search||`${p.title} ${p.primary_keyword}`.toLowerCase().includes(search.toLowerCase())),[posts,search]); if(!allowed)return null;
 return <AdminLayout title="SEO Blog tự động" description="Tạo, tối ưu và đặt lịch bài viết — không cần deploy lại website"><div className="space-y-5">
 {notice&&<div className="flex justify-between rounded-xl border border-violet-200 bg-violet-50 p-3 text-sm text-violet-800">{notice}<button onClick={()=>setNotice('')}><FiX/></button></div>}
 <div className="grid gap-4 md:grid-cols-3"><Stat l="Tổng bài" v={posts.length}/><Stat l="Đã xuất bản" v={posts.filter(p=>p.status==='published').length}/><Stat l="Chờ lịch" v={posts.filter(p=>p.status==='scheduled').length}/></div>
 <section className="rounded-2xl border bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold dark:text-white">Kho nội dung</h2><p className="text-sm text-slate-500">Duyệt bản nháp trước khi xuất bản.</p></div><button onClick={()=>edit()} className="flex items-center justify-center gap-2 rounded-xl bg-violet-600 px-4 py-2.5 text-sm font-semibold text-white"><FiPlus/> Tạo bài bằng AI</button></div>
 <div className="mt-4 grid gap-3 sm:grid-cols-[1fr_180px_auto]"><label className="relative"><FiSearch className="absolute left-3 top-3 text-slate-400"/><input className={`${cls} pl-9`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="Tìm bài hoặc từ khóa..."/></label><select className={cls} value={status} onChange={e=>setStatus(e.target.value)}><option value="">Mọi trạng thái</option><option value="draft">Bản nháp</option><option value="scheduled">Đặt lịch</option><option value="published">Đã đăng</option><option value="archived">Lưu trữ</option></select><button onClick={load} className="rounded-xl border px-4"><FiRefreshCw/></button></div>
 <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b text-xs uppercase text-slate-400"><tr><th className="py-3">Bài viết</th><th>Từ khóa</th><th>SEO</th><th>Trạng thái</th><th>Lịch đăng</th><th/></tr></thead><tbody className="divide-y dark:divide-slate-800">{loading?<tr><td colSpan={6} className="py-10 text-center">Đang tải...</td></tr>:shown.map(p=><tr key={p.id}><td className="py-3"><b className="dark:text-white">{p.title}</b><p className="text-xs text-slate-400">/{p.slug}</p></td><td>{p.primary_keyword}</td><td>{p.seo_score??'—'}/100</td><td><Badge s={p.status}/></td><td>{p.scheduled_at?new Date(p.scheduled_at).toLocaleString('vi-VN'):'—'}</td><td><button onClick={()=>edit(p)} className="p-2 text-violet-600"><FiEdit3/></button></td></tr>)}</tbody></table></div></section></div>
 {open&&<div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-3"><div className="mx-auto my-3 max-w-6xl rounded-2xl bg-slate-50 dark:bg-slate-950"><header className="sticky top-0 z-10 flex justify-between rounded-t-2xl border-b bg-white/95 p-4 dark:border-slate-800 dark:bg-slate-900/95"><div><b className="dark:text-white">{draft.id?'Biên tập bài SEO':'Tạo bài SEO mới'}</b><p className="text-xs text-slate-500">Múi giờ: Asia/Ho_Chi_Minh</p></div><button onClick={()=>setOpen(false)}><FiX/></button></header><div className="grid gap-5 p-5 lg:grid-cols-[1fr_330px]"><main className="space-y-4">
 <Card t="1. Từ khóa & ý định"><div className="mb-4 rounded-xl border border-fuchsia-100 bg-fuchsia-50/60 p-3"><p className="text-sm font-bold text-fuchsia-800">Để AI tự lên cụm chủ đề đa dạng</p><p className="mb-2 text-xs text-fuchsia-600">AI sẽ tránh từ khóa đã có và tạo 12 góc nội dung khác nhau.</p><div className="flex flex-col gap-2 sm:flex-row"><input className={cls} value={ideaFocus} onChange={e=>setIdeaFocus(e.target.value)} placeholder="Định hướng tùy chọn, ví dụ: học bổng, đời sống..."/><button disabled={busy} onClick={suggestIdeas} className="shrink-0 rounded-xl bg-fuchsia-600 px-4 py-2 text-sm font-semibold text-white">AI đề xuất ý tưởng</button></div>{ideas.length>0&&<div className="mt-3 grid gap-2 sm:grid-cols-2">{ideas.map((idea,index)=><button key={`${idea.primary_keyword}-${index}`} onClick={()=>chooseIdea(idea)} className="rounded-xl border border-fuchsia-100 bg-white p-3 text-left hover:border-fuchsia-400"><b className="block text-sm text-slate-800">{idea.primary_keyword}</b><span className="text-xs text-slate-500">{idea.category} · {idea.angle||idea.search_intent}</span></button>)}</div>}</div><div className="grid gap-3 sm:grid-cols-2"><select className={cls} value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{TOPICS.map(x=><option key={x[0]}>{x[0]}</option>)}</select><select className={cls} value={draft.search_intent} onChange={e=>setDraft({...draft,search_intent:e.target.value})}><option value="informational">Tìm thông tin</option><option value="commercial">So sánh</option><option value="transactional">Chuyển đổi</option></select><input list="keys" className={cls} value={draft.primary_keyword||''} onChange={e=>setDraft({...draft,primary_keyword:e.target.value})} placeholder="Từ khóa chính *"/><datalist id="keys">{TOPICS.map(x=><option key={x[1]} value={x[1]}/>)}</datalist><input className={cls} value={secondary} onChange={e=>setSecondary(e.target.value)} placeholder="Từ khóa phụ, cách nhau bằng dấu phẩy"/></div><button disabled={busy} onClick={generate} className="mt-3 flex gap-2 rounded-xl bg-gradient-to-r from-violet-600 to-fuchsia-600 px-4 py-2.5 text-sm font-semibold text-white"><FiFileText/>{busy?'Đang xử lý...':'Tạo bản nháp chuẩn SEO'}</button></Card>
 <Card t="2. Nội dung & metadata"><Fields draft={draft} setDraft={setDraft}/></Card></main><aside className="space-y-4"><Card t="Ảnh đúng chủ đề">{draft.cover_image?<img src={draft.cover_image} alt={draft.cover_image_alt||''} className="mb-3 aspect-video w-full rounded-xl object-cover"/>:<div className="mb-3 flex aspect-video items-center justify-center rounded-xl bg-slate-100 text-sm text-slate-400">Chưa có ảnh</div>}<button disabled={busy} onClick={findImage} className="mb-2 w-full rounded-xl border border-violet-200 px-3 py-2 text-sm font-semibold text-violet-700">Tìm ảnh theo từ khóa chính</button><input className={cls} value={draft.cover_image||''} onChange={e=>setDraft({...draft,cover_image:e.target.value})} placeholder="URL ảnh"/><input className={`${cls} mt-2`} value={draft.cover_image_alt||''} onChange={e=>setDraft({...draft,cover_image_alt:e.target.value})} placeholder="Alt ảnh"/>{draft.cover_image_source_url&&<a href={draft.cover_image_source_url} target="_blank" rel="noreferrer" className="mt-2 flex gap-1 text-xs text-violet-600"><FiExternalLink/>{draft.cover_image_source||'Nguồn ảnh'}</a>}</Card>
 <Card t={`Điểm SEO: ${draft.seo_score??'—'}/100`}><div className="h-2 rounded bg-slate-200"><div className="h-full rounded bg-emerald-500" style={{width:`${draft.seo_score||0}%`}}/></div>{draft.seo_issues?.map((x,i)=><p key={i} className="mt-2 flex gap-2 text-xs"><FiCheckCircle className={x.ok?'text-emerald-500':'text-amber-500'}/>{x.message}</p>)}</Card>
 {!!draft.cannibalization?.length&&<Card t="Cảnh báo trùng từ khóa">{draft.cannibalization.map(x=><p key={x.id} className="mb-2 rounded bg-amber-50 p-2 text-xs text-amber-800"><b>{x.title}</b>{x.similarity!=null&&` · ${Math.round(x.similarity*100)}% giống`}</p>)}</Card>}
 <Card t="Xuất bản"><label className="text-xs font-semibold">Ngày giờ Việt Nam<input type="datetime-local" className={`${cls} mt-1`} value={draft.scheduled_at?.slice(0,16)||''} onChange={e=>setDraft({...draft,scheduled_at:e.target.value})}/></label><div className="mt-3 grid grid-cols-2 gap-2"><button disabled={busy} onClick={save} className="rounded-xl border p-2 text-sm text-violet-700">Lưu nháp</button><button onClick={()=>act('schedule')} className="flex items-center justify-center gap-1 rounded-xl bg-slate-800 p-2 text-sm text-white"><FiCalendar/>Đặt lịch</button><button onClick={()=>act('publish')} className="col-span-2 flex items-center justify-center gap-2 rounded-xl bg-emerald-600 p-2.5 text-sm text-white"><FiSend/>Đăng ngay</button>{draft.id&&<><button onClick={()=>act('archive')} className="flex justify-center gap-1 p-2 text-xs"><FiArchive/>Lưu trữ</button><button onClick={()=>act('delete')} className="flex justify-center gap-1 p-2 text-xs text-red-500"><FiTrash2/>Xóa</button></>}</div></Card></aside></div></div></div>}
 </AdminLayout>}

function Fields({draft,setDraft}:{draft:Partial<SeoPost>;setDraft:(x:Partial<SeoPost>)=>void}){const f=(k:keyof SeoPost)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement>)=>setDraft({...draft,[k]:e.target.value});return <div className="space-y-3"><input className={cls} value={draft.title||''} onChange={f('title')} placeholder="Tiêu đề bài"/><div className="grid gap-3 sm:grid-cols-2"><input className={cls} value={draft.slug||''} onChange={f('slug')} placeholder="Slug"/><input className={cls} value={draft.meta_title||''} onChange={f('meta_title')} placeholder="SEO title"/></div><textarea rows={3} className={cls} value={draft.meta_description||''} onChange={f('meta_description')} placeholder={`Meta description (${draft.meta_description?.length||0}/160)`}/><textarea rows={3} className={cls} value={draft.excerpt||''} onChange={f('excerpt')} placeholder="Đoạn giới thiệu"/><textarea rows={18} className={`${cls} font-mono`} value={draft.content||''} onChange={f('content')} placeholder="Nội dung Markdown/HTML"/></div>}
function Card({t,children}:{t:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-white p-4 shadow-sm dark:border-slate-800 dark:bg-slate-900"><h3 className="mb-3 font-bold dark:text-white">{t}</h3>{children}</section>}
function Stat({l,v}:{l:string;v:number}){return <div className="rounded-2xl border bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><p className="text-sm text-slate-500">{l}</p><p className="text-2xl font-black dark:text-white">{v}</p></div>}
function Badge({s}:{s:string}){const m:any={draft:['Bản nháp','bg-amber-100 text-amber-700'],scheduled:['Đặt lịch','bg-blue-100 text-blue-700'],published:['Đã đăng','bg-emerald-100 text-emerald-700'],archived:['Lưu trữ','bg-slate-100 text-slate-600']};return <span className={`rounded-full px-2 py-1 text-xs ${m[s]?.[1]}`}>{m[s]?.[0]||s}</span>}
